import React, { useState } from 'react';
import { Text, TextInput, View } from 'react-native';
import { Screen } from '@/src/components/ui/Screen';
import { Button } from '@/src/components/ui/Button';
import { ChoiceChip } from '@/src/components/ui/ChoiceChip';
import { GroupedSection } from '@/src/components/ui/GroupedSection';
import { createRoutineDraft, manualRoutineItem, validateRoutineDraft, type RoutineDraft, type RoutineItemDraft, type RoutineReference } from '@/src/presentation/p0b-personalization/draft';
import { styles } from './ContextFlow';
export interface RoutineContextProps { initialDraft?: RoutineDraft; createItemId: () => string; availableProducts?: readonly Extract<RoutineReference, { kind: 'catalog' }>[]; onApply: (draft: RoutineDraft) => void; onSkip: () => void; loading?: boolean; error?: string | null }
export function RoutineContext({ initialDraft, createItemId, availableProducts = [], onApply, onSkip, loading = false, error }: RoutineContextProps) {
  const [draft, setDraft] = useState(() => createRoutineDraft(initialDraft));
  const [name, setName] = useState('');
  const [validation, setValidation] = useState<string | null>(null);
  const update = (id: string, patch: Partial<RoutineItemDraft>) => { setValidation(null); setDraft(current => ({ ...current, items: current.items.map(item => item.id === id ? { ...item, ...patch } : item) })); };
  return <Screen scrollable><Text style={styles.title}>Your routine, a little at a time</Text>
    <Text style={styles.copy}>Add what matters for this Check. Names you enter stay unverified until matched to product evidence.</Text>
    <GroupedSection header="Add a product"><View style={styles.group}>
      <TextInput style={styles.input} editable={!loading} accessibilityLabel="Routine product name" placeholder="Product name" value={name} onChangeText={setName} />
      <Button label="Add product" disabled={loading || !name.trim() || draft.items.length >= 50} onPress={() => { const id = createItemId(); if (draft.items.some(item => item.id === id)) { setValidation('This item already exists. Please try again.'); return; } setDraft(current => ({ ...current, items: [...current.items, manualRoutineItem(id, name)] })); setName(''); }} />
    </View></GroupedSection>
    {availableProducts.length > 0 && <GroupedSection header="Products from your saved collection"><View style={styles.group}>{availableProducts.map(product => <Button key={product.productId + ':' + product.variantId + ':' + product.formulaVersionId} label={`Add ${product.label}`} disabled={loading || draft.items.length >= 50} onPress={() => { const id = createItemId(); if (draft.items.some(item => item.id === id)) { setValidation('This item already exists. Please try again.'); return; } setDraft(current => ({ ...current, items: [...current.items, { ...manualRoutineItem(id, product.label), reference: { ...product } }] })); }} />)}</View></GroupedSection>}
    {draft.items.map(item => <GroupedSection key={item.id} header={item.reference.label} footer={item.reference.kind === 'manual' ? "Manual name. Formula and ingredients are unverified." : "Product reference supplied by your saved collection. Missing formula context stays unknown."}><View style={styles.group}>
      {item.reference.kind === 'manual' && <TextInput style={styles.input} accessibilityLabel={`Edit product name ${item.reference.label}`} editable={!loading} value={item.reference.label} onChangeText={label => update(item.id, { reference: { ...item.reference, label } })} />}
      <Text style={styles.copy}>Use status</Text><View style={styles.chips}>{(['current', 'paused', 'stopped', 'occasional'] as const).map(value => <ChoiceChip key={value} label={value[0].toUpperCase() + value.slice(1)} disabled={loading} selected={item.status === value} onSelect={() => update(item.id, { status: value })} />)}</View>
      <Text style={styles.copy}>When</Text><View style={styles.chips}>{([['am', 'Morning'], ['pm', 'Evening'], ['both', 'Both'], ['unknown', 'Not sure']] as const).map(([value, label]) => <ChoiceChip key={value} label={label} disabled={loading} selected={item.timing === value} onSelect={() => update(item.id, { timing: value })} />)}</View>
      <Text style={styles.copy}>How often</Text><View style={styles.chips}>{([['daily', 'Daily'], ['few_times_week', 'A few times a week'], ['less_often', 'Less often'], ['most_days', 'Most days'], ['weekly', 'Weekly'], ['as_needed', 'As needed']] as const).map(([value, label]) => <ChoiceChip key={value} label={label} disabled={loading} selected={item.frequency.kind === 'qualitative' && item.frequency.value === value} onSelect={() => update(item.id, { frequency: { kind: 'qualitative', value } })} />)}<ChoiceChip label="Not sure" selected={item.frequency.kind === 'unknown'} disabled={loading} onSelect={() => update(item.id, { frequency: { kind: 'unknown' } })} /></View>
      <TextInput style={styles.input} accessibilityLabel={`Exact use count for ${item.reference.label}`} editable={!loading} keyboardType="numeric" placeholder="Exact use count, if known" value={item.frequency.kind === 'exact' ? String(item.frequency.count) : ''} onChangeText={text => { if (!text.trim()) { update(item.id, { frequency: { kind: 'unknown' } }); return; } const count = Number(text); if (!/^\d+$/.test(text) || !Number.isSafeInteger(count) || count < 1 || count > 100) { setValidation('Enter a whole number from 1 to 100.'); return; } setValidation(null); update(item.id, { frequency: { kind: 'exact', count, unit: item.frequency.kind === 'exact' ? item.frequency.unit : 'week' } }); }} />
      {item.frequency.kind === 'exact' && <View style={styles.chips}>{(['day', 'week', 'month'] as const).map(unit => <ChoiceChip key={unit} label={`Per ${unit}`} disabled={loading} selected={item.frequency.kind === 'exact' && item.frequency.unit === unit} onSelect={() => { if (item.frequency.kind === 'exact') update(item.id, { frequency: { ...item.frequency, unit } }); }} />)}</View>}
      <Button label="Remove product" variant="ghost" disabled={loading} onPress={() => setDraft(current => ({ ...current, items: current.items.filter(value => value.id !== item.id) }))} />
    </View></GroupedSection>)}
    <GroupedSection header="How much of your routine is here?" footer="A partial routine cannot establish that you use no other products."><View style={[styles.group, styles.chips]}>{([['partial', 'Some of my routine'], ['complete', 'My whole routine'], ['unknown', 'Not sure']] as const).map(([value, label]) => <ChoiceChip key={value} label={label} disabled={loading} selected={draft.completeness === value} onSelect={() => setDraft(current => ({ ...current, completeness: value }))} />)}</View></GroupedSection>
    {(error || validation) && <Text accessibilityRole="alert" style={styles.copy}>{error || validation}</Text>}
    <Button label="Use this routine context" loading={loading} disabled={!!validation || draft.items.some(item => !item.reference.label.trim())} onPress={() => { const message = validateRoutineDraft(draft); setValidation(message); if (!message) onApply(createRoutineDraft(draft)); }} />
    <Button label="Skip routine context" variant="ghost" disabled={loading} onPress={onSkip} />
  </Screen>;
}
