begin;
select plan(29);
select has_table('public', 'personal_context_heads', 'Owner revision head exists');
select has_table('public', 'personal_context_revisions', 'Immutable context journal exists');
select has_table('public', 'personal_decision_assessments', 'Immutable assessment provenance exists');
select ok(not has_table_privilege('authenticated','public.personal_context_revisions','SELECT,INSERT,UPDATE,DELETE'), 'Raw context unavailable to authenticated');
select ok(not has_table_privilege('anon','public.personal_context_revisions','SELECT,INSERT,UPDATE,DELETE'), 'Raw context unavailable to anon');
select ok(not has_table_privilege('authenticated','public.personal_context_heads','SELECT,INSERT,UPDATE,DELETE'), 'Raw owner heads unavailable to authenticated');
select ok(not has_table_privilege('anon','public.personal_context_heads','SELECT,INSERT,UPDATE,DELETE'), 'Raw owner heads unavailable to anon');
select ok(not has_table_privilege('authenticated','public.personal_decision_assessments','SELECT,INSERT,UPDATE,DELETE'), 'Raw decisions unavailable to authenticated');
select ok(not has_table_privilege('anon','public.personal_decision_assessments','SELECT,INSERT,UPDATE,DELETE'), 'Raw decisions unavailable to anon');
select ok(not has_function_privilege('anon','public.write_personal_context(uuid,uuid,bigint,text,jsonb,uuid)','EXECUTE'), 'Context write RPC unavailable to anon');
select ok(not has_function_privilege('authenticated','public.read_personal_context(uuid)','EXECUTE'), 'Context read RPC unavailable to clients');
select ok(not has_function_privilege('authenticated','public.read_personal_experience_history(uuid,bigint,integer,uuid,uuid)','EXECUTE'), 'History read RPC unavailable to clients');
select ok(not has_function_privilege('authenticated','public.persist_personal_decision_assessment(uuid,uuid,jsonb,jsonb,uuid,uuid,uuid,text,text,text,text)','EXECUTE'), 'Decision write RPC unavailable to clients');
select ok(not has_function_privilege('authenticated','public.write_personal_context(uuid,uuid,bigint,text,jsonb,uuid)','EXECUTE'), 'Context RPC unavailable to clients');
insert into auth.users(id, instance_id, aud, role, email, encrypted_password, created_at, updated_at)
values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','00000000-0000-0000-0000-000000000000','authenticated','authenticated','p0b-a@example.test','',now(),now()),
('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','00000000-0000-0000-0000-000000000000','authenticated','authenticated','p0b-b@example.test','',now(),now());
create temporary table writes(payload jsonb);
insert into writes select public.write_personal_context('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc',0,'routine','{"completeness":"partial","items":[]}',null);
select is((select payload->'revision'->>'revision' from writes),'1','First write advances revision');
select is(public.write_personal_context('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc',0,'routine','{"completeness":"partial","items":[]}',null)->>'replayed','true','Exact replay succeeds despite old base');
select throws_ok($$select public.write_personal_context('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc',0,'routine','{"completeness":"complete","items":[]}',null)$$,'P0001','IDEMPOTENCY_CONFLICT','Changed replay rejected');
select throws_ok($$select public.write_personal_context('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','dddddddd-dddd-4ddd-8ddd-dddddddddddd',0,'routine','{"completeness":"partial","items":[]}',null)$$,'P0001','STALE_CONTEXT','Stale new write rejected');
select is(public.read_personal_context('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb')->>'revision','0','Other owner remains empty');
select throws_ok($$update public.personal_context_revisions set payload = '{}' where user_id = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'$$,'P0001','IMMUTABLE_CONTEXT_REVISION','Revision updates prohibited');
insert into writes select public.write_personal_context('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',1,'experience','{"id":"ffffffff-ffff-4fff-8fff-ffffffffffff","reference":{"kind":"manual","name":"Old lotion"},"kind":"no_reaction_reported","occurred":{"start":null,"end":null},"useContext":null,"symptoms":[],"note":null}',null);
select is(public.read_personal_context('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')->'experiences'->0->'data'->>'kind','no_reaction_reported','No reaction stays distinct from tolerance');
select throws_ok($$select public.write_personal_context('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',0,'experience','{"id":"ffffffff-ffff-4fff-8fff-ffffffffffff"}',(select id from public.personal_context_revisions where section='experience' limit 1))$$,'P0001','EXPERIENCE_CORRECTION_CONFLICT','Cross-owner correction rejected');
select is(public.persist_personal_decision_assessment('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"expectedContextRevision":2}','{"fixture":true}',null,(select id from public.personal_context_revisions where section='routine' limit 1),(select id from public.personal_context_revisions where section='experience' limit 1),'fixture','fixture','fixture','fixture')->>'replayed','false','Assessment binds current revision');
insert into writes select public.write_personal_context('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','22222222-2222-4222-8222-222222222222',2,'routine','{"completeness":"complete","items":[]}',null);
select is(public.persist_personal_decision_assessment('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"expectedContextRevision":2}','{"fixture":true}',null,null,null,'fixture','fixture','fixture','fixture')->>'replayed','true','Replay after edit returns immutable winning assessment');
select throws_ok($$select public.persist_personal_decision_assessment('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','33333333-3333-4333-8333-333333333333','{"expectedContextRevision":2}','{"fixture":true}',null,null,null,'fixture','fixture','fixture','fixture')$$,'P0001','STALE_CONTEXT','Changed context between evaluation and persistence rejected');
select throws_ok($$select public.persist_personal_decision_assessment('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','44444444-4444-4444-8444-444444444444','{}','{"fixture":true}',null,null,null,'fixture','fixture','fixture','fixture')$$,'P0001','INVALID_CONTEXT_REVISION','Missing expected context revision rejected');
select throws_ok($$select public.persist_personal_decision_assessment('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','55555555-5555-4555-8555-555555555555','{"expectedContextRevision":0}','{"fixture":true}',null,(select id from public.personal_context_revisions where section='routine' limit 1),null,'fixture','fixture','fixture','fixture')$$,'P0001','ASSESSMENT_CONTEXT_OWNER_MISMATCH','Assessment revision links cannot cross owners');
delete from auth.users where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
select is((select count(*)::int from public.personal_context_revisions where user_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),0,'Identity deletion cascades context');
select is((select count(*)::int from public.personal_context_heads where user_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),0,'Identity deletion cascades heads');
select * from finish();
rollback;
