begin;
select plan(24);
select ok((select not(evaluate_allowed or display_allowed or store_allowed or revoked) from private.part_four_routine_authority),'Routine authority starts denied');
select is((select count(*)::integer from private.part_four_routine_formula_associations),0,'No guessed routine association is seeded');
select is((select count(*)::integer from private.part_four_routine_source_grants),0,'No external source grant is seeded');
select ok(not has_table_privilege('anon','private.part_four_routine_authority','SELECT,INSERT,UPDATE,DELETE'),'anon cannot access part_four_routine_authority');
select ok(not has_table_privilege('authenticated','private.part_four_routine_authority','SELECT,INSERT,UPDATE,DELETE'),'authenticated cannot access part_four_routine_authority');
select ok(not has_table_privilege('anon','private.part_four_routine_formula_associations','SELECT,INSERT,UPDATE,DELETE'),'anon cannot access part_four_routine_formula_associations');
select ok(not has_table_privilege('authenticated','private.part_four_routine_formula_associations','SELECT,INSERT,UPDATE,DELETE'),'authenticated cannot access part_four_routine_formula_associations');
select ok(not has_table_privilege('anon','private.part_four_routine_source_grants','SELECT,INSERT,UPDATE,DELETE'),'anon cannot access part_four_routine_source_grants');
select ok(not has_table_privilege('authenticated','private.part_four_routine_source_grants','SELECT,INSERT,UPDATE,DELETE'),'authenticated cannot access part_four_routine_source_grants');
select ok(not has_table_privilege('anon','private.part_four_source_withdrawals','SELECT,INSERT,UPDATE,DELETE'),'anon cannot access part_four_source_withdrawals');
select ok(not has_table_privilege('authenticated','private.part_four_source_withdrawals','SELECT,INSERT,UPDATE,DELETE'),'authenticated cannot access part_four_source_withdrawals');
select ok(not has_function_privilege('anon','public.part_four_routine_formula_worker(uuid,jsonb)','EXECUTE'),'anon cannot mint canonical evidence via public.part_four_routine_formula_worker');
select ok(not has_function_privilege('authenticated','public.part_four_routine_formula_worker(uuid,jsonb)','EXECUTE'),'authenticated cannot mint canonical evidence via public.part_four_routine_formula_worker');
select ok(has_function_privilege('service_role','public.part_four_routine_formula_worker(uuid,jsonb)','EXECUTE'),'Service can call public.part_four_routine_formula_worker');
select ok(not has_function_privilege('anon','public.part_three_worker(uuid,text,jsonb)','EXECUTE'),'anon cannot mint canonical evidence via public.part_three_worker');
select ok(not has_function_privilege('authenticated','public.part_three_worker(uuid,text,jsonb)','EXECUTE'),'authenticated cannot mint canonical evidence via public.part_three_worker');
select ok(has_function_privilege('service_role','public.part_three_worker(uuid,text,jsonb)','EXECUTE'),'Service can call public.part_three_worker');
select ok(not has_function_privilege('service_role','public.part_three_worker_foundation_v1(uuid,text,jsonb)','EXECUTE'),'Trusted service cannot bypass P4 wrapper through old writer');
select ok(not has_function_privilege('authenticated','private.part_four_retained_packet(jsonb,text,timestamptz,text[])','EXECUTE'),'Client cannot override retained projection');
select ok(not has_table_privilege('service_role','private.part_four_source_withdrawals','DELETE'),'Trusted service cannot erase withdrawal registry');
select ok(has_table_privilege('service_role','private.part_four_source_withdrawals','INSERT,SELECT,UPDATE'),'Trusted service can record opaque withdrawals');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='part_three_saved_assessments' and column_name='original_packet_hash'),'Original visible packet identity survives projection');
select ok((select relrowsecurity from pg_class where oid='private.part_four_routine_formula_associations'::regclass),'Routine association RLS enabled');
select ok((select relrowsecurity from pg_class where oid='private.part_four_source_withdrawals'::regclass),'Withdrawal registry RLS enabled');
select * from finish();
rollback;
