begin;
select plan(20);
select ok(not has_function_privilege('anon','public.part_three_worker(uuid,text,jsonb)','EXECUTE'),'Anonymous cannot call trusted Part3 worker');
select ok(not has_function_privilege('authenticated','public.part_three_worker(uuid,text,jsonb)','EXECUTE'),'Authenticated clients cannot bypass Edge ownership');
select ok(has_function_privilege('service_role','public.part_three_worker(uuid,text,jsonb)','EXECUTE'),'Trusted worker is composed through service-only RPC');
select ok(not has_table_privilege('authenticated','public.part_three_results','SELECT,INSERT,UPDATE,DELETE'),'Personal packets have no direct client table permissions');
select ok(not has_table_privilege('anon','public.part_three_saved_assessments','SELECT,INSERT,UPDATE,DELETE'),'Saved private packets are not anonymous metadata');
select ok(not has_table_privilege('authenticated','private.part_three_encounters','SELECT,INSERT,UPDATE,DELETE'),'Exposure latches cannot be reset by clients');
select ok(not has_table_privilege('authenticated','private.part_three_provider_attempts','SELECT,INSERT,UPDATE,DELETE'),'Provider traces are service-only');
select ok(not has_table_privilege('authenticated','private.part_three_external_grants','SELECT,INSERT,UPDATE,DELETE'),'Display clients cannot mint external processing permissions');
select ok((select not permitted and not provider_enabled and not processing_approved and not tradeoff_utility_approved and not question_utility_approved and not spend_cap_approved and circuit_open and token_budget_remaining=0 from private.part_three_release),'Every activation gate starts closed');
select is((select call_cap from private.part_three_release),1,'Interactive encounter model cap is one');
select throws_ok($$update private.part_three_release set call_cap=2$$,'23514',null,'Call cap cannot expand beyond one');
select throws_ok($$update private.part_three_release set token_budget_remaining=-1$$,'23514',null,'Token budget cannot become negative');
select throws_ok($$select public.part_three_worker('b3333333-3333-4333-8333-333333333333','read','{"resultId":"b3333333-3333-4333-8333-333333333334"}')$$,'42501','PART_THREE_FORBIDDEN','Owner profile is checked before private worker operations');
select is(public.part_three_worker(null,'release/register','{"releaseHash":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","localFixture":true}')->>'registered','true','Local source release registration is explicit');
select ok((select permitted and not provider_enabled from private.part_three_release),'Local release registration never activates provider');
select is(public.part_three_worker(null,'release/withdraw','{"releaseHash":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}')->>'withdrawn','true','Release withdrawal is acknowledged');
select public.part_three_worker(null,'release/register','{"releaseHash":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","localFixture":true}');
select ok((select not permitted from private.part_three_release),'Withdrawn immutable release cannot be reactivated');
create temporary table packet(value jsonb);
insert into packet values('{"resultRevision":2,"binding":{"refinement":{"configuredModel":"jev-1.13.0"}},"selectedTradeoffId":"optional-model","question":null,"refinementStatus":"accepted","refinementTrace":{"baselineTradeoffId":"optional-baseline","originalQuestion":{"id":"question-baseline"}}}');
select is(private.part_three_baseline_packet((select value from packet),3,false)->>'selectedTradeoffId','optional-baseline','Disabling optional selection restores baseline tradeoff');
select is(private.part_three_baseline_packet((select value from packet),3,false)->'question'->>'id','question-baseline','Unexposed baseline question is restored');
select ok(private.part_three_baseline_packet((select value from packet),3,true)->'question'='null'::jsonb and private.part_three_baseline_packet((select value from packet),3,true)->'refinementTrace'='null'::jsonb and private.part_three_baseline_packet((select value from packet),3,true)->'binding'->'refinement'='null'::jsonb,'Restoration respects exposure suppression and removes model authority');
select * from finish();
rollback;
