import assert from 'node:assert/strict';
import { createContextDraft, toggleSecondaryGoal, relevantQuestions, createRoutineDraft, manualRoutineItem, validateContextDraft } from '../src/presentation/p0b-personalization/draft.ts';
const draft = createContextDraft();
assert.equal(draft.pregnancy.state, 'unanswered');
assert.deepEqual(relevantQuestions(), []);
assert.deepEqual(relevantQuestions({ fields: ['pregnancy'], evidenceReason: 'Verified finding' }), ['pregnancy']);
assert.deepEqual(relevantQuestions({ fields: ['pregnancy'], evidenceReason: ' ' }), []);
const primary = { ...draft, primaryGoal: { state: 'answered' as const, value: 'hydration' as const } };
assert.equal(toggleSecondaryGoal(primary, 'hydration').secondaryGoals.length, 0);
const one = toggleSecondaryGoal(primary, 'texture');
const two = toggleSecondaryGoal(one, 'blemishes');
assert.equal(toggleSecondaryGoal(two, 'tone').secondaryGoals.length, 2);
assert.deepEqual(toggleSecondaryGoal(two, 'texture').secondaryGoals, ['blemishes']);
assert.equal(validateContextDraft(draft), null);
assert.equal(validateContextDraft({ ...draft, secondaryGoals: ['texture', 'tone', 'blemishes'] }), 'Choose up to two other goals.');
assert.equal(createRoutineDraft().completeness, 'unknown');
const item = manualRoutineItem('local-1', 'My cream');
assert.equal(item.reference.verification, 'unverified');
assert.equal(item.timing, 'unknown');
assert.deepEqual(item.frequency, { kind: 'unknown' });
const qualitative = { ...item, frequency: { kind: 'qualitative' as const, value: 'few_times_weekly' as const } };
assert.equal(qualitative.frequency.kind, 'qualitative');
assert.equal(createContextDraft({ ...draft, treatments: { state: 'answered', value: [] }, sensitivities: { state: 'withheld' } }).treatments.state, 'answered');
console.log('P0-B progressive context semantics passed');
const copy = createContextDraft(primary);
copy.secondaryGoals.push('comfort');
assert.deepEqual(primary.secondaryGoals, []);
const routine = createRoutineDraft({ completeness: 'partial', items: [qualitative] });
routine.items[0].reference.label = 'Edited';
assert.equal(qualitative.reference.label, 'My cream');
assert.equal(routine.completeness, 'partial');
