import { createContextDraft } from '../src/presentation/p0b-personalization/draft.ts';
import { profileToStorage } from '../src/presentation/p0b-personalization/storageAdapter.ts';
import assert from 'node:assert/strict';
import { createClient } from '@supabase/supabase-js';
import { captureCustomerFunctionClient, bindCustomerOwnerLifecycle, CustomerController } from '../src/presentation/personal-decision/customerController.ts';
import type { PersonalContextSnapshot } from '../src/contracts/PersonalContext.ts';
let liveOwner: string | null = 'A';
const principals: string[] = [];
const sdk = createClient('http://127.0.0.1:54321', 'synthetic-public-key', { accessToken: async () => { await Promise.resolve(); liveOwner = 'B'; return 'synthetic-token-b'; }, global: { fetch: async (_url, options) => { const header = new Headers(options?.headers).get('Authorization'); principals.push(header === 'Bearer synthetic-token-a' ? 'A' : header === 'Bearer synthetic-token-b' ? 'B' : 'unknown'); return new Response(JSON.stringify({ ok: true }), { status: 200, headers: { 'Content-Type': 'application/json' } }); } } });
const profile = createContextDraft(); profile.primaryGoal = { state: 'answered', value: 'dryness' };
const body = { operation: 'save_profile', requestId: '99999999-9999-4999-8999-999999999999', baseRevision: 0, profile: profileToStorage(profile) };
// The actual SDK selects its dynamic token asynchronously: this control reproduces the old hazard.
await sdk.functions.invoke('personal-context', { body }); assert.deepEqual(principals, ['B']);
principals.length = 0; liveOwner = 'A';
let clearedOwner: string | null | undefined;
const source = { functions: sdk.functions, auth: { getSession: async () => ({ data: { session: { access_token: 'synthetic-token-a', user: { id: 'A' } } }, error: null }) } };
const pinned = await captureCustomerFunctionClient('A', source, () => liveOwner, owner => { clearedOwner = owner; });
await assert.rejects(() => pinned.functions.invoke('personal-context', { body }));
assert.deepEqual(principals, ['A']); assert.equal(clearedOwner, 'B');
principals.length = 0; liveOwner = 'B'; await assert.rejects(() => captureCustomerFunctionClient('A', source, () => liveOwner, () => {})); assert.deepEqual(principals, []);
liveOwner = 'A'; await assert.rejects(() => captureCustomerFunctionClient('A', { ...source, auth: { getSession: async () => ({ data: { session: null } }) } }, () => liveOwner, owner => { clearedOwner = owner; })); assert.equal(clearedOwner, null);
await assert.rejects(() => captureCustomerFunctionClient('A', { ...source, auth: { getSession: async () => ({ data: { session: { access_token: 'synthetic-token-b', user: { id: 'B' } } } }) } }, () => liveOwner, () => {}));
console.log('Actual SDK owner rotation is pinned or aborted; token values were not logged');
const context: PersonalContextSnapshot = { version: 'personal-context-v1', ownerId: 'A', revision: 0, profile: null, routine: null, experiences: [], historyTruncated: false, historyRevision: null, legacy: { source: 'legacy_free_context', profile: null, products: [], experiences: [], truncated: false } };
let finish: ((context: PersonalContextSnapshot) => void) | undefined, calls = 0;
const controller = new CustomerController({ load: async () => ++calls === 1 ? context : new Promise(resolve => { finish = resolve; }), write: async () => { throw new Error('Unused'); }, evaluate: async () => ({ kind: 'unavailable', reason: 'Unused' }) }, () => 'request');
const authListeners = new Set<() => void>(), accessListeners = new Set<() => void>();
const subscribe = (listeners: Set<() => void>) => (listener: () => void) => { listeners.add(listener); return () => { listeners.delete(listener); }; };
liveOwner = 'A'; const stop = bindCustomerOwnerLifecycle(controller, () => liveOwner, subscribe(authListeners), subscribe(accessListeners)); await controller.load(); assert.equal(controller.getState().context?.ownerId, 'A');
const pending = controller.load(); liveOwner = null; authListeners.forEach(listener => listener()); assert.equal(controller.getState().context, null);
liveOwner = 'B'; accessListeners.forEach(listener => listener()); finish?.(context); await pending; assert.equal(controller.getState().ownerId, 'B'); assert.equal(controller.getState().context, null);
stop(); assert.equal(authListeners.size, 0); assert.equal(accessListeners.size, 0); assert.equal(controller.getState().ownerId, null);
console.log('Root owner lifecycle clears cached context without feature screens and fences late reads');
