import assert from 'node:assert/strict';
import { CustomerController } from '../src/presentation/personal-decision/customerController.ts';
import type { PersonalContextSnapshot, PersonalContextRequest } from '../src/contracts/PersonalContext.ts';
const snapshot = (ownerId: string, revision = 0): PersonalContextSnapshot => ({ version: 'personal-context-v1', ownerId, revision, profile: null, routine: null, experiences: [], historyRevision: null, historyTruncated: false, legacy: { source: 'legacy_free_context', profile: null, products: [], experiences: [], truncated: false } });
let finishLoad: ((v: PersonalContextSnapshot) => void) | undefined;
const requests: PersonalContextRequest[] = [];
let fail = true;
let loads = 0;
const gateway = { load: async () => { loads++; return snapshot('A', loads - 1); }, write: async (_owner: string, request: any) => { requests.push(request); if (fail) throw new Error('network'); return { replayed: false, revision: { ownerId: 'A' } } as any; }, evaluate: async () => ({ kind: 'unavailable' as const, reason: 'runtime_unavailable' }) };
let counter = 0;
const controller = new CustomerController(gateway, () => `request-${++counter}`);
controller.setOwner('A'); await controller.load();
assert.equal(controller.getState().context?.ownerId, 'A');
const write = { operation: 'save_routine' as const, routine: { completeness: 'partial' as const, items: [] } };
assert.equal(await controller.save(write), false);
fail = false;
assert.equal(await controller.save(write), true);
assert.equal((requests[0] as any).requestId, (requests[1] as any).requestId);
assert.equal(controller.getState().context?.revision, 1);
controller.setOwner('B');
assert.equal(controller.getState().context, null);
assert.equal(controller.getState().decision.kind, 'idle');
const delayed = new CustomerController({ ...gateway, load: () => new Promise(resolve => { finishLoad = resolve; }) }, () => 'id');
delayed.setOwner('A'); const pending = delayed.load(); delayed.setOwner('B'); finishLoad?.(snapshot('A')); await pending;
assert.equal(delayed.getState().context, null);
console.log('P0-B customer controller owner and retry semantics passed');
let conflictLoads = 0;
const conflicted = new CustomerController({ ...gateway, load: async () => snapshot('A', conflictLoads++), write: async () => { throw Object.assign(new Error('conflict'), { code: 'STALE_CONTEXT' }); } }, () => 'request');
conflicted.setOwner('A'); await conflicted.load(); assert.equal(await conflicted.save(write), false);
assert.equal(conflicted.getState().context?.revision, 1);
assert.ok(conflicted.getState().error?.includes('latest version'));
let evaluationCalls: Array<{ requestId: string }> = [];
const evaluating = new CustomerController({ ...gateway, load: async () => snapshot('A', loads++), evaluate: async (_owner, request) => { evaluationCalls.push(request); throw new Error('response loss'); } }, () => `eval-${++counter}`);
evaluating.setOwner('A'); await evaluating.load(); await evaluating.assess(null); assert.equal(evaluationCalls.length, 0);
const truth = { schemaVersion: 1 as const, snapshotId: 'snapshot', resolutionCaseId: 'case', caseRevision: 1, resolverVersion: 'v1', catalogReferences: { productId: null, variantId: null, formulaVersionId: null } } as any;
await evaluating.assess(truth); await evaluating.assess(truth);
assert.equal(evaluationCalls[0].requestId, evaluationCalls[1].requestId);
await evaluating.load(); await evaluating.assess(truth);
assert.notEqual(evaluationCalls[1].requestId, evaluationCalls[2].requestId);
let completeWrite: ((result: any) => void) | undefined;
const saveOwner = new CustomerController({ ...gateway, load: async () => snapshot('A'), write: () => new Promise(resolve => { completeWrite = resolve; }) }, () => 'request');
saveOwner.setOwner('A'); await saveOwner.load(); const pendingSave = saveOwner.save(write); saveOwner.setOwner('B'); completeWrite?.({ replayed: false, revision: { ownerId: 'A' } }); assert.equal(await pendingSave, false); assert.equal(saveOwner.getState().context, null);
console.log('P0-B stale conflict and assessment retry semantics passed');
