import assert from 'node:assert/strict';
import { createContextDraft, toggleSecondaryGoal, relevantQuestions, createRoutineDraft, manualRoutineItem, validateContextDraft, validateRoutineDraft } from '../src/presentation/p0b-personalization/draft.ts';
const draft = createContextDraft();
assert.equal(draft.pregnancy.state, 'unanswered');
assert.deepEqual(relevantQuestions(), []);
assert.deepEqual(relevantQuestions({ fields: ['pregnancy'], evidenceReason: 'Verified finding' }), ['pregnancy']);
assert.deepEqual(relevantQuestions({ fields: ['pregnancy'], evidenceReason: ' ' }), []);
const primary = { ...draft, primaryGoal: { state: 'answered' as const, value: 'dryness' as const } };
assert.equal(toggleSecondaryGoal(primary, 'dryness').secondaryGoals.length, 0);
const one = toggleSecondaryGoal(primary, 'texture');
const two = toggleSecondaryGoal(one, 'breakouts');
assert.equal(toggleSecondaryGoal(two, 'dark_spots').secondaryGoals.length, 2);
assert.deepEqual(toggleSecondaryGoal(two, 'texture').secondaryGoals, ['breakouts']);
assert.equal(validateContextDraft(draft), null);
assert.equal(validateContextDraft({ ...draft, secondaryGoals: ['texture', 'dark_spots', 'breakouts'] }), 'Choose up to two other goals.');
assert.equal(createRoutineDraft().completeness, 'unknown');
const item = manualRoutineItem('00000000-0000-4000-8000-000000000001', 'My cream');
assert.equal(item.reference.kind, 'manual');
if (item.reference.kind === 'manual') assert.equal(item.reference.verification, 'unverified');
assert.equal(item.timing, 'unknown');
assert.deepEqual(item.frequency, { kind: 'unknown' });
const qualitative = { ...item, frequency: { kind: 'qualitative' as const, value: 'few_times_week' as const } };
assert.equal(qualitative.frequency.kind, 'qualitative');
assert.equal(createContextDraft({ ...draft, treatments: { state: 'answered', value: [] }, sensitivities: { state: 'withheld' } }).treatments.state, 'answered');
console.log('P0-B progressive context semantics passed');
const copy = createContextDraft(primary);
copy.secondaryGoals.push('redness');
assert.deepEqual(primary.secondaryGoals, []);
const routine = createRoutineDraft({ completeness: 'partial', items: [qualitative] });
routine.items[0].reference.label = 'Edited';
assert.equal(qualitative.reference.label, 'My cream');
assert.equal(routine.completeness, 'partial');
assert.equal(validateRoutineDraft({ completeness: 'partial', items: [{ ...item, frequency: { kind: 'exact', count: 101, unit: 'week' } }] }), 'Use an exact count from 1 to 100.');
assert.equal(validateRoutineDraft({ completeness: 'partial', items: [{ ...item, reference: { kind: 'catalog', label: 'Matched product', productId: 'product', variantId: null, formulaVersionId: 'formula' } }] }), 'A formula reference needs its variant reference.');
const dated = createRoutineDraft({ completeness: 'partial', items: [{ ...item, startedOn: '2026-01-01', stoppedOn: null, duration: { count: 2, unit: 'months' } }] });
const editedRoutine = createRoutineDraft(dated);
if (editedRoutine.items[0].duration) editedRoutine.items[0].duration.count = 4;
assert.equal(dated.items[0].duration?.count, 2);
assert.equal(editedRoutine.items[0].startedOn, '2026-01-01');
assert.equal(createContextDraft({ ...draft, treatments: { state: 'unsure' } }).treatments.state, 'unsure');
