import assert from 'node:assert/strict';
import { projectTrustedSnapshot } from '../src/presentation/personal-decision/truthAdapter.ts';
import { contextBinding,evaluationFrequency } from '../src/presentation/personal-decision/contextAdapter.ts';
import { evaluateDecisionRequest,parseDecisionRequest,DecisionServiceError } from '../supabase/functions/personal-decision/handler.ts';
import type { DecisionDependencies,SavedAssessment } from '../supabase/functions/personal-decision/handler.ts';
import { fixtureSnapshot,FIXTURE_CASE,FIXTURE_SNAPSHOT,FIXTURE_PRODUCT,FIXTURE_VARIANT,FIXTURE_FORMULA } from '../supabase/functions/personal-decision/fixtures.ts';
import { localFixtureAllowed } from '../supabase/functions/personal-decision/runtime.ts';
import { describePersonalDecision } from '../src/presentation/personal-decision/result.ts';
import type { PersonalContextSnapshot } from '../src/contracts/PersonalContext.ts';
const owner='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const request=()=>parseDecisionRequest({operation:'evaluate',requestId:'99999999-9999-4999-8999-999999999999',caseId:FIXTURE_CASE,snapshotId:FIXTURE_SNAPSHOT});
const envelope=()=>({snapshot:fixtureSnapshot(),category:{state:'known' as const,value:'moisturizer',sourceIds:['category']},categorySources:[{id:'category',revision:'1'}]});
function context():PersonalContextSnapshot{return {version:'personal-context-v1',ownerId:owner,revision:2,profile:{id:'77777777-7777-4777-8777-777777777777',ownerId:owner,revision:1,recordedAt:'2026-09-26T00:00:00Z',provenance:'self_report',supersedesRevisionId:null,data:{intent:'add',primaryGoal:'dryness',secondaryGoals:[],skinBehavior:'dry_tight',reactivity:'generally_tolerates',reproductive:{pregnancy:'no',nursing:'no',tryingToConceive:'no'},sensitivities:{status:'none_known',values:[]},treatments:{status:'none',values:[]}}},routine:{id:'88888888-8888-4888-8888-888888888888',ownerId:owner,revision:2,recordedAt:'2026-09-26T00:00:00Z',provenance:'self_report',supersedesRevisionId:null,data:{completeness:'complete',items:[]}},experiences:[],historyTruncated:false,historyRevision:null,legacy:{source:'legacy_free_context',profile:null,products:[],experiences:[],truncated:false}};}
function dependencies(c=context()):DecisionDependencies {let saved:SavedAssessment|null=null;return {runtime:'local_fixture',verifyCaseOwner:async()=>true,now:()=>new Date('2026-09-26T00:00:00Z').toISOString(),readSnapshot:async()=>envelope(),readContext:async()=>c,readHistory:async(_o,revision)=>({items:[],nextCursor:null,atRevision:revision}),readRoutineFacts:async()=>[],readAssessment:async()=>saved,persist:async(_owner,_id,input,packet)=>{if(input.expectedContextRevision!==c.revision)throw new DecisionServiceError('STALE_CONTEXT',409);saved={assessmentId:'66666666-6666-4666-8666-666666666666',input,packet};return {assessmentId:saved.assessmentId,packet,replayed:false};}};}
let count=0;async function test(name:string,run:()=>void|Promise<void>){await run();count++;console.log(`PASS ${name}`);}
await test('strict request only accepts case snapshot and retry UUID references',()=>{for(const field of ['ownerId','packet','productId','ingredients','profile','expectedBinding'])assert.throws(()=>parseDecisionRequest({...request(),[field]:'attacker'}));for(const field of ['requestId','caseId'])assert.throws(()=>parseDecisionRequest({...request(),[field]:'bad'}));});
await test('request key ordering is canonical for immutable replay',()=>assert.deepEqual(parseDecisionRequest({snapshotId:FIXTURE_SNAPSHOT,caseId:FIXTURE_CASE,requestId:request().requestId,operation:'evaluate'}),request()));
await test('snapshot formula authority requires verified exact package agreement',()=>{const s=fixtureSnapshot();assert.equal(projectTrustedSnapshot({snapshot:s}).formula.state,'known');assert.equal(projectTrustedSnapshot({snapshot:s}).category.state,'unknown');s.formula!.appliesToSelectedVariant=false;assert.equal(projectTrustedSnapshot({snapshot:s}).formula.state,'unknown');});
await test('unresolved snapshot conflicts stay explicit and prevent formula promotion',()=>{const s=fixtureSnapshot();s.conflicts=[{code:'ingredient_mismatch',status:'unresolved'}];assert.equal(projectTrustedSnapshot({snapshot:s}).formula.state,'conflict');});
await test('identified product family can survive unresolved package variant',()=>{const s=fixtureSnapshot();delete s.product!.variantId;s.catalogReferences.variantId=null;s.state='identified_formula_unverified';const p=projectTrustedSnapshot({snapshot:s});assert(p.identity.state==='known');assert.equal(p.identity.value.variantId,null);assert.equal(p.formula.state,'unknown');});
await test('default missing trusted snapshot fails closed before context evaluation',async()=>{const d=dependencies();d.readSnapshot=async()=>null;await assert.rejects(()=>evaluateDecisionRequest(owner,request(),d),e=>e instanceof DecisionServiceError&&e.code==='TRUTH_SNAPSHOT_UNAVAILABLE');});
await test('full fixture core evaluates persists and renders bounded UUID packet',async()=>{const c=context(),r=await evaluateDecisionRequest(owner,request(),dependencies(c));assert.equal(r.packet.action.kind,'COULD_WORK');assert.equal(r.packet.id,request().requestId);assert.equal(r.contextRevision,2);assert.deepEqual(r.expectedBinding,contextBinding(owner,envelope(),c));assert.equal(describePersonalDecision(r.packet,r.expectedBinding).kind,'ready');});
await test('old request replays immutable packet after new context',async()=>{const c=context(),d=dependencies(c),first=await evaluateDecisionRequest(owner,request(),d);c.revision=3;c.profile!.data.sensitivities={status:'reported',values:['glycerin']};d.readSnapshot=async()=>null;const replay=await evaluateDecisionRequest(owner,request(),d);assert.equal(replay.replayed,true);assert.deepEqual(replay.packet,first.packet);assert.equal(replay.contextRevision,2);});
await test('context persistence race returns stale conflict instead of stale new assessment',async()=>{const c=context(),d=dependencies(c);d.readRoutineFacts=async()=>{c.revision++;return [];};await assert.rejects(()=>evaluateDecisionRequest(owner,request(),d),e=>e instanceof DecisionServiceError&&e.code==='STALE_CONTEXT');});
await test('owner mismatch never evaluates another users context',async()=>{const c=context();c.ownerId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';await assert.rejects(()=>evaluateDecisionRequest(owner,request(),dependencies(c)),e=>e instanceof DecisionServiceError&&e.code==='CONTEXT_OWNER_MISMATCH');});
await test('current corrected relevant history is paged independently of bounded recent history',async()=>{const c=context();c.historyRevision='cccccccc-cccc-4ccc-8ccc-cccccccccccc';c.historyTruncated=true;const d=dependencies(c);let pages=0;d.readHistory=async(_owner,revision,product,cursor)=>{assert.equal(product,FIXTURE_PRODUCT);pages++;return {atRevision:revision,nextCursor:cursor?null:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',items:cursor?[{id:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',ownerId:owner,revision:1,recordedAt:'2026-09-26T00:00:00Z',provenance:'self_report',supersedesRevisionId:'ffffffff-ffff-4fff-8fff-ffffffffffff',data:{id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',reference:{kind:'catalog',productId:FIXTURE_PRODUCT,variantId:FIXTURE_VARIANT,formulaVersionId:FIXTURE_FORMULA},kind:'reacted',occurred:{start:null,end:null},useContext:null,symptoms:['stinging'],note:null}}]:[]};};const result=await evaluateDecisionRequest(owner,request(),d);assert.equal(pages,2);assert(result.packet.findings.some(f=>f.kind==='prior_product_reaction'));assert.equal(result.packet.action.kind,'USE_WITH_CAUTION');});
await test('privacy withheld list/reproductive answers survive storage normalization',async()=>{const c=context();c.profile!.data.sensitivities.status='withheld';const r=await evaluateDecisionRequest(owner,request(),dependencies(c));assert.equal(r.packet.action.kind,'NOT_ENOUGH_INFORMATION');assert(r.packet.evidenceNeeds.some(n=>n.code==='sensitivity_context'&&n.state==='withheld'));});
await test('qualitative frequency never becomes exact count',()=>{assert.equal(evaluationFrequency({kind:'qualitative',value:'few_times_week'}),'few_times_weekly');assert.equal(evaluationFrequency({kind:'exact',count:3,unit:'week'}),'unknown');assert.equal(evaluationFrequency({kind:'qualitative',value:'most_days'}),'unknown');});
await test('fixture provider refuses remote environment and requires explicit opt in',()=>{assert.equal(localFixtureAllowed(undefined,'http://kong:8000'),false);assert.equal(localFixtureAllowed('1','https://remote.supabase.co'),false);assert.equal(localFixtureAllowed('1','http://kong:8000'),true);});

await test('opaque authoritative snapshot identifiers are not narrowed to UUID',async()=>{const r=parseDecisionRequest({...request(),snapshotId:'snapshot:immutable-review-v1'}),d=dependencies();d.readSnapshot=async()=>({...envelope(),snapshot:{...fixtureSnapshot(),snapshotId:r.snapshotId}});assert.equal((await evaluateDecisionRequest(owner,r,d)).truthRef.snapshotId,r.snapshotId);});
await test('uppercase UUID retry references normalize while snapshot casing is preserved',()=>{const id='abcdefab-cdef-4abc-8def-abcdefabcdef';const r=parseDecisionRequest({...request(),requestId:id.toUpperCase(),caseId:id.toUpperCase(),snapshotId:'Snapshot:CaseSensitive'});assert.equal(r.requestId,id);assert.equal(r.caseId,id);assert.equal(r.snapshotId,'Snapshot:CaseSensitive');});
await test('case ownership guard rejects before any provider is consulted',async()=>{const d=dependencies();d.verifyCaseOwner=async()=>false;d.readSnapshot=async()=>{throw new Error('Must not read');};await assert.rejects(()=>evaluateDecisionRequest(owner,request(),d),e=>e instanceof DecisionServiceError&&e.code==='CASE_NOT_FOUND');});

await test('maximum bounded opaque snapshot reference remains renderer compatible',async()=>{const r=parseDecisionRequest({...request(),snapshotId:'S'.repeat(200)}),d=dependencies();d.readSnapshot=async()=>({...envelope(),snapshot:{...fixtureSnapshot(),snapshotId:r.snapshotId}});const result=await evaluateDecisionRequest(owner,r,d);assert.equal(describePersonalDecision(result.packet,result.expectedBinding).kind,'ready');});
await test('persisted evaluation facts retain category authority without customer notes',async()=>{const d=dependencies();let stored:SavedAssessment['input']|null=null;const persist=d.persist;d.persist=async(owner,id,input,packet)=>{stored=input;return persist(owner,id,input,packet);};await evaluateDecisionRequest(owner,request(),d);assert(stored);const product=(stored as SavedAssessment['input']).evaluatedFacts.product as {category:{state:string;value:string}};assert.equal(product.category.value,'moisturizer');assert(!('profile' in (stored as SavedAssessment['input']).evaluatedFacts));});
await test('JSONB request key order cannot invalidate immutable replay',async()=>{const d=dependencies();await evaluateDecisionRequest(owner,request(),d);const read=d.readAssessment;d.readAssessment=async(owner,id)=>{const saved=await read(owner,id);if(saved)saved.input.request={snapshotId:saved.input.request.snapshotId,caseId:saved.input.request.caseId,operation:'evaluate',requestId:saved.input.request.requestId};return saved;};assert.equal((await evaluateDecisionRequest(owner,request(),d)).replayed,true);});
await test('101 relevant reactions paginate exactly and remain renderer-visible with missing formula',async()=>{const c=context();c.revision=103;c.historyRevision='12345678-1234-4234-8234-000000000101';const d=dependencies(c);d.readSnapshot=async()=>{const e=envelope();e.snapshot.state='identified_formula_unverified';e.snapshot.formula=null;e.snapshot.catalogReferences.formulaVersionId=null;return e;};const rows=Array.from({length:101},(_,n)=>({id:`12345678-1234-4234-8234-${String(n+1).padStart(12,'0')}`,ownerId:owner,revision:n+3,recordedAt:'2026-09-26T00:00:00Z',provenance:'self_report' as const,supersedesRevisionId:null,data:{id:`12345678-1234-4234-8234-${String(n+1).padStart(12,'0')}`,reference:{kind:'catalog' as const,productId:FIXTURE_PRODUCT,variantId:null,formulaVersionId:null},kind:'reacted' as const,occurred:{start:null,end:null},useContext:null,symptoms:[],note:null}}));let pages=0;d.readHistory=async(_owner,revision,_product,cursor)=>{pages++;const start=cursor?Number(cursor):0;return {items:rows.slice(start,start+50),nextCursor:start+50<rows.length?String(start+50):null,atRevision:revision};};const r=await evaluateDecisionRequest(owner,request(),d);assert.equal(pages,3);assert.equal(r.packet.action.kind,'USE_WITH_CAUTION');assert.equal(r.packet.findings.filter(f=>f.kind==='prior_product_reaction').length,1);assert.equal(describePersonalDecision(r.packet,r.expectedBinding).kind,'ready');assert.equal(rows.length,101);});

console.log(`${count} P0-B service composition cases passed`);
