import assert from 'node:assert/strict';
import { createClient } from '@supabase/supabase-js';
import { createOwnerPinnedLegacyGateway } from '../src/presentation/personal-decision/legacyCustomerGateway.ts';
import { captureCustomerFunctionClient } from '../src/presentation/personal-decision/customerController.ts';
import { createPersonalizationDraft } from '../src/presentation/personalization/draft.ts';
import type { FreeSkinProfile, FreeSkinProfileInput, PersonalFitResult } from '../src/contracts/FreePersonalFit.ts';
import type { CustomerFunctionClient } from '../src/presentation/personal-decision/customerController.ts';
let owner: string | null = 'A', rotate = false;
const principals: string[] = [];
let holdHttp = false, releaseHttp: ((value: Response) => void) | undefined, reachedHttp: (() => void) | undefined;
const sdk = createClient('http://127.0.0.1:54321', 'synthetic-public-key', { accessToken: async () => { await Promise.resolve(); if (rotate) owner = 'B'; return 'synthetic-token-b'; }, global: { fetch: async (_url, options) => { const value = new Headers(options?.headers).get('Authorization'); principals.push(value === 'Bearer synthetic-token-a' ? 'A' : value === 'Bearer synthetic-token-b' ? 'B' : 'unknown'); if (holdHttp) return new Promise<Response>(resolve => { releaseHttp = resolve; reachedHttp?.(); }); return new Response('{}', { headers: { 'Content-Type': 'application/json' } }); } } });
const source = { functions: sdk.functions, auth: { getSession: async () => ({ data: { session: owner ? { access_token: 'synthetic-token-a', user: { id: 'A' } } : null } }) } };
const profile: FreeSkinProfile = { goals: ['dryness'], skinBehavior: 'comfortable', reactivity: 'generally_tolerates', pregnancyStatus: 'unanswered', sensitivitiesStatus: 'none_known', knownSensitivities: [], treatmentStatus: 'none', currentTreatments: [], updatedAt: '2026-09-26T00:00:00Z' };
const fit: PersonalFitResult = { productId: 'product', variantId: 'variant', formulaVersionId: 'formula', label: 'COULD_WORK', reason: 'goal_role_match', explanation: 'Synthetic bounded result', evidenceUsed: [], missingEvidence: [], sources: [] };
const api = { getFreeSkinProfile: async (client: CustomerFunctionClient) => { await client.functions.invoke('free-personal-fit', { body: { operation: 'get_profile' } }); return profile; }, saveFreeSkinProfile: async (input: FreeSkinProfileInput, client: CustomerFunctionClient) => { await client.functions.invoke('free-personal-fit', { body: { operation: 'save_profile', profile: input } }); return { ...input, updatedAt: profile.updatedAt }; }, getPersonalFit: async (_product: string, _variant: string | undefined, client: CustomerFunctionClient) => { await client.functions.invoke('free-personal-fit', { body: { operation: 'fit', productId: _product } }); return fit; } };
const gateway = createOwnerPinnedLegacyGateway(api, expected => captureCustomerFunctionClient(expected, source, () => owner, () => {}), () => owner);
const draft = createPersonalizationDraft(); draft.goals = ['dryness_barrier'];
assert.equal((await gateway.loadProfile('A')).kind, 'ready');
assert.equal((await gateway.saveProfile('A', draft)).kind, 'ready');
assert.equal(gateway.lastSaveStatus('A')?.kind, 'ready');
assert.equal((await gateway.getFit('A', 'product', 'variant')).kind, 'supported');
assert.ok(principals.every(principal => principal === 'A'));
principals.length = 0; rotate = true; owner = 'A'; assert.equal((await gateway.saveProfile('A', draft)).kind, 'unavailable'); assert.deepEqual(principals, ['A']);
principals.length = 0; owner = 'A'; assert.equal((await gateway.getFit('A', 'product', 'variant')).kind, 'unavailable'); assert.deepEqual(principals, ['A']);
principals.length = 0; owner = null; assert.equal((await gateway.saveProfile('A', draft)).kind, 'unavailable'); assert.equal((await gateway.getFit('A', 'product')).kind, 'unavailable'); assert.deepEqual(principals, []);
assert.equal(gateway.lastSaveStatus('A'), null);
console.log('Legacy actual-SDK profile/fit requests stay with captured owner or abort; normal behavior preserved');
const { CustomerController, bindCustomerOwnerLifecycle } = await import('../src/presentation/personal-decision/customerController.ts');
const listeners = new Set<() => void>();
const controller = new CustomerController({ load: async () => { throw new Error('Unused'); }, write: async () => { throw new Error('Unused'); }, evaluate: async () => ({ kind: 'unavailable', reason: 'Unused' }) }, () => 'id');
owner = 'A'; rotate = false;
const stop = bindCustomerOwnerLifecycle(controller, () => owner, listener => { listeners.add(listener); return () => { listeners.delete(listener); }; }, () => () => {}, () => gateway.clear());
assert.equal((await gateway.saveProfile('A', draft)).kind, 'ready');
owner = 'B'; listeners.forEach(listener => listener()); owner = 'A'; listeners.forEach(listener => listener());
assert.equal(gateway.lastSaveStatus('A'), null);
stop();

owner = 'A'; rotate = false;
const stopLate = bindCustomerOwnerLifecycle(controller, () => owner, listener => { listeners.add(listener); return () => { listeners.delete(listener); }; }, () => () => {}, () => gateway.clear());
const httpReached = new Promise<void>(resolve => { reachedHttp = resolve; }); holdHttp = true;
const lateSave = gateway.saveProfile('A', draft); await httpReached;
owner = 'B'; listeners.forEach(listener => listener()); owner = 'A'; listeners.forEach(listener => listener());
releaseHttp?.(new Response('{}', { headers: { 'Content-Type': 'application/json' } }));
assert.equal((await lateSave).kind, 'unavailable'); assert.equal(gateway.lastSaveStatus('A'), null);
holdHttp = false; stopLate();
console.log('Root owner purge clears legacy status without screens and rejects late A-B-A completions');
