import assert from 'node:assert/strict';
import { createExperienceDraft, validateExperienceDraft, prepareExperienceEdit } from '../src/presentation/p0b-personalization/experience.ts';
const id = '00000000-0000-4000-8000-000000000001';
const revision = '00000000-0000-4000-8000-000000000002';
const draft = createExperienceDraft(id);
assert.equal(draft.kind, null);
assert.deepEqual(draft.occurred, { start: null, end: null });
assert.equal(draft.useContext, null);
assert.equal(draft.reference.kind, 'manual');
assert.ok(validateExperienceDraft(draft));
const report = { ...draft, reference: { kind: 'manual' as const, label: 'My cream', verification: 'unverified' as const }, kind: 'no_reaction_reported' as const };
assert.equal(validateExperienceDraft(report), null);
assert.equal(prepareExperienceEdit(report, revision).draft.kind, 'no_reaction_reported');
const edit = prepareExperienceEdit(report, revision);
assert.equal(edit.draft.id, id);
assert.equal(edit.supersedesRevisionId, revision);
edit.draft.symptoms.push('Redness');
assert.deepEqual(report.symptoms, []);
assert.ok(validateExperienceDraft({ ...report, occurred: { start: '2026-02-30', end: null } }));
assert.ok(validateExperienceDraft({ ...report, occurred: { start: '2026-04-03', end: '2026-04-01' } }));
assert.ok(validateExperienceDraft({ ...report, note: 'a'.repeat(501) }));
assert.ok(validateExperienceDraft({ ...report, symptoms: Array.from({ length: 11 }, (_, i) => String(i)) }));
console.log('P0-B experience draft semantics passed');
const catalog = { ...report, reference: { kind: 'catalog' as const, label: 'Known product', productId: id, variantId: revision, formulaVersionId: null }, useContext: { timing: 'pm' as const, frequency: { kind: 'qualitative' as const, value: 'few_times_week' as const }, startedOn: '2026-01-01', stoppedOn: null, duration: { count: 2, unit: 'months' as const } } };
const corrected = prepareExperienceEdit(catalog, revision);
assert.equal(corrected.draft.reference.kind, 'catalog');
assert.equal(corrected.draft.reference.kind === 'catalog' && corrected.draft.reference.formulaVersionId, null);
assert.deepEqual(corrected.draft.useContext, catalog.useContext);
assert.ok(validateExperienceDraft({ ...catalog, useContext: { ...catalog.useContext, duration: { count: 1001, unit: 'days' } } }));
