import assert from 'node:assert/strict';
import test from 'node:test';
import fc from 'fast-check';
import { evaluatePersonalResult } from '../src/domain/part-three/evaluate.ts';
import { purposeFacts } from '../src/domain/part-three/projection.ts';
import { PersonalResultV2Schema } from '../src/contracts/PersonalResultV2.ts';
import { normalize,LOCAL_DICTIONARY_RELEASE } from '../src/domain/part-two/index.ts';
import { boundDeclaration,sourceReading,boundLabelDeclaration,p2metadata,p2id } from './fixtures/part-two-core.ts';
import { p3input,p3revision,p3routine,p3assessment } from './fixtures/part-three.ts';
const evaluate=(x:ReturnType<typeof p3input>)=>{x.binding.encounterInputs={candidateRoutineItemId:x.candidateRoutineItemId,selectedManualReportIds:x.selectedManualReportIds,use:x.requestedUse};return evaluatePersonalResult(x);};
const judge=(x:ReturnType<typeof p3input>)=>evaluate(x).summary?.judgment;
test('J01/J02/J03/J05/J12 positivity needs purpose + actual need; ingredient role and irrelevant withheld data do not alter it',()=>{const x=p3input();assert.equal(judge(x),'worth_considering');x.context.profile!.data.primaryGoal={state:'known',value:'dark_spots'};assert.equal(judge(x),'not_enough_info');x.context.profile!.data.primaryGoal={state:'known',value:'dryness'};x.partTwo=normalize(boundDeclaration('Glycerin','public'),LOCAL_DICTIONARY_RELEASE,p2metadata);assert.equal(judge(x),'not_enough_info');assert.equal(purposeFacts(x.partTwo,x.binding,Date.parse(x.now)).length,0);});
test('J08/J09 exact decisive avoidance differs from sensitivity and partial unconditional match survives',()=>{const x=p3input();x.context.preferences=[p3revision('pref',{id:'avoid',revision:1,kind:'avoid_ingredient',target:{kind:'ingredient',identity:{kind:'resolved',ingredientId:'glycerin'}},strength:'decisive',status:'confirmed',confirmedAt:x.now,source:{kind:'structured'}})];x.binding.preferenceRevisions=['pref'];assert.equal(judge(x),'skip');const r=evaluate(x);assert(r.findings[0].factRefs.length);assert(r.findings[0].dependencies.occurrenceIds.length);x.context.preferences=[];x.binding.preferenceRevisions=[];x.context.profile!.data.sensitivities={status:'reported',values:['Glycerin']};assert.equal(judge(x),'check_first');});
test('J04 unresolved avoidance blocks a positive with a specific gap',()=>{const x=p3input();x.context.preferences=[p3revision('pref',{id:'avoid',revision:1,kind:'avoid_ingredient',target:{kind:'ingredient',identity:{kind:'unresolved',originalTerm:'Unknown term'}},strength:'decisive',status:'confirmed',confirmedAt:x.now,source:{kind:'structured'}})];x.binding.preferenceRevisions=['pref'];assert.equal(judge(x),'check_first');assert(evaluate(x).materialGaps.some(g=>g.reason==='avoidance_unresolved'));});
test('J10 source-only and conditional matches never become a product-level skip',()=>{const x=p3input();x.partTwo=normalize(sourceReading('Glycerin'),LOCAL_DICTIONARY_RELEASE,p2metadata);x.binding.subject={kind:'source_reading',captureSessionId:p2id(5),observationId:p2id(7)};x.binding.captureSessionId=p2id(5);x.context.profile!.data.sensitivities={status:'reported',values:['Glycerin']};assert.equal(judge(x),'not_enough_info');assert(evaluate(x).findings.every(f=>f.consequence!=='concern'));});
test('C01/C02/J07 relevant manual recall is explicitly selected and liked never becomes helps',()=>{const x=p3input();x.context.experiences=[p3revision('exp',{id:'report',reference:{kind:'manual',name:'Synthetic'},kind:'reacted',occurred:{start:{state:'known',value:{value:'2020',precision:'year'}},end:{state:'unanswered'}},useContext:null,symptoms:[],note:null})];x.history.activeRevisionIds=['exp'];assert.equal(judge(x),'worth_considering');x.selectedManualReportIds=['report'];assert.equal(judge(x),'check_first');assert.equal(evaluate(x).findings.find(f=>f.kind==='experience')?.arguments.relation,'selected_manual');x.context.experiences[0].data.kind='liked';assert.equal(evaluate(x).findings.some(f=>f.kind==='current_help'),false);x.history.activeRevisionIds=[];assert.equal(evaluate(x).findings.some(f=>f.kind==='experience'),false);});
test('C04/C05/C06/C07 same category cannot replace purpose/site; selected helpful comparison changes with add/replace',()=>{const x=p3input(),item=p3routine();x.context.routine=p3revision('routine',{completeness:'partial',items:[item]});x.binding.routineRevision='routine';x.binding.comparatorId=item.id;x.context.assessments=[p3revision('assessment-rev',p3assessment(item))];x.binding.assessmentRevisions=['assessment-rev'];x.context.profile!.data.primaryGoal={state:'known',value:'simplify'};assert.equal(judge(x),'skip');x.binding.intent='replace';assert.equal(judge(x),'worth_considering');x.context.assessments[0].data.perceivedHelp='not_helping';assert.equal(judge(x),'worth_considering');x.context.routine.data.items[0].applicationSite!.answer={state:'known',value:'hands'};assert.equal(judge(x),'not_enough_info');});
test('Q01/Q02/Q03 one material question latches at exposure; skip/answer prevent replacement',()=>{const x=p3input(),item=p3routine();x.context.routine=p3revision('routine',{completeness:'partial',items:[item]});x.binding.routineRevision='routine';x.binding.comparatorId=item.id;x.context.assessments=[p3revision('a',p3assessment(item))];x.binding.assessmentRevisions=['a'];x.binding.intent='unanswered';assert.equal(evaluate(x).question?.id,'question:replace-or-add');x.questionSuppression.exposedQuestionId='question:replace-or-add';assert.equal(evaluate(x).question,null);x.questionSuppression.exposedQuestionId=null;x.questionSuppression.skip=true;assert.equal(evaluate(x).question,null);});
test('L01/L02 incomplete pinned history never earns positive; independent concerns survive',()=>{const x=p3input();x.history.completeness='incomplete';x.history.reason='cap';assert.equal(judge(x),'not_enough_info');x.context.profile!.data.sensitivities={status:'reported',values:['Glycerin']};assert.equal(judge(x),'check_first');assert(evaluate(x).materialGaps.some(g=>g.reason==='relevant_history'));});
test('L04 authority/binding and extra fields fail closed',()=>{const x=p3input();x.context.ownerId='foreign';assert.throws(()=>evaluate(x));const result=evaluatePersonalResult(p3input());assert.equal(PersonalResultV2Schema.safeParse({...result,clinicalVerdict:'safe'}).success,false);assert.equal(PersonalResultV2Schema.safeParse({...result,summary:{...result.summary!,affirmativePremiseIds:[]}}).success,false);});
test('generated reported sensitivity fields never derive clinical/causal prose or a skip',()=>{fc.assert(fc.property(fc.constantFrom('Glycerin','Water','Retinol','Unknown'),term=>{const x=p3input();x.context.profile!.data.sensitivities={status:'reported',values:[term]};const r=evaluate(x);assert.notEqual(r.summary?.judgment,'skip');assert(!JSON.stringify(r).includes('culprit'));}),{seed:3102026,numRuns:100});});
test('J06 explicit current manual confirmation earns report-qualified keep; mixed/liked never do',()=>{const x=p3input(),item=p3routine();x.context.profile!.data.primaryGoal={state:'known',value:'maintain'};x.context.routine=p3revision('routine',{completeness:'partial',items:[item]});x.binding.routineRevision='routine';x.binding.intent='check_current';x.candidateRoutineItemId=item.id;x.context.assessments=[p3revision('a',p3assessment(item))];x.binding.assessmentRevisions=['a'];let r=evaluate(x);assert.equal(r.summary?.displayVariant,'worth_keeping');assert.equal(r.findings.find(f=>f.kind==='current_help')?.arguments.relation,'selected_manual');assert.deepEqual(r.findings.find(f=>f.kind==='current_help')?.factRefs,[]);x.context.assessments[0].data.perceivedHelp='mixed';assert.equal(judge(x),'not_enough_info');x.context.assessments[0].data.perceivedHelp='helps';x.context.profile!.data.sensitivities={status:'reported',values:['Glycerin']};assert.equal(judge(x),'check_first');});
test('L05 expired source cannot publish judgment or residual personalized finding bodies',()=>{const x=p3input();x.now=new Date(Date.parse(x.partTwo.expiresAt)+1).toISOString();const r=evaluate(x);assert.equal(r.state,'expired');assert.equal(r.summary,null);assert.deepEqual(r.findings,[]);assert.equal(r.question,null);});
test('L14 unselected product reaction never becomes shared-ingredient alarm or tolerance prediction',()=>{const x=p3input();x.context.experiences=[p3revision('e',{id:'other-report',reference:{kind:'manual',name:'Other product'},kind:'reacted',occurred:{start:{state:'unanswered'},end:{state:'unanswered'}},useContext:null,symptoms:[],note:null})];x.history.activeRevisionIds=['e'];const r=evaluate(x);assert.equal(r.summary?.judgment,'worth_considering');assert.equal(r.findings.some(f=>f.kind==='experience'),false);});
test('L03 omitted context and changed release binding fails before output',()=>{const x=p3input();x.binding.profileRevision=null;assert.throws(()=>evaluate(x));x.binding.profileRevision='profile';x.binding.releases.releaseHash='unapproved';assert.throws(()=>evaluate(x));});
test('J04 unknown resolved ingredient IDs remain an unresolved decisive constraint',()=>{const x=p3input();x.context.preferences=[p3revision('pref',{id:'avoid',revision:1,kind:'avoid_ingredient',target:{kind:'ingredient',identity:{kind:'resolved',ingredientId:'unreviewed-id'}},strength:'decisive',status:'confirmed',confirmedAt:x.now,source:{kind:'structured'}})];x.binding.preferenceRevisions=['pref'];const r=evaluate(x);assert.equal(r.summary?.judgment,'check_first');assert(r.materialGaps.some(g=>g.reason==='avoidance_unresolved'&&g.state==='unavailable'));assert.equal(r.findings.some(f=>f.kind==='avoidance'),false);assert(r.findings.find(f=>f.kind==='evidence_limit')?.dependencies.contextRevisionIds.includes('pref'));});
test('J06/C04 keep depends on exact requested site, use form and matching helpfulness purpose',()=>{const x=p3input(),item=p3routine();x.context.profile!.data.primaryGoal={state:'known',value:'maintain'};x.context.routine=p3revision('routine',{completeness:'partial',items:[item]});x.binding.routineRevision='routine';x.binding.intent='check_current';x.candidateRoutineItemId=item.id;const a=p3assessment(item);x.context.assessments=[p3revision('a',a)];x.binding.assessmentRevisions=['a'];assert.equal(evaluate(x).summary?.displayVariant,'worth_keeping');assert(evaluate(x).findings.find(f=>f.kind==='current_help')?.dependencies.contextRevisionIds.includes('profile'));x.requestedUse.site='hands';assert.notEqual(judge(x),'worth_considering');x.requestedUse.site='face';a.useContext={...a.useContext,useForm:{answer:{state:'known',value:'rinse_off'},provenance:'self_report'}};assert.notEqual(judge(x),'worth_considering');a.useContext=p3assessment(item).useContext;a.goalOrPurpose={state:'known',value:'cleansing'};assert.notEqual(judge(x),'worth_considering');});
test('J08 explicit selected manual current product honors decisive product avoidance without name inference',()=>{const x=p3input(),item=p3routine();x.context.profile!.data.primaryGoal={state:'known',value:'maintain'};x.context.routine=p3revision('routine',{completeness:'partial',items:[item]});x.binding.routineRevision='routine';x.binding.intent='check_current';x.candidateRoutineItemId=item.id;x.context.assessments=[p3revision('a',p3assessment(item))];x.binding.assessmentRevisions=['a'];x.context.preferences=[p3revision('pref',{id:'avoid',revision:1,kind:'avoid_product',target:{kind:'product',reference:item.reference},strength:'decisive',status:'confirmed',confirmedAt:x.now,source:{kind:'structured'}})];x.binding.preferenceRevisions=['pref'];assert.equal(judge(x),'skip');x.candidateRoutineItemId=null;assert.equal(evaluate(x).findings.some(f=>f.kind==='avoidance'),false);});
test('C01/C02/L14 report date, version and use-period qualifiers remain literal; comparator reaction does not transfer',()=>{const x=p3input(),item=p3routine();x.context.routine=p3revision('routine',{completeness:'partial',items:[item]});x.binding.routineRevision='routine';x.binding.comparatorId=item.id;x.context.assessments=[p3revision('a',p3assessment(item))];x.binding.assessmentRevisions=['a'];x.binding.intent='replace';x.context.experiences=[p3revision('old-report',{id:'report',reference:item.reference,kind:'reacted',occurred:{start:{state:'known',value:{value:'2020',precision:'year'}},end:{state:'withheld'}},useContext:p3assessment(item).useContext,symptoms:[],note:null})];x.history.activeRevisionIds=['old-report'];const r=evaluate(x),f=r.findings.find(f=>f.kind==='experience')!;assert.equal(r.summary?.judgment,'worth_considering');assert.equal(f.consequence,'information');assert.equal(f.arguments.reportTrace?.role,'comparator');assert.deepEqual(f.arguments.reportTrace?.period,x.context.experiences[0].data.occurred);assert.deepEqual(f.arguments.reportTrace?.useContext?.frequency,item.frequency);assert(f.dependencies.contextRevisionIds.includes('old-report'));assert(f.dependencies.contextRevisionIds.includes('routine'));});
test('J06 explicit current catalog confirmation supports family-qualified report help without inventing formula identity',()=>{const x=p3input(),item=p3routine();item.reference={kind:'catalog',productId:p2id(200),variantId:p2id(201),formulaVersionId:p2id(202)};x.context.profile!.data.primaryGoal={state:'known',value:'maintain'};x.context.routine=p3revision('routine',{completeness:'partial',items:[item]});x.binding.routineRevision='routine';x.binding.intent='check_current';x.candidateRoutineItemId=item.id;x.context.assessments=[p3revision('a',p3assessment(item))];x.binding.assessmentRevisions=['a'];const r=evaluate(x);assert.equal(r.summary?.displayVariant,'worth_keeping');assert.equal(r.findings.find(f=>f.kind==='current_help')?.arguments.relation,'product_family');assert.equal(r.binding.subject.kind==='declaration'&&r.binding.subject.formulaVersionId,null);});

test('C04 an explicit cleansing Check cannot earn a moisturizer need or same-step comparison',()=>{
 for(const intent of ['add','replace','unanswered'] as const){const x=p3input(),item=p3routine();x.context.routine=p3revision('routine',{completeness:'partial',items:[item]});x.binding.routineRevision='routine';x.binding.comparatorId=item.id;x.context.assessments=[p3revision('a',p3assessment(item))];x.binding.assessmentRevisions=['a'];x.binding.intent=intent;x.requestedUse.purpose='cleansing';const r=evaluate(x);assert.equal(r.summary?.judgment,'not_enough_info');assert(!r.findings.some(f=>f.kind==='purpose_value'||f.ruleId==='pair-replacement'||f.ruleId==='already-helpful'));assert.equal(r.question,null,'Intent cannot repair an explicit incompatible purpose');}
});
test('a bounded historical result retains a later mandatory concern over earlier optional information',()=>{
 const x=p3input(),item=p3routine();x.context.routine=p3revision('routine',{completeness:'partial',items:[item]});x.binding.routineRevision='routine';x.candidateRoutineItemId=item.id;x.binding.intent='check_current';
 x.context.experiences=Array.from({length:101},(_,i)=>p3revision('e'+i,{id:'r'+i,reference:item.reference,kind:i===100?'reacted':'liked',occurred:{start:{state:'unanswered'},end:{state:'unanswered'}},useContext:null,symptoms:[],note:null}));x.history.activeRevisionIds=x.context.experiences.map(e=>e.id);const r=evaluate(x);assert.equal(r.findings.length,100);assert.equal(new Set(r.findings.map(f=>f.id)).size,100);assert.equal(r.summary?.judgment,'check_first');assert(r.findings.some(f=>f.consequence==='concern'&&f.arguments.reportTrace?.recordId==='r100'));assert(r.materialGaps.some(g=>g.reason==='relevant_history'));assert(PersonalResultV2Schema.safeParse(r).success);
});
