import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFileSync } from 'node:fs';
import { verifyPrivateJpeg, PrivateImageError, PART_ONE_MAX_UPLOAD_BYTES } from '../supabase/functions/_shared/part-one-jpeg.ts';
import { uploadPrivateDerivative, consumePrivateCleanupOnce, recoverPrivateCapture, type PrivateUploadPorts } from '../supabase/functions/_shared/part-one-private-storage.ts';
import { createPrivateStoragePorts, type PrivateStorageClient } from '../supabase/functions/_shared/part-one-private-supabase.ts';
const bytes=new Uint8Array(readFileSync(new URL('./fixtures/part-one-private/derivative.jpg',import.meta.url)));
const id='ea000000-0000-4000-8000-000000000001';
const binding={captureSessionId:id,packageObservationId:id,idempotencyKey:'fixture',evidenceId:id,expectedGeneration:0,expectedResultRevision:1,expectedCaptureRevision:0,expectedDeletionEpoch:0};
const calls:string[]=[];
function ports():PrivateUploadPorts{return {ownerId:id,async operation(a){calls.push(a);return a.endsWith('authorize')?{allowed:true}:{ticketId:id,bucketId:'synthetic-private',objectName:'opaque.jpg'};},async service(a){calls.push(a);return a==='upload/dispatch'?{allowed:true}:a==='upload/attest'?{verified:true}:{queued:true};},storage:{async upload(){calls.push('bytes');},async inspect(){return null;},async remove(){},async sign(){return 'http://localhost/signed';}}};}
const req=(body:Uint8Array,signal?:AbortSignal)=>new Request('http://localhost/private',{method:'POST',headers:{'content-type':'image/jpeg'},body:new Uint8Array(body).buffer,signal});
test('actual bounded JPEG decoder validates the sanitized derivative',()=>assert.deepEqual(verifyPrivateJpeg(bytes),{width:160,height:64}));
test('metadata marker is rejected before pixels or storage',()=>{const meta=Uint8Array.from([0xff,0xe1,0,8,69,120,105,102,0,0]);const dirty=new Uint8Array(bytes.length+meta.length);dirty.set(bytes.slice(0,2));dirty.set(meta,2);dirty.set(bytes.slice(2),2+meta.length);assert.throws(()=>verifyPrivateJpeg(dirty),PrivateImageError);});
test('truncated stream and trailing bytes cannot masquerade as sanitized JPEG',()=>{assert.throws(()=>verifyPrivateJpeg(bytes.slice(0,-8)),PrivateImageError);const trailer=new Uint8Array(bytes.length+1);trailer.set(bytes);assert.throws(()=>verifyPrivateJpeg(trailer),PrivateImageError);});
test('compressed oversize is an explicit error',()=>assert.throws(()=>verifyPrivateJpeg(new Uint8Array(PART_ONE_MAX_UPLOAD_BYTES+1)),PrivateImageError));
test('decoded image dimensions are bounded before allocation',()=>{const oversized=new Uint8Array(bytes);const frame=oversized.findIndex((v,i)=>v===0xff&&oversized[i+1]===0xc0);assert.ok(frame>0);oversized[frame+5]=0x10;oversized[frame+6]=1;assert.throws(()=>verifyPrivateJpeg(oversized),/image_dimensions_exceeded/);});
test('actual streamed upload byte cap is enforced without content-length',async()=>{calls.length=0;await assert.rejects(uploadPrivateDerivative(req(new Uint8Array(PART_ONE_MAX_UPLOAD_BYTES+1)),binding,ports()),/payload_too_large/);assert.deepEqual(calls,['captures/upload-authorize']);});

test('denied policy reads zero bytes and reserves no ticket',async()=>{let pulls=0;const p=ports();p.operation=async()=>{throw new Error('disabled');};const stream=new ReadableStream<Uint8Array>({pull(){pulls++;}},{highWaterMark:0});await assert.rejects(uploadPrivateDerivative(new Request('http://localhost/private',{method:'POST',headers:{'content-type':'image/jpeg'},body:stream,duplex:'half'} as RequestInit),binding,p),/disabled/);assert.equal(pulls,0);});
test('invalid image cannot reserve quota, dispatch or upload',async()=>{calls.length=0;await assert.rejects(uploadPrivateDerivative(req(Uint8Array.from([1,2,3])),binding,ports()));assert.deepEqual(calls,['captures/upload-authorize']);});
test('pre-canceled request cannot reserve or dispatch',async()=>{const abort=new AbortController();abort.abort();calls.length=0;await assert.rejects(uploadPrivateDerivative(req(bytes,abort.signal),binding,ports()),/upload_cancelled/);assert.deepEqual(calls,['captures/upload-authorize']);});
test('stalled body cancellation hook never holds rejection',async()=>{const abort=new AbortController();const stream=new ReadableStream<Uint8Array>({pull(){return new Promise(()=>{});},cancel(){return new Promise(()=>{});}},{highWaterMark:0});const pending=uploadPrivateDerivative(new Request('http://localhost/private',{method:'POST',headers:{'content-type':'image/jpeg'},body:stream,signal:abort.signal,duplex:'half'} as RequestInit),binding,ports());setTimeout(()=>abort.abort(),10);await assert.rejects(pending,/upload_cancelled/);});
test('verified stream reserves, dispatches and attests in order',async()=>{calls.length=0;const result=await uploadPrivateDerivative(req(bytes),binding,ports());assert.deepEqual(result,{verified:true});assert.deepEqual(calls,['captures/upload-authorize','captures/upload-reserve','upload/dispatch','bytes','upload/attest']);});
test('storage success followed by deletion rejection queues durable cleanup',async()=>{calls.length=0;const p=ports();p.service=async(a)=>{calls.push(a);return a==='upload/dispatch'?{allowed:true}:a==='upload/attest'?{conflict:true,code:'stale_capture'}:{queued:true};};await assert.rejects(uploadPrivateDerivative(req(bytes),binding,p),/stale_capture/);assert.equal(calls.at(-1),'upload/abort');});
test('SDK receives binary ArrayBuffer, never Uint8Array JSON serialization',async()=>{let body:unknown;const client={rpc:async()=>({data:null,error:null}),storage:{from:()=>({upload:async(_name:string,input:ArrayBuffer)=>{body=input;return{data:{},error:null};},remove:async()=>({data:{},error:null}),createSignedUrl:async()=>({data:null,error:null})})}} satisfies PrivateStorageClient;await createPrivateStoragePorts(client).upload('private','opaque',bytes,{contentType:'image/jpeg',upsert:false,signal:new AbortController().signal});assert.ok(body instanceof ArrayBuffer);assert.deepEqual(new Uint8Array(body),bytes);});
test('Explicit public API origin preserves signed private object path and token across local Docker gateway',async()=>{
 const signed='http://kong:8000/storage/v1/object/sign/private/opaque%20name.jpg?token=synthetic-token';
 const client={rpc:async()=>({data:{allowed:true,maxSeconds:60},error:null}),storage:{from:()=>({upload:async()=>({data:null,error:null}),remove:async()=>({data:null,error:null}),createSignedUrl:async()=>({data:{signedUrl:signed},error:null})})}} satisfies PrivateStorageClient;
 assert.equal(await createPrivateStoragePorts(client).sign('private','opaque',60),signed);
 assert.equal(await createPrivateStoragePorts(client,{publicApiOrigin:'http://127.0.0.1:57421'}).sign('private','opaque',60),'http://127.0.0.1:57421/storage/v1/object/sign/private/opaque%20name.jpg?token=synthetic-token');
 for(const origin of ['http://evil.example','https://user:password@example.test','https://example.test/path','https://example.test?query=1','not a URL'])assert.throws(()=>createPrivateStoragePorts(client,{publicApiOrigin:origin}),/invalid_private_public_origin/);
 const bad={...client,storage:{from:()=>({...client.storage.from(),createSignedUrl:async()=>({data:{signedUrl:'http://kong:8000/unrelated?token=synthetic-token'},error:null})})}};
 await assert.rejects(createPrivateStoragePorts(bad,{publicApiOrigin:'http://127.0.0.1:57421'}).sign('private','opaque',60),/invalid_private_asset_url/);
});
test('cleanup deletes exact version and only acknowledges fresh actual absence',async()=>{const order:string[]=[];let removed=false;const result=await consumePrivateCleanupOnce({service:async(a)=>{order.push(a);return a==='cleanup/claim'?{claim:{objectId:id,objectVersion:'v1',bucketId:'private',objectName:'opaque',leaseToken:id}}:a==='cleanup/ack'?{deleted:true}:{allowed:true};},storage:{async inspect(){order.push('inspect');return removed?null:{id,version:'v1',size:bytes.length};},async remove(){order.push('remove');removed=true;}}});assert.equal(result.deleted,true);assert.deepEqual(order,['cleanup/claim','inspect','cleanup/dispatch','remove','inspect','cleanup/ack']);});
test('replacement Storage version is blocked without deleting bytes',async()=>{let removed=false,blocked=false;const result=await consumePrivateCleanupOnce({service:async(a)=>{if(a==='cleanup/blocked')blocked=true;return a==='cleanup/claim'?{claim:{objectId:id,objectVersion:'v1',bucketId:'private',objectName:'opaque',leaseToken:id}}:{allowed:true};},storage:{async inspect(){return{id,version:'v2',size:1};},async remove(){removed=true;}}});assert.equal(removed,false);assert.equal(blocked,true);assert.equal(result.blocked,true);});
test('unknown Storage deletion never claims byte erasure',async()=>{let ack=false;const result=await consumePrivateCleanupOnce({service:async(a)=>{if(a==='cleanup/ack')ack=true;return a==='cleanup/claim'?{claim:{objectId:id,objectVersion:'v1',bucketId:'private',objectName:'opaque',leaseToken:id}}:{allowed:true};},storage:{async inspect(){return{id,version:'v1',size:1};},async remove(){throw new Error('timeout');}}});assert.equal(ack,false);assert.equal(result.deleted,false);});
test('recovery final rights read rejects deletion after signed access hop',async()=>{let read=0;await assert.rejects(recoverPrivateCapture(id,{operation:async()=>++read===1?{assets:[{attestationId:id,expiresAt:new Date(Date.now()+60000).toISOString(),asset:{storageObjectId:id},storage:{bucketId:'private',objectName:'opaque',objectVersion:'v1'}}]}:{conflict:true,code:'private_removed'},storage:{async upload(){},async inspect(){return{id,version:'v1',size:1};},async remove(){},async sign(){return'http://localhost/signed';}}}),/private_removed/);});
