import assert from 'node:assert/strict';
import test from 'node:test';
import { handlePersonalRequest, type PartThreePorts } from '../supabase/functions/part-three/handler.ts';
import { p3input } from './fixtures/part-three.ts';
import { p2id } from './fixtures/part-two-core.ts';
import type { PartThreeEvaluateRequest } from '../src/contracts/PartThreeService.ts';
import { PersonalResultV2Schema, type PersonalResultV2 } from '../src/contracts/PersonalResultV2.ts';
import { assembleFoundation } from '../src/domain/part-four/assemble.ts';
function host(enabled=true){const x=p3input();x.context.profile!.id=p2id(101);const request:PartThreeEvaluateRequest={operation:'evaluate',requestId:p2id(110),encounterId:p2id(111),accountGeneration:1,generation:1,scanId:x.partTwo.scanId,captureSessionId:x.partTwo.captureSessionId,expectedPartOneGeneration:x.partTwo.generation,expectedPartOneRevision:x.partTwo.evidenceRevision,intent:'add',comparatorId:null,candidateRoutineItemId:null,selectedManualReportIds:[],use:x.requestedUse,savedAssessmentId:null};let published:any=null;const ports:PartThreePorts={partFourEnabled:enabled,ownerId:x.context.ownerId,now:()=>x.now,normalize:async()=>x.partTwo,context:async()=>x.context,history:async()=>({items:[],nextCursor:null,atRevision:x.context.revision}),worker:async(action,payload)=>{if(action==='encounter/read')return {};if(action==='prepare')return {resultId:p2id(120),resultRevision:2,leaseToken:p2id(121)};if(action==='provider/gate')return {allowed:false};if(action==='publish'){published=payload.result;return {kind:'result',result:published,replayed:false};}throw Error(action);}};return {x,request,ports,published:()=>published};}
test('canonical local handler publishes complete versioned formula and context insights with unavailable sources',async()=>{const h=host();const r=await handlePersonalRequest(h.request,h.ports);assert.equal(r.kind,'result');if(r.kind!=='result')return;const packet=r.result.partFour;assert(packet);assert.equal(packet.formula.ingredients.length,h.x.partTwo.state==='ready'?h.x.partTwo.output.reading.occurrences.length:0);assert.equal(packet.contextRevision,h.x.context.revision);assert.equal(packet.reviews.state,'unavailable');assert.equal(packet.value.state,'unavailable');assert.equal(packet.decisionState,'pending','No premature green for a goal benefit that lacks admitted evidence');assert.deepEqual(h.published().partFour,packet);assert(PersonalResultV2Schema.safeParse(r.result).success);});
test('Part4 stays opt-in and does not alter inherited P3 result when disabled',async()=>{const h=host(false);const r=await handlePersonalRequest(h.request,h.ports);assert.equal(r.kind,'result');if(r.kind==='result'){assert.equal(r.result.partFour,undefined);assert.equal(r.result.binding.releases.partFour,undefined);assert.equal(r.result.summary?.judgment,'worth_considering');}});
test('typed packet rejects changed source/context/knowledge binding and partial unversioned payload',async()=>{const h=host();const r=await handlePersonalRequest(h.request,h.ports);if(r.kind!=='result')throw Error('missing');for(const mutate of [(x:any)=>x.partFour.contextRevision++,(x:any)=>x.partFour.formula.partTwoRevision++,(x:any)=>x.partFour.formula.knowledgeHash='f'.repeat(64),(x:any)=>delete x.binding.releases.partFour]){const bad:PersonalResultV2=structuredClone(r.result);mutate(bad);assert.equal(PersonalResultV2Schema.safeParse(bad).success,false);}});
test('explicit concern is not suppressed by missing optional sources; raw note does not influence packet',async()=>{const h=host();const r=await handlePersonalRequest(h.request,h.ports);if(r.kind!=='result')throw Error('missing');const altered=structuredClone(r.result);altered.summary!.judgment='check_first';altered.summary!.affirmativePremiseIds=[];const input={context:h.x.context,partTwo:h.x.partTwo,requestedUse:h.request.use,intent:h.request.intent,candidateRoutineItemId:null,selectedComparatorId:null};const a=assembleFoundation(input,altered);h.x.context.notes=[];const b=assembleFoundation(input,altered);assert.deepEqual(a,b);assert.equal(a?.decisionState,'supported');});
