import assert from 'node:assert/strict';
import test from 'node:test';
import {handlePersonalRequest,PartThreeError} from '../supabase/functions/part-three/handler.ts';
import {p3input,p3revision,p3routine,p3assessment} from './fixtures/part-three.ts';
import {p2id,p2now} from './fixtures/part-two-core.ts';
import {createJevProvider,type JevTransport} from '../src/domain/part-three/provider.ts';
import type {PartThreeEvaluateRequest} from '../src/contracts/PartThreeService.ts';
type NativeJevRequest=Parameters<JevTransport['send']>[0];
function fixture(){const x=p3input();x.context.profile!.id=p2id(101);const item=p3routine(p2id(102));x.context.routine=p3revision(p2id(103),{completeness:'partial',items:[item]});const a=p3assessment(item);a.id=p2id(104);a.useContext={timing:item.timing,frequency:item.frequency,startedOn:item.startedOn,stoppedOn:item.stoppedOn,duration:item.duration,reportedPurpose:item.reportedPurpose,applicationSite:item.applicationSite,useForm:item.useForm};x.context.assessments=[p3revision(p2id(105),a)];const request:PartThreeEvaluateRequest={operation:'evaluate',requestId:p2id(110),encounterId:p2id(111),accountGeneration:1,generation:1,scanId:x.partTwo.scanId,captureSessionId:x.partTwo.captureSessionId,expectedPartOneGeneration:x.partTwo.generation,expectedPartOneRevision:x.partTwo.evidenceRevision,intent:'replace',comparatorId:item.id,candidateRoutineItemId:null,selectedManualReportIds:[],use:x.requestedUse,savedAssessmentId:null};return {x,request};}
function host(allow=false){const {x,request}=fixture();let interacted=false,exposed:string|null=null,calls=0;const actions:string[]=[];const ports={ownerId:x.context.ownerId,now:()=>p2now,normalize:async()=>x.partTwo,context:async()=>x.context,history:async()=>({items:[],nextCursor:null,atRevision:x.context.revision}),identity:async()=>({name:'Permitted synthetic name',expiresAt:x.partTwo.expiresAt}),worker:async(action:string,payload:any)=>{actions.push(action);if(action==='encounter/read')return {interacted,exposedQuestionId:exposed,skip:false,answered:false};if(action==='prepare')return {resultId:p2id(120),resultRevision:2,leaseToken:p2id(121)};if(action==='provider/gate')return {allowed:allow,callId:p2id(122),model:'jev-1.13.0',approvalId:'synthetic-processing-approval',grants:['exact-intent-grant']};if(action==='publish')return {kind:'result',result:payload.result,replayed:false};throw Error('Unexpected action');},provider:(model:string)=>createJevProvider({async send(native:NativeJevRequest){calls++;assert(!JSON.stringify(native).includes(x.context.ownerId));assert(!JSON.stringify(native).includes('dryness'));const answers=Object.fromEntries(Object.entries(native.questions).map(([id,q])=>{const ids=Object.keys(q.criteria),chosen=ids[ids.length-1];return [id,{type:'choice',choice:chosen,probabilities:Object.fromEntries(ids.map(option=>[option,option===chosen?1:0])),confidence:1}];}));return JSON.stringify({model,answers,usage:{input_tokens:100,output_tokens:10}});}},model,()=>Date.parse(p2now))};return {x,request,ports,actions,calls:()=>calls,interact:()=>{interacted=true;},expose:()=>{exposed='question:replace-or-add';}};}
test('L10 production runtime seam invokes real Jev adapter with injected transport behind gates; mandatory baseline remains',async()=>{const h=host(true),result=await handlePersonalRequest(h.request,h.ports);assert.equal(result.kind,'result');if(result.kind!=='result')return;assert.equal(h.calls(),1);assert.equal(result.result.refinementStatus,'accepted');assert.equal(result.result.summary?.judgment,'worth_considering');assert(result.result.findings.filter(f=>f.mandatoryVisibility).every(f=>f.consequence==='value'));assert(h.actions.includes('provider/gate'));});
test('gates off causes zero provider calls and complete deterministic fallback through identical live handler',async()=>{const h=host(false),result=await handlePersonalRequest(h.request,h.ports);assert.equal(h.calls(),0);assert.equal(result.kind,'result');if(result.kind==='result'){assert.equal(result.result.refinementStatus,'off');assert.equal(result.result.summary?.judgment,'worth_considering');assert(result.result.selectedTradeoffId);}});
test('Q02/L11 optional model choice cannot replace a question after exposure or interaction',async()=>{const h=host(true);h.request.intent='unanswered';const original=h.ports.provider;h.ports.provider=model=>{const provider=original(model);return {async evaluate(...args:Parameters<typeof provider.evaluate>){const choice=await provider.evaluate(...args);h.expose();h.interact();return {...choice,selectedQuestionId:null};}};};const result=await handlePersonalRequest(h.request,h.ports);assert.equal(result.kind,'result');if(result.kind==='result')assert.equal(result.result.question?.id,'question:replace-or-add');});
test('L03/L04 incoming authority, mismatched scan and foreign context fail before storage',async()=>{const h=host();await assert.rejects(()=>handlePersonalRequest({...h.request,ownerId:p2id(999)},h.ports),e=>e instanceof PartThreeError&&e.status===400);await assert.rejects(()=>handlePersonalRequest({...h.request,scanId:p2id(999)},h.ports));h.x.context.ownerId=p2id(999);await assert.rejects(()=>handlePersonalRequest(h.request,h.ports));assert.equal(h.actions.length,0);});
test('model invalid/timeout/unavailable preserve complete same baseline instead of downgrading evidence',async()=>{for(const outcome of ['invalid','timeout','unavailable','abstained'] as const){const h=host(true);h.ports.provider=()=>({evaluate:async()=>({selectedTradeoffId:null,selectedQuestionId:null,provider:'jev',resolvedModel:outcome==='abstained'?'jev-1.13.0':null,usage:outcome==='abstained'?{inputTokens:1,outputTokens:1}:null,elapsedMs:0,contractVersion:'part-three-selection/v1',outcome})});const result=await handlePersonalRequest(h.request,h.ports);assert.equal(result.kind,'result');if(result.kind==='result'){assert.equal(result.result.summary?.judgment,'worth_considering');assert.equal(result.result.refinementStatus,outcome);assert(result.result.selectedTradeoffId);}}});
test('LIFE02 live deferred composition publishes immediate complete baseline before optional transport finishes',async()=>{const h=host(true);let work:(()=>Promise<void>)|undefined,release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve;});const original=h.ports.worker;let published:any=null;const ports={...h.ports,defer:(next:()=>Promise<void>)=>{work=next;},worker:async(action:string,payload:any)=>{if(action==='refinement/prepare')return {resultId:p2id(120),resultRevision:3,leaseToken:p2id(123)};const value=await original(action,payload);if(action==='publish')published=value;return value;},provider:(model:string)=>{const adapter=h.ports.provider(model);return {async evaluate(...args:Parameters<typeof adapter.evaluate>){await pending;return adapter.evaluate(...args);}};}};
 const first=await handlePersonalRequest(h.request,ports);assert.equal(first.kind,'result');if(first.kind!=='result')return;assert.equal(first.result.refinementStatus,'off');assert.equal(first.result.resultRevision,2);assert.equal(first.result.summary?.judgment,'worth_considering');assert.equal(h.calls(),0);assert(work);const completion=work();await Promise.resolve();assert.equal(published.result.refinementStatus,'off');release();await completion;assert.equal(published.result.refinementStatus,'accepted');assert.equal(published.result.resultRevision,3);assert.deepEqual(published.result.summary,first.result.summary);assert.deepEqual(published.result.findings,first.result.findings);assert.equal(h.calls(),1);
});
