import assert from 'node:assert/strict';
import test from 'node:test';
import {retrieveDecisionHistory} from '../src/domain/part-three/history.ts';
import {p3revision} from './fixtures/part-three.ts';
const scope={kind:'catalog' as const,productId:'selected'};
const report=(id:string,revision:number)=>p3revision(`revision-${revision}`,{id,reference:{kind:'manual' as const,name:'Reported item'},kind:'reacted' as const,occurred:{start:{state:'unsure' as const},end:{state:'withheld' as const}},useContext:null,symptoms:[],note:null},revision);
test('L01 scoped pinned retrieval goes beyond overview and retains latest stable report correction',async()=>{const visited:Array<string|null>=[];const r=await retrieveDecisionHistory([scope],10,async(_,cursor)=>{visited.push(cursor);return cursor?{items:[report('old',3),report('outside-overview',4)],nextCursor:null,atRevision:10}:{items:[report('old',2)],nextCursor:'page2',atRevision:10};});assert.deepEqual(visited,[null,'page2']);assert.equal(r.history.completeness,'complete');assert.equal(r.records.find(x=>x.data.id==='old')?.revision,3);assert(r.records.some(x=>x.data.id==='outside-overview'));});
test('L02 repeated cursor, page failure, revision change and cap never become no history',async()=>{for(const reason of ['repeated_cursor','page_error','revision_changed','cap'] as const){let pages=0;const r=await retrieveDecisionHistory([scope],10,async()=>{pages++;if(reason==='page_error')throw Error('synthetic unavailable');return {items:reason==='cap'?Array.from({length:1001},(_,n)=>report(String(n),1)):[],nextCursor:reason==='repeated_cursor'?'same':null,atRevision:reason==='revision_changed'?11:10};});assert.equal(r.history.reason,reason);assert.notEqual(r.history.completeness,'complete');if(reason==='repeated_cursor')assert.equal(pages,2);}});
test('L02 bounded deadline rejects late historical pages and excessive requested scopes',async()=>{let clock=0;const r=await retrieveDecisionHistory([scope],10,async()=>{clock=2001;return {items:[],nextCursor:'second',atRevision:10};},()=>clock);assert.equal(r.history.reason,'deadline');const cap=await retrieveDecisionHistory([scope,scope,scope],10,async()=>({items:[],nextCursor:null,atRevision:10}));assert.equal(cap.history.reason,'cap');});
