import assert from 'node:assert/strict';
import { test } from 'node:test';
import { boundLabelDeclaration } from './fixtures/part-two-core.ts';
import { authoritativeInput, PART_TWO_RELEASE_ID, PART_TWO_VERSIONS, LOCAL_DICTIONARY_RELEASE } from '../supabase/functions/_shared/part-two-runtime.ts';
import { normalize, sha256 } from '../src/domain/part-two/index.ts';
const context=()=>{
 const input=boundLabelDeclaration();const b=input.binding,d={...input.declaration,textStructureHash:sha256(JSON.stringify(input.declaration.sections))},a=input.labelAssertions![0],ref=input.sourceRefs[0];
 const observed={id:ref.observationId,kind:'observation' as const,revision:ref.sourceRevision,policyId:ref.policyId,policyVersion:ref.policyVersion,ownerId:b.ownerId,scope:b.scope,payload:{rawText:a.sourceText,labelAssertions:[{assertionId:a.assertionId,assertionKind:a.assertionKind,text:a.text,start:a.span.start,end:a.span.end,transcription:a.transcription,conditional:a.conditional}]},dependencies:[],identityDependencies:[],observedAt:ref.observedAt,expiresAt:ref.expiresAt,status:'active' as const,statusRevision:1};
 const record={canonical_key:null,policy_id:ref.policyId,policy_version:ref.policyVersion,owner_id:b.ownerId,scope:b.scope,dependencies:[ref.observationId],identity_dependencies:[],supersedes_id:null,observed_at:d.observedAt,expires_at:d.expiresAt,created_at:d.observedAt};
 return {ownerId:b.authenticatedOwnerId,scanId:b.scanId,capture:null,generation:b.generation,evidenceRevision:b.evidenceRevision,bindingRevision:1,policyEpoch:1,withdrawnExplanationDependencies:[],deletionEpoch:0,result:{packageConfirmation:b.packageConfirmation},declaration:{...record,id:d.declarationId,kind:'declaration' as const,item_id:d.itemId,revision:d.revision,payload:{...d,structuredSections:d.sections,state:input.bundle.state,predicate:input.bundle.predicate,sources:input.bundle.sources}},snapshot:{...record,id:b.snapshotId,kind:'snapshot' as const,item_id:b.itemId,revision:b.snapshotRevision,payload:{requestedMarket:b.requestedMarket}},dependencies:[observed],observations:[observed],policies:[{id:ref.policyId,version:ref.policyVersion,retainAllowed:true,displayAllowed:true,exportAllowed:false,epoch:0,labelAssertionKinds:[a.assertionKind],labelAssertionEpoch:a.fieldPermission.policyEpoch,expiresAt:ref.expiresAt}],expiresAt:b.expiresAt,state:'pending' as const,releaseId:PART_TWO_RELEASE_ID,releaseHash:LOCAL_DICTIONARY_RELEASE.contentHash,versions:PART_TWO_VERSIONS,releaseEpoch:1,contextDigest:sha256('ctx'),dependencyDigest:b.dependencyDigest,bindingKey:b.bindingKey};
};
const request=(c:ReturnType<typeof context>)=>({schemaVersion:1 as const,requestId:'label-runtime-request',scanId:c.scanId,captureSessionId:null,expectedGeneration:c.generation,expectedEvidenceRevision:c.evidenceRevision});
test('actual authoritative mapper constructs literal assertions only from reviewed field grant + immutable annotation',()=>{
 const c=context();const input=authoritativeInput(c,request(c));assert.equal(input.kind,'bound_declaration');if(input.kind!=='bound_declaration')throw Error('bound required');assert.equal(input.labelAssertions?.length,1);assert.equal(input.sourceRefs[0].sourceTextHash,sha256(c.observations[0].payload.rawText));
 const result=normalize(input,LOCAL_DICTIONARY_RELEASE,{snapshotId:'label-snapshot',createdAt:c.observations[0].observedAt,resultRevision:2});assert.equal(result.state,'ready');if(result.state!=='ready'||result.output.kind!=='bound')throw Error('ready bound required');assert.equal(result.output.productFacts.facts.filter(f=>f.kind==='product_label_assertion').length,1);assert.equal(result.output.reading.facts.filter(f=>f.kind==='product_label_assertion').length,0);
});
test('no field grant/wrong span/foreign owner/stale observation cannot elevate stored label metadata',()=>{
 for(const variant of ['grant','span','owner','revision','permission_flag','conditional','uncertain','missing_epoch'] as const){const c=context();if(variant==='grant')c.policies[0].labelAssertionKinds=[];if(variant==='missing_epoch')delete (c.policies[0] as {labelAssertionEpoch?:number}).labelAssertionEpoch;if(variant==='span')c.observations[0].payload.labelAssertions[0].start++;if(variant==='owner')c.observations[0].ownerId='foreign';if(variant==='revision')c.observations[0].revision++;if(variant==='permission_flag'){c.policies[0].labelAssertionKinds=[];Object.assign(c.observations[0].payload,{fieldPermission:{permitted:true,assertionKind:'claim'},category:'drug'});}if(variant==='conditional')c.observations[0].payload.labelAssertions[0].conditional='if applicable';if(variant==='uncertain')c.observations[0].payload.labelAssertions[0].transcription='uncertain';
  let result;try{const input=authoritativeInput(c,request(c));result=normalize(input,LOCAL_DICTIONARY_RELEASE,{snapshotId:'denied',createdAt:c.observations[0].observedAt,resultRevision:2});}catch{continue;}if(result.state==='ready'&&result.output.kind==='bound')assert.equal(result.output.productFacts.facts.filter(f=>f.kind==='product_label_assertion').length,0,variant);
 }
});

test('qualified annotation overflow is a typed durable parse limit, never truncated complete facts',async()=>{
 const c=context();c.observations[0].payload.labelAssertions=Array.from({length:101},(_,n)=>({...c.observations[0].payload.labelAssertions[0],assertionId:`assertion-${n}`}));
 const {normalizeAuthorized}=await import('../supabase/functions/_shared/part-two-runtime.ts');const r=await normalizeAuthorized(request(c),c.ownerId,{localFixtureApproved:true,authorize:async()=>c.ownerId,now:()=>c.observations[0].observedAt,operation:async()=>({context:c,state:'pending',resultRevision:1,reasonCodes:[],cached:null,ticket:{bindingKey:c.bindingKey,leaseToken:'ticket',contextDigest:c.contextDigest,expectedResultRevision:1}}),worker:async(_action,payload)=>({published:true,result:{...(payload.result as object),resultRevision:2}})});
 assert.equal(r.state,'parse_limit');if(r.state==='parse_limit')assert.deepEqual(r.reasonCodes,['label_annotation_limit']);assert.equal(r.resultRevision,2);
});
