import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { test } from 'node:test';
import { extractPrivateCapturedSource } from '../supabase/functions/_shared/part-one-private-source.ts';
import { GenericCapturedSourceOutcomeSchema } from '../src/contracts/PartOneCapturedSource.ts';
import { evaluatePrivateEvidence } from '../supabase/functions/_shared/part-one-private-evidence.ts';
import { factBundleClaimLimits } from '../src/domain/part-one/evidence.ts';
import { capturedSourceContext, sourceId, withGtinCheckDigit } from './fixtures/part-one-private-source.ts';
const hash=async(value:string)=>createHash('sha256').update(value).digest('hex');
const extract=(input:ReturnType<typeof capturedSourceContext>)=>extractPrivateCapturedSource(input,{hash});
function replaceText(input:ReturnType<typeof capturedSourceContext>,text:string,index=0){const o=input.observations[index];o.rawText=text;o.ocr!.lines=text.split('\n').map((text,n)=>({text,alternatives:[],region:[0.1,n*0.04,0.8,0.035],confidence:0.99}));}

test('Novel GTIN/variant/market/category and chemical text yield literal owner-private candidates without a registry',async()=>{
 for(const [body,brand,market,size]of [['850912345678','New Orchard Labs','CA','75'],['735194620851','Harbor Formula','GB','240']]){
  const code=withGtinCheckDigit(body),text=`Product name: ${brand} Night Mist\nBrand: ${brand}\nLine: Night\nForm: mist\nScent: fragrance-free\nSize: ${size} ml\nMarket: ${market}\nCategory: Cosmetic\nGTIN: ${code}\nIngredients: 1,2-Hexanediol, Aqua (Water, Eau), PEG-240/HDI Copolymer\nDirections: Apply externally`;
  const input=capturedSourceContext([text],code),before=structuredClone(input),out=await extract(input);
  assert.equal(out.state,'partial');assert.equal(out.candidate?.packageIdentity?.code.raw,code);assert.equal(out.candidate?.variant.brand,brand);assert.equal(out.candidate?.variant.size,size);assert.equal(out.candidate?.variant.unit,'ml');assert.equal(out.candidate?.packageMarket,market);assert.equal(out.candidate?.category,'cosmetic');assert.equal(out.candidate?.association,'barcode_matches_catalog_same_asset');
  assert.deepEqual(out.facts.sections[0].entries.map(e=>e.rawToken),['1,2-Hexanediol','Aqua (Water, Eau)','PEG-240/HDI Copolymer']);assert.equal(out.facts.sections[0].lineCoverageComplete,false);assert.equal(out.absenceClaimsAllowed,false);assert.equal(out.catalogVerified,false);assert.equal(out.acceptanceEligible,false);assert.deepEqual(input,before);
  for(const ref of [...out.candidate!.packageIdentity!.evidenceRefs,...Object.values(out.candidate!.variantRefs).flat(),...out.candidate!.marketRefs,...out.candidate!.sections.flatMap(s=>s.lineRefs)])assert.equal(text.slice(ref.start,ref.end),ref.text);
 }
});
test('Observed section headings and next heading bound text but never prove all optical lines',async()=>{const out=await extract(capturedSourceContext(['Category: Cosmetic\nIngredients: Water, Glycerin\nWarnings: Avoid eyes']));assert.equal(out.candidate!.sections[0].startCovered,true);assert.equal(out.candidate!.sections[0].endCovered,true);assert.equal(out.candidate!.sections[0].lineCoverageComplete,false);assert.ok(out.reasonCodes.includes('full_panel_not_established'));assert.ok(out.candidate!.gaps.some(g=>g.code==='ocr_panel_coverage_unverified'));});
test('Missing tail/header, explanatory table and unknown fields remain partial',async()=>{for(const text of ['Ingredients: Water, Glycerin','Water, Glycerin','Ingredients:\nWater\tHumectant\nGlycerin\tMoisturizer']){const out=await extract(capturedSourceContext([text]));assert.equal(out.state,'partial');assert.equal(out.candidate!.category,'unknown');assert.equal(out.candidate!.packageMarket,null);assert.equal(out.acceptanceEligible,false);}assert.ok((await extract(capturedSourceContext(['Ingredients: Water']))).reasonCodes.includes('section_tail_not_observed'));assert.ok((await extract(capturedSourceContext(['Water']))).reasonCodes.includes('ingredient_header_not_observed'));});
test('Package metadata following ingredients is extracted separately, never promoted into INCI tokens',async()=>{const out=await extract(capturedSourceContext(['Ingredients: Water, Glycerin\nMarket: US\nBrand: Cedar Lane\nSize: 30 ml']));assert.deepEqual(out.facts.sections[0].entries.map(e=>e.rawToken),['Water','Glycerin']);assert.equal(out.candidate!.variant.brand,'Cedar Lane');assert.equal(out.candidate!.packageMarket,'US');});
test('Multi-line chemical tokens retain per-line image intersections and exact punctuation',async()=>{const text='Ingredients: Aqua (Water,\nEau), 1,2-Hexanediol\nDirections: Apply';const out=await extract(capturedSourceContext([text]));const token=out.facts.sections[0].entries[0];assert.equal(token.rawToken,'Aqua (Water,\nEau)');assert.equal(token.sourceSpans.length,2);assert.notDeepEqual(token.sourceSpans[0].region,token.sourceSpans[1].region);for(const span of token.sourceSpans){assert.ok(!text.slice(span.start!,span.end!).includes('\n'));for(const t of span.transformation){assert.ok(t.sourceStart>=span.start!);assert.ok(t.sourceEnd<=span.end!);}}});
test('Separate package and ingredient photos do not manufacture physical package linkage',async()=>{const code=withGtinCheckDigit('850912345678');const out=await extract(capturedSourceContext([`GTIN: ${code}\nBrand: Juniper`, 'Ingredients: Water, Betaine'],code));assert.equal(out.candidate!.association,'barcode_matches_catalog_unlinked_assets');assert.ok(out.reasonCodes.includes('same_package_photo_link_unestablished'));});
test('Contradictory valid codes, label variants/markets/categories and selected identity cannot be repaired by mixing',async()=>{
 const a=withGtinCheckDigit('850912345678'),b=withGtinCheckDigit('735194620851');for(const text of [`GTIN: ${a}\nGTIN: ${b}\nIngredients: Water`,`GTIN: ${a}\nBrand: Cedar\nBrand: Harbor\nIngredients: Water`,`Market: US\nMarket: CA\nIngredients: Water`,`Category: Cosmetic\nDrug Facts\nActive ingredients: Zinc Oxide 10%`]){const out=await extract(capturedSourceContext([text],a));assert.equal(out.state,'conflict');assert.equal(out.candidate!.association,'contradiction');}
 const selected=await extract(capturedSourceContext([`GTIN: ${a}\nBrand: Other\nIngredients: Water`],a,{brand:'Selected'}));assert.ok(selected.candidate!.contradictions.some(c=>c.kind==='variant'&&c.field==='brand'));
});
test('Confidence and absence of alternatives cannot establish panel completeness; alternatives/glare stay visible gaps',async()=>{const input=capturedSourceContext(['Ingredients: Water, Glycerin']);input.observations[0].ocr!.lines[0].confidence=1;input.observations[0].ocr!.lines[0].alternatives=['Ingredients: Alcohol'];input.observations[0].uncertaintyReasons=['glare'];const out=await extract(input);assert.equal(out.acceptanceEligible,false);assert.ok(out.reasonCodes.includes('recognition_alternatives_unresolved'));assert.ok(out.candidate!.gaps.some(g=>g.code==='glare'));assert.equal(out.facts.sections[0].lineCoverageComplete,false);});
test('Original/derivative disagreement and changed correction remain attributable conflict; original is never overwritten',async()=>{
 const input=capturedSourceContext(['Ingredients: Water, Glycerin']),derivative=input.observations[0],original=structuredClone(derivative);original.observationId=sourceId(90);original.originalObservationId=sourceId(90);original.coordinateSpace='source_original';original.rawText='Ingredients: Water, Alcohol';original.ocr!.lines[0].text=original.rawText;original.ocr!.sourceWidth=5120;original.ocr!.sourceHeight=1280;derivative.derivedFromObservationIds=[original.observationId];input.observations.push(original);
 const out=await extract(input);assert.equal(out.state,'conflict');assert.ok(out.reasonCodes.includes('source_derivative_text_disagreement'));assert.equal(original.rawText,'Ingredients: Water, Alcohol');
 const edited=capturedSourceContext(['Ingredients: Water, Glycerin']),prior=edited.observations[0],head=structuredClone(prior);head.observationId=sourceId(91);head.revision=2;head.kind='edit';head.rawText='Ingredients: Water, Alcohol';head.supersedesId=prior.observationId;head.ocr=null;head.edit={observationId:head.observationId,supersedesId:prior.observationId,revision:2,text:head.rawText,reason:'Attributed operator edit'};edited.observations=[head];edited.priorObservations=[prior];const correction=await extract(edited);assert.equal(correction.state,'conflict');assert.equal(correction.facts.capturedText[0].attributedEdit,true);assert.ok(correction.reasonCodes.includes('source_edit_text_disagreement'));
});
test('Owner/lifecycle/rights and exact derivative geometry fail closed without exposing raw text',async()=>{for(const mutate of [(i:ReturnType<typeof capturedSourceContext>)=>i.observations[0].ownerId=sourceId(99),(i:ReturnType<typeof capturedSourceContext>)=>i.assets[0].expiresAt=i.now,(i:ReturnType<typeof capturedSourceContext>)=>i.policy.operations.retain=false,(i:ReturnType<typeof capturedSourceContext>)=>i.observations[0].ocr!.sourceWidth=5120,(i:ReturnType<typeof capturedSourceContext>)=>i.observations[0].ocr!.lines[0].text='Changed']){const input=capturedSourceContext(['Ingredients: Hidden private text']);mutate(input);const out=await extract(input);assert.equal(out.state,'blocked');assert.equal(out.candidate,null);assert.deepEqual(out.facts,{sections:[],capturedText:[]});}});
test('Restricted UPC namespace, invalid check digit and ambiguous eight-digit code are not global identities',async()=>{for(const code of ['200000000004','8509123456781','01234565']){const out=await extract(capturedSourceContext([`GTIN: ${code}\nIngredients: Water`]));assert.equal(out.candidate!.packageIdentity,null);assert.equal(out.acceptanceEligible,false);}});
test('Category is not inferred from ingredients or cosmetic routing, and country of origin is not sales market',async()=>{const input=capturedSourceContext(['Made in: FR\nIngredients: Water, Glycerin']);input.item!.sourceMarkets=['US'];const out=await extract(input);assert.equal(out.candidate!.category,'unknown');assert.equal(out.candidate!.packageMarket,null);assert.equal(out.candidate!.variant.brand,null);});
test('Candidate IDs/hashes are deterministic, output immutable, expiry includes original ancestors',async()=>{const input=capturedSourceContext(['Ingredients: Water']),one=await extract(input),two=await extract(structuredClone(input));assert.deepEqual(one,two);assert.equal(GenericCapturedSourceOutcomeSchema.safeParse({...one,acceptanceEligible:true}).success,false);assert.throws(()=>one.facts.sections[0].rawText='Changed',TypeError);input.assets[0].expiresAt='2026-10-02T12:05:00.000Z';assert.equal((await extract(input)).candidate!.expiresAt,input.assets[0].expiresAt);});
test('Superseded selections, cycles and a receipt/user boolean cannot enter the typed generic source boundary',async()=>{const input=capturedSourceContext(['Ingredients: Water']);const clone=structuredClone(input.observations[0]);clone.observationId=sourceId(95);clone.originalObservationId=clone.observationId;clone.supersedesId=input.observations[0].observationId;input.observations.push(clone);assert.equal((await extract(input)).state,'blocked');assert.rejects(()=>extractPrivateCapturedSource({...capturedSourceContext(['Ingredients: Water']),complete:true} as never,{hash}));});
test('Readable partial ingredient spans retain observed presence without granting full-list absence',async()=>{const input=capturedSourceContext(['Ingredients: Water, 1,2-Hexanediol']),out=await extract(input);assert.ok(out.facts.sections[0].entries.every(e=>e.uncertaintyReasons.length===0));assert.equal(out.facts.sections[0].lineCoverageComplete,false);const evaluation=await evaluatePrivateEvidence(input,{hash});const capabilities=factBundleClaimLimits(evaluation.factBundle!,input.now);assert.equal(capabilities.readableEntryIds.length,2);assert.equal(capabilities.fullListAbsence,false);});
test('Alternatives on one OCR line affect its tokens while another literal line stays readable; glare stays conservative',async()=>{const input=capturedSourceContext(['Ingredients: Water,\nGlycerin\nWarnings: External']);input.observations[0].ocr!.lines[0].alternatives=['Ingredients: Alcohol,'];const out=await extract(input);assert.ok(out.facts.sections[0].entries[0].uncertaintyReasons.includes('recognition_alternatives_unresolved'));assert.deepEqual(out.facts.sections[0].entries[1].uncertaintyReasons,[]);input.observations[0].uncertaintyReasons=['glare'];assert.ok((await extract(input)).facts.sections[0].entries.every(e=>e.uncertaintyReasons.includes('glare')));});
test('A package-role transcript retains label text and explicit fields without asserting ingredient sections',async()=>{const input=capturedSourceContext(['Brand: New Garden\nIngredients: Water, Glycerin']);input.observations[0].role='package';const out=await extract(input);assert.equal(out.candidate!.variant.brand,'New Garden');assert.deepEqual(out.facts.sections,[]);assert.equal(out.facts.capturedText[0].rawText,input.observations[0].rawText);});
