import assert from 'node:assert/strict';
import test from 'node:test';
import { createJevProvider,createJevHttpTransport,parseUniqueJson,JEV_PROTOCOL,type EligibleMenu,type AuthorizedProjection } from '../src/domain/part-three/provider.ts';
import { canonicalJson,sha256 } from '../src/domain/part-two/hash.ts';
const menuBase={candidateSetId:'menu',jobs:[{id:'prioritize_tradeoff' as const,options:[{id:'none',description:'No optional tradeoff'},{id:'trade',description:'Known replacement relation'}]},{id:'select_question' as const,options:[{id:'none',description:'No question'},{id:'ask',description:'Clarify add or replace'}]}],compatiblePairs:[[null,null],['trade','ask'],['trade',null],[null,'ask']] as Array<[string|null,string|null]>};
const menu:EligibleMenu={...menuBase,candidateSetHash:sha256(canonicalJson(menuBase))};
const projection:AuthorizedProjection={version:'part-three-provider-projection/v1',purpose:'optional_content_selection',approvalId:'synthetic-only',fields:[{id:'intent',value:'unknown',externalOperationGrant:'synthetic-grant',sourceFieldId:'synthetic-field'}]};
const valid=()=>({model:'jev-1.13.0',answers:{prioritize_tradeoff:{type:'choice',choice:'o001',probabilities:{o000:0.2,o001:0.8},confidence:0.6},select_question:{type:'choice',choice:'o001',probabilities:{o000:0.2,o001:0.8},confidence:0.6}},usage:{input_tokens:50,output_tokens:20}});
async function replay(response:unknown){let calls=0;const provider=createJevProvider({async send(request){calls++;assert.equal(request.model,'jev-1.13.0');assert.equal(Object.keys(request.questions).length,2);assert(!JSON.stringify(request).includes('synthetic-grant'));assert(!JSON.stringify(request).includes('synthetic-only'));assert(!JSON.stringify(request).includes('candidateSet'));return typeof response==='string'?response:JSON.stringify(response);}},'jev-1.13.0');const selected=await provider.evaluate(projection,menu,new AbortController().signal,Date.now()+1500);assert.equal(calls,1);return selected;}
test('native Jev Choice is converted into provider-neutral selection without headline/prose authority',async()=>{const r=await replay(valid());assert.equal(r.outcome,'accepted');assert.equal(r.selectedTradeoffId,'trade');assert.equal(r.selectedQuestionId,'ask');assert.deepEqual(r.usage,{inputTokens:50,outputTokens:20});assert(!('judgment' in r));});
test('exact menu/probability/confidence/model/usage schemas fail closed',async()=>{const cases=[(r:any)=>delete r.answers.select_question.confidence,(r:any)=>r.answers.select_question.probabilities.extra=0,(r:any)=>r.answers.extra=r.answers.select_question,(r:any)=>r.model='jev-latest',(r:any)=>r.answers.select_question.choice='o000',(r:any)=>r.answers.select_question.probabilities.o001=0.9,(r:any)=>r.answers.select_question.confidence=0.99,(r:any)=>r.usage.input_tokens=-1,(r:any)=>r.judgment='safe'];for(const mutate of cases){const r=valid();mutate(r);assert.equal((await replay(r)).outcome,'invalid');}});
test('duplicate keys, malformed JSON and byte cap reject before JSON field loss',async()=>{assert.throws(()=>parseUniqueJson('{"a":1,"a":2}'));for(const text of ['not JSON','{"model":"jev-1.13.0","model":"jev-1.13.0"}', ' '.repeat(JEV_PROTOCOL.responseBytes+1)])assert.equal((await replay(text)).outcome,'invalid');});
test('unsupported projection fields and mismatched menu hash make no transport call',async()=>{const provider=createJevProvider({async send(){assert.fail('Transport must not be called');}},'jev-1.13.0');for(const [p,m] of [[{...projection,ownerId:'private'},menu],[projection,{...menu,candidateSetHash:'wrong'}],[{...projection,fields:[{...projection.fields[0],value:'raw note'}]},menu]])assert.equal((await provider.evaluate(p as any,m as any,new AbortController().signal,Date.now()+1500)).outcome,'disallowed');assert.throws(()=>createJevProvider({send:async()=>''},'jev-latest'));});
test('single attempt deadline aborts transport and refuses late success',async()=>{let calls=0,aborted=false;const provider=createJevProvider({async send(_r,signal){calls++;signal.addEventListener('abort',()=>{aborted=true;});await new Promise(resolve=>setTimeout(resolve,30));return JSON.stringify(valid());}},'jev-1.13.0');assert.equal((await provider.evaluate(projection,menu,new AbortController().signal,Date.now()+5)).outcome,'timeout');assert.equal(calls,1);assert(aborted);await new Promise(resolve=>setTimeout(resolve,35));});
test('real HTTP transport wire uses one injected fetch without retry or logs',async()=>{let calls=0;const fetcher:typeof fetch=async(input,init)=>{calls++;assert.equal(input,'https://api.typesafe.ai/v1/systemone');assert.equal(init?.redirect,'error');return new Response(JSON.stringify(valid()),{status:200,headers:{'content-type':'application/json'}});};const provider=createJevProvider(createJevHttpTransport(fetcher,()=> 'synthetic-not-a-credential'),'jev-1.13.0');assert.equal((await provider.evaluate(projection,menu,new AbortController().signal,Date.now()+1500)).outcome,'accepted');assert.equal(calls,1);const refusal=createJevProvider(createJevHttpTransport(async()=>{calls++;return new Response('{}',{status:429,headers:{'retry-after':'99'}});},()=> 'synthetic-not-a-credential'),'jev-1.13.0');assert.equal((await refusal.evaluate(projection,menu,new AbortController().signal,Date.now()+1500)).outcome,'unavailable');assert.equal(calls,2);});
