import assert from 'node:assert/strict';
import test from 'node:test';
import {evaluatePersonalResult,type PersonalEvaluationInput} from '../src/domain/part-three/evaluate.ts';
import {PersonalResultV2Schema,type PersonalResultV2} from '../src/contracts/PersonalResultV2.ts';
import {decisionCopy,findingCopy,reportQualifierCopy} from '../src/presentation/part-three/copy.ts';
import {retrieveDecisionHistory} from '../src/domain/part-three/history.ts';
import {createPartThreeController,createQuestionLatchStore} from '../src/presentation/part-three/controller.ts';
import type {PartThreeTarget} from '../src/presentation/part-three/target.ts';
import type {PartThreeRequest,PartThreeResponse} from '../src/contracts/PartThreeService.ts';
import {personalContextV2Schema} from '../src/contracts/PersonalContextV2Schema.ts';
import {migratePersonalContextV1,projectPersonalContextV1} from '../src/services/context/migrateV2.ts';
import {canonicalJson,sha256} from '../src/domain/part-two/hash.ts';
import {handlePersonalRequest,type PartThreePorts} from '../supabase/functions/part-three/handler.ts';
import {eligibleMenuFor} from '../src/domain/part-three/menu.ts';
import {PART_THREE_RELEASE} from '../src/domain/part-three/release.ts';
import {acceptanceCases,A,baseInput,align,evidence,comparator,keepInput,avoid,recalled,goldenPacket,purposeFinding,positivePlan,replacementPlan,unknownPlan,experienceFinding,reactionPlan,extraPlan,expectedCopy,reportQualifiers,fixtureFactories,type GoldPlan,type AcceptanceId} from './fixtures/part-three-acceptance.ts';
import {p3revision,p3routine} from './fixtures/part-three.ts';
import {p2id,p2metadata} from './fixtures/part-two-core.ts';

const replacementCopies=['This is a replacement comparison with the current item you selected.',expectedCopy.replacement.reason];
const safeCopy=/\b(?:safe|no concerns|free of|culprit|allergy diagnosis|better results|stronger product|compatibility score)\b/i;
function check(x:PersonalEvaluationInput,plan:GoldPlan,copy:Omit<ReturnType<typeof decisionCopy>,'name'>,findingCopies:string[],qualifiers?:string[][]){
 align(x);const expected=goldenPacket(x,plan),actual=evaluatePersonalResult(x);
 assert(PersonalResultV2Schema.safeParse(expected).success,'Golden packet must satisfy strict public contract');
 assert.deepEqual(actual,expected,'Full packet, earning references, exact source/context dependencies and all rule states');
 assert.deepEqual(decisionCopy(actual),{name:plan.state?'Personal Check':x.name,...copy});
 assert.deepEqual(actual.findings.map(findingCopy),findingCopies);
 if(qualifiers)assert.deepEqual(actual.findings.map(reportQualifierCopy),qualifiers);
 assert(!safeCopy.test([copy.label,copy.reason,copy.scope,...findingCopies].join(' ')),'Copy cannot promote clinical/safety/causal/absence meanings');
 for(const f of actual.findings){assert.deepEqual(f.factRefs,f.dependencies.factIds);assert.deepEqual(f.reportRefs,f.dependencies.contextRevisionIds);assert(Date.parse(f.dependencies.validUntil)>=Date.parse(actual.validUntil));}
 return actual;
}
const sensitivityPlan=():GoldPlan=>({judgment:'check_first',findings:[{kind:'sensitivity',rule:'reported-sensitivity',consequence:'concern',detail:'reaction',fact:'identity',reports:[A.profile],name:'Glycerin'},purposeFinding()],primary:0,scope:'published_version',eligibleRules:['reported-sensitivity','purpose-value']});
const avoidancePlan=(value=true):GoldPlan=>({judgment:'skip',findings:[{kind:'avoidance',rule:'exact-avoidance',consequence:'decisive',detail:'preference',fact:'identity',reports:[A.pref],name:'Glycerin'},...(value?[purposeFinding()]:[])],primary:0,scope:'published_version',eligibleRules:['exact-avoidance',...(value?['purpose-value']:[])]});
const keepPlan=():GoldPlan=>({judgment:'worth_considering',variant:'worth_keeping',findings:[{kind:'current_help',rule:'current-help',consequence:'value',detail:'helps',reports:[A.routine,A.assessment,A.profile],scope:'report',relation:'selected_manual',subject:{kind:'report',recordId:A.assessmentRecord,relation:'selected_manual'}}],primary:0,scope:'report',eligibleRules:['current-help']});
function target(x:PersonalEvaluationInput):PartThreeTarget {align(x);const {attemptId,...binding}=x.binding;return {binding,request:{encounterId:binding.encounterId,accountGeneration:binding.accountGeneration,generation:binding.generation,scanId:binding.scanId,captureSessionId:binding.captureSessionId,expectedPartOneGeneration:binding.partOneGeneration,expectedPartOneRevision:binding.partOneRevision,intent:binding.intent,comparatorId:binding.comparatorId,candidateRoutineItemId:x.candidateRoutineItemId,selectedManualReportIds:x.selectedManualReportIds,use:x.requestedUse,savedAssessmentId:null}};}
function controller(x:PersonalEvaluationInput,plan:GoldPlan,request?:(r:PartThreeRequest,packet:PersonalResultV2)=>Promise<PartThreeResponse>|PartThreeResponse){let sequence=600,evaluations=0,packet=goldenPacket(align(x),plan);const client=createPartThreeController({request:async r=>{
 if(r.operation==='evaluate')packet={...packet,resultId:++evaluations===1?packet.resultId:r.requestId,binding:{...packet.binding,attemptId:r.requestId}};
 if(request)return request(r,structuredClone(packet));
 return r.operation==='question_event'?{kind:'acknowledged'}:{kind:'result',result:structuredClone(packet),replayed:r.operation==='read'};
}},()=>p2id(sequence++),()=>{},()=>Date.parse(x.now),createQuestionLatchStore());client.bind(target(x));return client;}
const tick=()=>new Promise<void>(r=>setImmediate(r));
const cases:Partial<Record<AcceptanceId,()=>void|Promise<void>>>={
 J01(){const x=baseInput(),raw=fixtureFactories.boundDeclaration('Glycerin, Aqua','public');Object.assign(raw.bundle,{state:'accepted',completenessReasons:[]});raw.bundle.predicate.completeness={passed:true,evidenceIds:[p2id(7)],reasons:[]};raw.declaration.completenessReasons=[];evidence(x,raw);x.context.profile!.data.primaryGoal={state:'unanswered'};check(x,unknownPlan(),expectedCopy.unknown,[]);if(x.partTwo.state==='ready'&&x.partTwo.output.kind==='bound'){assert.equal(x.partTwo.output.productFacts.claimLimits.declarationCompleteness,'accepted');assert.equal(x.partTwo.output.productFacts.claimLimits.negativeClaimsAllowed,false);}},
 J02(){check(comparator(),replacementPlan(),expectedCopy.replacement,replacementCopies);},
 J03(){const x=baseInput();x.context.profile!.data.primaryGoal={state:'known',value:'dark_spots'};check(x,unknownPlan('purpose_or_site'),expectedCopy.useGap,[]);},
 J04(){const x=avoid(comparator(),true),plan:GoldPlan={judgment:'check_first',findings:[{kind:'evidence_limit',rule:'unresolved-avoidance',consequence:'information',detail:'unresolved',reports:[A.pref],name:'My unresolved term'},...replacementPlan().findings],gaps:[['avoidance_unresolved','missing','evidence']],primary:0,scope:'published_version',eligibleRules:['purpose-value','pair-comparison']};const r=check(x,plan,{label:'Check first',reason:'Your confirmed avoidance term “My unresolved term” remains unresolved; a match cannot be established.',scope:expectedCopy.positive.scope},['Your confirmed avoidance term “My unresolved term” remains unresolved; a match cannot be established.',...replacementCopies]);assert.equal(r.findings[0].arguments.name,'My unresolved term');},
 J05(){const x=comparator();x.context.profile!.data.reproductive={pregnancy:'withheld',tryingToConceive:'withheld',nursing:'withheld'};check(x,replacementPlan(),expectedCopy.replacement,replacementCopies);},
 J06(){const x=keepInput();check(x,keepPlan(),expectedCopy.keep,[expectedCopy.keep.reason]);for(const field of ['purpose','site','useForm'] as const){const bad=structuredClone(x);if(field==='purpose')bad.requestedUse.purpose='cleansing';else if(field==='site')bad.requestedUse.site='hands';else bad.requestedUse.useForm='rinse_off';check(bad,unknownPlan('purpose_or_site'),expectedCopy.useGap,[]);}},
 J07(){for(const kind of ['liked','finished','no_reaction_reported'] as const){const x=recalled(keepInput(),kind);x.context.assessments=[];x.context.profile!.data.reactivity='generally_tolerates';const f=experienceFinding(x);const words={liked:'liking it',finished:'finishing it',no_reaction_reported:'no reaction'}[kind];check(x,{...unknownPlan('purpose_or_site'),findings:[f],eligibleRules:['experience-recall']},expectedCopy.useGap,[`You reported ${words} for the report you selected.`],[reportQualifiers]);}},
 J08(){const x=avoid(baseInput());check(x,avoidancePlan(),{label:'Skip this one',reason:'This conflicts with your confirmed choice to avoid Glycerin.',scope:expectedCopy.positive.scope},['This conflicts with your confirmed choice to avoid Glycerin.',expectedCopy.positive.reason]);const y=baseInput();y.context.profile!.data.sensitivities={status:'reported',values:['Glycerin']};const r=check(y,sensitivityPlan(),{label:'Check first',reason:'This list includes Glycerin, which you reported as a sensitivity.',scope:expectedCopy.positive.scope},['This list includes Glycerin, which you reported as a sensitivity.',expectedCopy.positive.reason]);assert(r.findings[0].dependencies.occurrenceIds.length===1);},
 J09(){const x=avoid(baseInput());assert(x.partTwo.state==='ready'&&x.partTwo.output.kind==='bound');assert.equal(x.partTwo.output.productFacts.claimLimits.declarationCompleteness,'partial');check(x,avoidancePlan(),{label:'Skip this one',reason:'This conflicts with your confirmed choice to avoid Glycerin.',scope:expectedCopy.positive.scope},['This conflicts with your confirmed choice to avoid Glycerin.',expectedCopy.positive.reason]);},
 J10(){for(const mode of ['reading','conditional'] as const){const x=avoid(baseInput());if(mode==='reading')evidence(x,fixtureFactories.sourceReading('Glycerin'));else {const raw=fixtureFactories.boundDeclaration('May contain: Glycerin','public');evidence(x,raw);}const gaps:NonNullable<GoldPlan['gaps']>=[['avoidance_unresolved','missing','evidence']];if(mode==='reading')gaps.push(['identity_or_use','missing','evidence']);gaps.push(['purpose_coverage','missing','reviewer']);check(x,{judgment:'check_first',findings:[{kind:'evidence_limit',rule:'exact-avoidance',consequence:'information',detail:'conditional',fact:'identity',reports:[A.pref],name:'Glycerin'}],gaps,primary:0,scope:mode==='reading'?'source_reading':'published_version',eligibleRules:['exact-avoidance']},{label:'Check first',reason:'This is conditional or source-only wording; definite product presence is unconfirmed.',scope:mode==='reading'?'Photo reading · Product presence unconfirmed':expectedCopy.positive.scope},['This is conditional or source-only wording; definite product presence is unconfirmed.']);}},
 J11(){const x=baseInput(),raw=fixtureFactories.boundLabelDeclaration('Moisturizes facial skin. Leave on.','purpose','public');Object.assign(raw.bundle,{state:'conflict',conflictIds:[p2id(220)]});raw.bundle.predicate.noContradiction={passed:false,evidenceIds:[p2id(7)],reasons:['sources_disagree']};raw.declaration.conflictIds=[p2id(220)];evidence(x,raw);check(x,{...unknownPlan(),gaps:[['formula_association','conflict','evidence'],['purpose_coverage','missing','reviewer']]},{label:'Not enough info',reason:'Sources disagree on a material fact. This Check keeps that conflict unresolved.',scope:expectedCopy.positive.scope},[]);},
 J12(){for(const text of ['Glycerin','Glycerin 2%, Aqua','Aqua, Glycerin'] as const){const x=evidence(baseInput(),fixtureFactories.boundDeclaration(text,'public'));check(x,unknownPlan(),expectedCopy.unknown,[]);assert(x.partTwo.state==='ready'&&x.partTwo.output.kind==='bound');assert(x.partTwo.output.productFacts.facts.some(f=>f.kind==='reference_function'));if(text.includes('2%')){const q=x.partTwo.output.productFacts.facts.find(f=>f.kind==='declared_quantity');assert(q?.kind==='declared_quantity');assert(q.value.span.raw.includes('2%'));assert.equal(q.value.value,'2');assert.equal(q.value.operator,'exact');assert.equal(q.value.unit,'%');assert.equal(q.value.basis,'unknown');assert.equal(q.value.subject,'ingredient');assert.equal(q.value.convertedPercentWw,null);}}},
 C01(){const x=recalled(baseInput());check(x,reactionPlan(x),expectedCopy.reaction,[expectedCopy.reaction.reason,expectedCopy.positive.reason],[reportQualifiers,[]]);const y=comparator(baseInput(),'add');y.binding.comparatorId=null;y.candidateRoutineItemId=A.item;y.context.assessments=[];const ref={kind:'catalog' as const,productId:p2id(230),variantId:null,formulaVersionId:null};y.context.routine!.data.items[0].reference=ref;recalled(y,'reacted',ref);check(y,reactionPlan(y,'product_family'),{label:'Check first',reason:'You reported a reaction with this product family.',scope:'Based on your report'},['You reported a reaction with this product family.',expectedCopy.positive.reason],[[reportQualifiers[0],'The report identifies a product family; its formula version is unconfirmed.',reportQualifiers[2]],[]]);assert(y.binding.subject.kind==='declaration'&&y.binding.subject.productId===null);},
 C02(){const x=comparator(baseInput(),'add');x.binding.comparatorId=null;x.candidateRoutineItemId=A.item;x.context.assessments=[];const ref={kind:'catalog' as const,productId:p2id(230),variantId:p2id(231),formulaVersionId:p2id(232)};x.context.routine!.data.items[0].reference={...ref,formulaVersionId:p2id(233)};recalled(x,'reacted',ref);const r=check(x,reactionPlan(x,'product_family'),{label:'Check first',reason:'You reported a reaction with this product family.',scope:'Based on your report'},['You reported a reaction with this product family.',expectedCopy.positive.reason],[[reportQualifiers[0],'The report records a formula version; matching this package is unconfirmed.',reportQualifiers[2]],[]]);assert.equal(r.findings[0].arguments.reportTrace!.reference.kind,'catalog');x.context.experiences[0].revision=2;x.context.experiences[0].supersedesRevisionId=A.report;x.context.experiences[0].id=p2id(234);x.context.experiences[0].data.kind='no_reaction_reported';x.history.activeRevisionIds=[p2id(234)];check(x,{...positivePlan(),findings:[experienceFinding(x,'product_family'),purposeFinding()],primary:1,eligibleRules:['experience-recall','purpose-value']},expectedCopy.positive,['You reported no reaction with this product family.',expectedCopy.positive.reason]);x.context.experiences=[];x.history.activeRevisionIds=[];check(x,positivePlan(),expectedCopy.positive,[expectedCopy.positive.reason]);},
 C03(){for(const frequency of [{kind:'exact' as const,count:2.5,unit:'week' as const},{kind:'qualitative' as const,value:'most_days' as const}]){const x=recalled(baseInput(),'liked');x.context.profile!.data.primaryGoal={state:'withheld'};x.context.experiences[0].data.useContext!.frequency=frequency;x.context.experiences[0].data.useContext!.startedOn={state:'known',value:{value:'2020-03',precision:'month'}};align(x);assert.deepEqual(personalContextV2Schema.parse(JSON.parse(JSON.stringify(x.context))),x.context);const label=frequency.kind==='exact'?'2.5 times per week':'most days';check(x,{...unknownPlan('purpose_or_site'),findings:[experienceFinding(x)],eligibleRules:['experience-recall']},expectedCopy.useGap,['You reported liking it for the report you selected.'],[[reportQualifiers[0],reportQualifiers[1],`Reported use: ${label}; started 2020-03 (month precision); stopped not reported.`]]);const v1=projectPersonalContextV1(x.context);assert.equal(v1.experiences[0].data.useContext!.startedOn,null);assert.equal(migratePersonalContextV1(v1).profile!.data.primaryGoal.state,'unanswered');}},
 C04(){for(const variant of ['purpose','site','form','paused','stopped'] as const){const x=comparator();const i=x.context.routine!.data.items[0];if(variant==='purpose')i.reportedPurpose!.answer={state:'known',value:'cleansing'};if(variant==='site')i.applicationSite!.answer={state:'known',value:'hands'};if(variant==='form')i.useForm!.answer={state:'known',value:'rinse_off'};if(variant==='paused'||variant==='stopped')i.state=variant;check(x,{...unknownPlan('purpose_or_site'),findings:[{kind:'comparison',rule:'different-use',consequence:'information',detail:'different_use',scope:'comparison',reports:[A.routine],subject:{kind:'comparison',candidateItemId:p2id(11),comparatorId:A.item}}],eligibleRules:['pair-comparison']},expectedCopy.useGap,['The selected items have different or unresolved purposes, sites or use forms.']);}},
 C05(){const x=comparator(baseInput(),'add');x.context.profile!.data.primaryGoal={state:'known',value:'simplify'};check(x,extraPlan(),expectedCopy.extra,[expectedCopy.extra.reason]);x.binding.intent='replace';check(x,replacementPlan(),expectedCopy.replacement,replacementCopies);},
 C06(){for(const variant of ['dissatisfied','not_helping','mixed'] as const){const x=comparator();if(variant==='dissatisfied')x.context.assessments[0].data.satisfaction='dissatisfied';else x.context.assessments[0].data.perceivedHelp=variant;check(x,replacementPlan(),expectedCopy.replacement,replacementCopies);assert.equal(x.context.assessments[0].data[variant==='dissatisfied'?'satisfaction':'perceivedHelp'],variant);}},
 C07(){const x=comparator();x.context.routine!.data.items.push({...p3routine(p2id(240)),state:'paused',reference:{kind:'manual',name:'Unselected other step'}});const r=check(x,replacementPlan(),expectedCopy.replacement,replacementCopies);assert(!JSON.stringify(r).includes('Unselected other step'));},
 C08(){for(const goals of [['dryness','maintain'],['maintain','dryness']] as const){const x=comparator(baseInput(),'add');x.context.profile!.data.primaryGoal={state:'known',value:'simplify'};x.context.profile!.data.secondaryGoals=[...goals];check(x,extraPlan(),expectedCopy.extra,[expectedCopy.extra.reason]);}},
 C09(){for(const note of ['My partner reacts to everything.','I do not avoid glycerin.','I used that in 2020, not now.','Some days it helps, other days it is heavy.']){const x=baseInput();x.context.notes=[p3revision(A.note,{id:p2id(241),scope:'profile' as const,targetRef:null,text:note})];const r=check(x,positivePlan(),expectedCopy.positive,[expectedCopy.positive.reason]);assert.equal(x.context.preferences.length,0);assert(!JSON.stringify(r).includes(note));}},
 Q01(){const x=avoid(comparator(baseInput(),'unanswered'));const r=check(x,avoidancePlan(false),{label:'Skip this one',reason:'This conflicts with your confirmed choice to avoid Glycerin.',scope:expectedCopy.positive.scope},['This conflicts with your confirmed choice to avoid Glycerin.']);assert.equal(r.question,null,'All intent branches preserve the same decisive avoidance and useful first result');for(const intent of ['replace','add','unsure'] as const){const branch=structuredClone(x);branch.binding.intent=intent;const extra={...extraPlan().findings[0],consequence:'optional' as const};const findings=intent==='replace'?[...avoidancePlan(false).findings,...replacementPlan().findings]:intent==='add'?[...avoidancePlan(false).findings,extra,purposeFinding()]:avoidancePlan(false).findings;const more=intent==='replace'?replacementCopies:intent==='add'?[expectedCopy.extra.reason,expectedCopy.positive.reason]:[];check(branch,{...avoidancePlan(false),findings,eligibleRules:['exact-avoidance',...(intent==='unsure'?[]:['purpose-value','pair-comparison'])]},{label:'Skip this one',reason:'This conflicts with your confirmed choice to avoid Glycerin.',scope:expectedCopy.positive.scope},['This conflicts with your confirmed choice to avoid Glycerin.',...more]);}},
 async Q02(){const x=comparator(baseInput(),'unanswered'),plan={...unknownPlan('purpose_or_site'),question:true};const c=controller(x,plan);await c.evaluate();const first=c.getView().question;assert(first);assert.deepEqual(c.getView().result, goldenPacket({...x,binding:{...x.binding,attemptId:p2id(600)}},plan));c.questionEvent('answer');assert.equal(c.getView().question,null);await c.renew();assert.equal(c.getView().question,null);assert.equal(c.getView().result!.question!.id,first.id);c.close();
 const y=avoid(comparator(baseInput(),'unanswered'));y.context.preferences[0].data.strength='prefer';const optional:GoldPlan={...unknownPlan('purpose_or_site'),question:true,findings:[{...avoidancePlan(false).findings[0],consequence:'optional'}],eligibleRules:['exact-avoidance']};let refinement=false;
 const latch=controller(y,optional,(req,packet)=>{if(req.operation==='question_event')return {kind:'acknowledged'};if(refinement){const menu=eligibleMenuFor(packet.binding,packet.findings,packet.question)!;const original=packet.question;packet.resultRevision=2;packet.refinementStatus='accepted';packet.binding.refinement={candidateSetHash:menu.candidateSetHash,projectionVersion:PART_THREE_RELEASE.refinement.projection,promptVersion:PART_THREE_RELEASE.refinement.prompt,adapterVersion:PART_THREE_RELEASE.refinement.adapter,configuredModel:PART_THREE_RELEASE.refinement.configuredModel,resolvedModel:PART_THREE_RELEASE.refinement.configuredModel};packet.refinementTrace={callId:p2id(252),menu,originalQuestion:original,baselineTradeoffId:packet.selectedTradeoffId,selection:{selectedTradeoffId:packet.selectedTradeoffId,selectedQuestionId:null,provider:'jev',resolvedModel:PART_THREE_RELEASE.refinement.configuredModel,usage:{inputTokens:1,outputTokens:1},elapsedMs:1,contractVersion:'part-three-selection/v1',outcome:'accepted'},applied:true};packet.question=null;assert(PersonalResultV2Schema.safeParse(packet).success,'Late fixture is a valid accepted tradeoff with optional question none');}return {kind:'result',result:packet,replayed:req.operation==='read'};});
 await latch.evaluate();latch.exposeQuestion();const exposed=structuredClone(latch.getView().question);assert(exposed);refinement=true;await latch.renew();assert.deepEqual(latch.getView().question,exposed,'Late optional none must not remove a first-exposed question');latch.questionEvent('answer');await latch.renew();assert.equal(latch.getView().question,null,'Answer suppresses exposure and never permits a next question');latch.close();},
 async Q03(){const x=comparator(baseInput(),'unanswered'),plan={...unknownPlan('purpose_or_site'),question:true};const c=controller(x,plan);await c.evaluate();c.questionEvent('skip');await tick();await c.renew();assert.equal(c.getView().question,null);c.close();c.bind(target(x));await c.evaluate();assert.equal(c.getView().question,null);assert.deepEqual(decisionCopy(c.getView().result!),{name:x.name,...expectedCopy.useGap});c.close();},
 Q04(){const x=baseInput();x.context.profile!.data.reproductive.pregnancy='withheld';check(x,positivePlan(),expectedCopy.positive,[expectedCopy.positive.reason]);x.binding.encounterId=p2id(242);x.binding.generation++;check(x,positivePlan(),expectedCopy.positive,[expectedCopy.positive.reason]);assert.equal(x.context.profile!.data.reproductive.pregnancy,'withheld');},
 async L01(){const x=comparator(baseInput(),'add');x.binding.comparatorId=null;x.candidateRoutineItemId=A.item;x.context.assessments=[];recalled(x,'reacted',x.context.routine!.data.items[0].reference);const record=x.context.experiences[0];x.context.experiences=[];x.selectedManualReportIds=[];const cursors:Array<string|null>=[];const got=await retrieveDecisionHistory([{kind:'manual',recordId:A.item,name:'Synthetic current item'}],x.context.revision,async(_,cursor)=>{cursors.push(cursor);return {items:cursor?[record]:[],nextCursor:cursor?null:'outside-recent-overview',atRevision:x.context.revision};});assert.deepEqual(cursors,[null,'outside-recent-overview']);x.context.experiences=got.records;x.history=got.history;check(x,reactionPlan(x),expectedCopy.reaction,[expectedCopy.reaction.reason,expectedCopy.positive.reason],[reportQualifiers,[]]);},
 async L02(){for(const mode of ['repeated_cursor','cap','page_error','revision_changed'] as const){const x=baseInput();let visits=0;const got=await retrieveDecisionHistory([{kind:'catalog',productId:p2id(243)}],1,async()=>{visits++;if(mode==='page_error')throw Error('Synthetic page failure');return {items:mode==='cap'?Array.from({length:1001},(_,i)=>p3revision(p2id(3000+i),{id:p2id(5000+i),reference:{kind:'manual' as const,name:'Unrelated'},kind:'liked' as const,occurred:{start:{state:'unanswered' as const},end:{state:'unanswered' as const}},useContext:null,symptoms:[],note:null})):[],nextCursor:mode==='repeated_cursor'?'same':null,atRevision:mode==='revision_changed'?2:1};});assert.equal(got.history.reason,mode);assert(visits);x.history=got.history;check(x,{judgment:'not_enough_info',findings:[purposeFinding()],gaps:[['relevant_history','unavailable','none']],primary:null,scope:'published_version',eligibleRules:['purpose-value']},{label:'Not enough info',reason:'Relevant history could not be completely checked.',scope:expectedCopy.positive.scope},[expectedCopy.positive.reason]);}},
 async L03(){for(const change of ['profile','scan','comparator'] as const){const x=baseInput();let resolve!:(r:PartThreeResponse)=>void;let pendingPacket!:PersonalResultV2;const c=controller(x,positivePlan(),async(_,packet)=>{pendingPacket=packet;return new Promise(r=>{resolve=r;});});const pending=c.evaluate();const changed=target(x);changed.binding.generation++;if(change==='profile'){changed.binding.contextRevision++;changed.binding.profileRevision=p2id(244);}if(change==='scan'){changed.binding.scanId=p2id(245);changed.request.scanId=p2id(245);}if(change==='comparator'){changed.binding.comparatorId=A.item;changed.request.comparatorId=A.item;}c.bind(changed);resolve({kind:'result',result:pendingPacket,replayed:false});assert.equal(await pending,false);assert.equal(c.getView().result,null);assert.equal(await c.save(),null);c.close();}},
 async L04(){const x=baseInput();let resolve!:(r:PartThreeResponse)=>void;let pendingPacket!:PersonalResultV2;const c=controller(x,positivePlan(),async(_,packet)=>{pendingPacket=packet;return new Promise(r=>{resolve=r;});});const pending=c.evaluate(),foreign=target(x);foreign.binding.ownerId=p2id(246);foreign.binding.accountGeneration++;c.bind(foreign);resolve({kind:'result',result:pendingPacket,replayed:false});assert.equal(await pending,false);assert.equal(c.getView().result,null);c.close();let finish!:(r:PartThreeResponse)=>void;const saved=controller(x,positivePlan(),async(r,packet)=>r.operation==='save'?new Promise(done=>{finish=done;}):{kind:'result',result:packet,replayed:false});await saved.evaluate();const saving=saved.save();await tick();saved.bind(foreign);finish({kind:'saved',savedAssessmentId:p2id(247),resultRevision:1,replayed:false});assert.equal(await saving,null);assert.equal(saved.getView().savedAssessmentId,null);saved.close();},
 L05(){const x=baseInput();x.now=new Date(Date.parse(x.partTwo.expiresAt)+1).toISOString();check(x,{...unknownPlan(),state:'expired'},{label:'Personal assessment unavailable',reason:'There is no supported personal premise for this judgment.',scope:null},[]);},
 async L07(){const x=comparator(),plan=replacementPlan();let revision=1,state:PersonalResultV2['state']='pending';const c=controller(x,plan,async(_,packet)=>{const value={...packet,resultRevision:revision,state,summary:state==='ready'?packet.summary:null};return {kind:'result',result:value,replayed:false};});await c.evaluate();assert.equal(c.getView().result!.state,'pending');revision=2;state='ready';await c.renew();assert.equal(c.getView().result!.resultRevision,2);assert.deepEqual(decisionCopy(c.getView().result!),{name:x.name,...expectedCopy.replacement});state='failed';assert.equal(await c.renew(),false,'Equal revision cannot change work state');assert.equal(c.getView().result,null);revision=3;await c.renew();assert.equal(c.getView().result!.state,'failed');c.invalidate();assert.equal(c.getView().result,null);c.close();},
 async L08(){const x=baseInput();let commits=0;const c=controller(x,positivePlan(),async(r,p)=>{if(r.operation==='save'){commits++;assert.equal(r.expectedBindingHash,sha256(canonicalJson(p.binding)));return {kind:'unavailable',reason:'changed_basis'};}return {kind:'result',result:p,replayed:false};});await c.evaluate();assert.equal(await c.save(),null);assert.equal(commits,1);assert.equal(c.getView().savedAssessmentId,null);assert.equal(c.getView().result,null);c.close();},
 async L09(){const x=baseInput(),c=controller(x,positivePlan());await c.evaluate();assert(Date.parse(c.getView().result!.validUntil)>Date.parse(x.now));c.setOnline(false);assert.equal(c.getView().result,null);assert.equal(c.getView().historical,null);assert.equal(await c.renew(),false);assert.equal(await c.save(),null);c.close();},
 async L10(){const x=comparator();const t=target(x);const request={operation:'evaluate' as const,requestId:x.binding.attemptId,...t.request};let calls=0;const ports:PartThreePorts={ownerId:x.context.ownerId,now:()=>x.now,normalize:async()=>x.partTwo,context:async()=>x.context,history:async()=>({items:[],nextCursor:null,atRevision:1}),identity:async()=>({name:x.name,expiresAt:x.partTwo.expiresAt}),worker:async(action,payload)=>{if(action==='encounter/read')return {skip:false,answered:false,exposedQuestionId:null,interacted:false};if(action==='prepare')return {resultId:x.resultId,resultRevision:1,leaseToken:p2id(248)};if(action==='provider/gate')return {allowed:true,callId:p2id(249),model:'jev-1.13.0',approvalId:'synthetic-approval',grants:['synthetic-grant']};if(action==='publish')return {kind:'result',result:payload.result,replayed:false};throw Error('Unexpected synthetic action');},provider:()=>({evaluate:async()=>{calls++;throw Error('Synthetic model failure');}})};
 const out=await handlePersonalRequest(request,ports);assert.equal(out.kind,'result');if(out.kind!=='result')return;const expected=goldenPacket(x,replacementPlan()),menu=eligibleMenuFor(expected.binding,expected.findings,null)!;const selection={selectedTradeoffId:null,selectedQuestionId:null,provider:'jev' as const,resolvedModel:null,usage:null,elapsedMs:0,contractVersion:'part-three-selection/v1' as const,outcome:'unavailable' as const};expected.refinementStatus='unavailable';expected.binding.refinement={candidateSetHash:menu.candidateSetHash,projectionVersion:PART_THREE_RELEASE.refinement.projection,promptVersion:PART_THREE_RELEASE.refinement.prompt,adapterVersion:PART_THREE_RELEASE.refinement.adapter,configuredModel:'jev-1.13.0',resolvedModel:null};expected.refinementTrace={callId:p2id(249),menu,originalQuestion:null,baselineTradeoffId:expected.selectedTradeoffId,selection,applied:false};assert.deepEqual(out.result,expected);assert.deepEqual(decisionCopy(out.result),{name:x.name,...expectedCopy.replacement});assert.deepEqual(out.result.findings.map(findingCopy),replacementCopies);assert.equal(calls,1);},
 async L11(){const x=comparator(baseInput(),'unanswered'),plan={...unknownPlan('purpose_or_site'),question:true};const c=controller(x,plan);await c.evaluate();const deciding=structuredClone(c.getView().result!.summary);c.exposeQuestion();const firstQuestion=structuredClone(c.getView().question);c.questionEvent('interact');await c.renew();assert.deepEqual(c.getView().question,firstQuestion);assert.deepEqual(c.getView().result!.summary,deciding);assert.deepEqual(c.getView().result!.findings,goldenPacket(x,plan).findings);c.close();
 // Refinement can be published before the interaction receipt, but arrive at this client after touch.
 // Both optional choices and the complete accepted trace are legitimate; publication timing cannot move visible content.
 const y=avoid(comparator());y.context.preferences[0].data.strength='prefer';
 const two:GoldPlan={...replacementPlan(),findings:[{...avoidancePlan(false).findings[0],consequence:'optional'},...replacementPlan().findings],primary:2,eligibleRules:['exact-avoidance','purpose-value','pair-comparison']};
 let refinement=false,saveCommits=0;const stable=controller(y,two,(req,packet)=>{if(req.operation==='save'){saveCommits++;return {kind:'saved',savedAssessmentId:p2id(254),resultRevision:2,replayed:false};}if(req.operation==='question_event')return {kind:'acknowledged'};if(refinement){const menu=eligibleMenuFor(packet.binding,packet.findings,null)!;const choice=packet.findings[1].id;packet.resultRevision=2;packet.refinementStatus='accepted';packet.selectedTradeoffId=choice;packet.binding.refinement={candidateSetHash:menu.candidateSetHash,projectionVersion:PART_THREE_RELEASE.refinement.projection,promptVersion:PART_THREE_RELEASE.refinement.prompt,adapterVersion:PART_THREE_RELEASE.refinement.adapter,configuredModel:PART_THREE_RELEASE.refinement.configuredModel,resolvedModel:PART_THREE_RELEASE.refinement.configuredModel};packet.refinementTrace={callId:p2id(251),menu,originalQuestion:null,baselineTradeoffId:packet.findings[0].id,selection:{selectedTradeoffId:choice,selectedQuestionId:null,provider:'jev',resolvedModel:PART_THREE_RELEASE.refinement.configuredModel,usage:{inputTokens:1,outputTokens:1},elapsedMs:1,contractVersion:'part-three-selection/v1',outcome:'accepted'},applied:true};assert(PersonalResultV2Schema.safeParse(packet).success,'Late fixture is a fully authorized accepted refinement');}return {kind:'result',result:packet,replayed:req.operation==='read'};});
 await stable.evaluate();const before=stable.getView().result!;const optionalCopy=findingCopy(before.findings.find(f=>f.id===before.selectedTradeoffId)!);stable.questionEvent('interact');refinement=true;await stable.renew();const after=stable.getView().result!;assert.deepEqual(after.summary,before.summary);assert.deepEqual(after.findings,before.findings);assert.equal(findingCopy(after.findings.find(f=>f.id===after.selectedTradeoffId)!),optionalCopy,'Optional visible content must not switch after touch or answer entry');assert.equal(await stable.save(),null,'A newer server revision cannot be substituted for the displayed exact packet');assert.equal(saveCommits,0,'Refused read must prevent the CAS save call');stable.allowOptionalRefresh();assert.equal(await stable.renew(),true);assert.equal(findingCopy(stable.getView().result!.findings.find(f=>f.id===stable.getView().result!.selectedTradeoffId)!),replacementCopies[0],'Only explicit optional refresh allows a changed visible selection');stable.close();},
 async L12(){const reading=evidence(baseInput(),fixtureFactories.sourceReading('Glycerin'));const limited:GoldPlan={...unknownPlan(),gaps:[['identity_or_use','missing','evidence'],['purpose_coverage','missing','reviewer']],scope:'source_reading'};const r=check(reading,limited,{label:'Not enough info',reason:'Product identity or intended use remains unresolved.',scope:'Photo reading · Product presence unconfirmed'},[]);const bound=comparator();bound.resultId=p2id(253);bound.binding.generation=reading.binding.generation+1;const b=check(bound,replacementPlan(),expectedCopy.replacement,replacementCopies);assert.equal(r.binding.subject.kind,'source_reading');assert.equal(b.binding.subject.kind,'declaration');assert.equal(r.summary!.namedDecision.itemId,null);assert.notEqual(r.binding.generation,b.binding.generation);const c=controller(reading,limited,(req,p)=>req.operation==='question_event'?{kind:'acknowledged'}:{kind:'result',result:req.operation==='evaluate'&&req.generation===bound.binding.generation?goldenPacket({...bound,binding:{...bound.binding,attemptId:req.requestId}},replacementPlan()):p,replayed:req.operation==='read'});await c.evaluate();assert.equal(c.getView().result!.binding.subject.kind,'source_reading');c.bind(target(bound));assert.equal(c.getView().result,null);await c.evaluate();assert.equal(c.getView().result!.binding.subject.kind,'declaration');assert.notEqual(c.getView().result!.resultId,r.resultId);assert.equal(r.binding.subject.kind,'source_reading','Original reading packet retains its source-only authority');c.close();},
 L13(){const x=recalled(baseInput());check(x,reactionPlan(x),expectedCopy.reaction,[expectedCopy.reaction.reason,expectedCopy.positive.reason]);x.context.experiences=[];x.history.activeRevisionIds=[];x.selectedManualReportIds=[];x.context.revision++;x.history.atRevision=x.context.revision;const r=check(x,positivePlan(),expectedCopy.positive,[expectedCopy.positive.reason]);assert(!JSON.stringify(r).includes(A.reportRecord));assert.deepEqual(r.findings[0].dependencies.contextRevisionIds,[A.profile]);},
 L14(){const x=baseInput();x.context.experiences=[p3revision(A.report,{id:A.reportRecord,reference:{kind:'manual',name:'Other glycerin product'},kind:'reacted',occurred:{start:{state:'unanswered'},end:{state:'unanswered'}},useContext:null,symptoms:['Stinging'],note:null})];x.history.activeRevisionIds=[A.report];check(x,positivePlan(),expectedCopy.positive,[expectedCopy.positive.reason]);assert.equal(x.selectedManualReportIds.length,0);},
 async U02(){const x=evidence(baseInput(),fixtureFactories.boundDeclaration('Unknown label term','public'));const r=check(x,unknownPlan(),expectedCopy.unknown,[]);let saved=false;const c=controller(x,unknownPlan(),async(req,packet)=>req.operation==='save'?(saved=true,{kind:'saved',savedAssessmentId:p2id(250),resultRevision:1,replayed:false}):{kind:'result',result:packet,replayed:false});await c.evaluate();assert.equal(await c.save(),p2id(250));assert(saved);assert.equal(r.summary!.judgment,'not_enough_info');c.close();},
};
const gates:Partial<Record<AcceptanceId,string>>={C10:'Actual atomic setup retry/concurrent clients require parent-owned local Auth/SQL/live-route validation.',Q05:'Purposeful visible compare steps and stop require mounted/native usability evidence; no native execution in this scope.',Q06:'No durable Part3 profile/routine question-answer path is implemented; CAS/draft/prior-saved-result must be verified when that path exists.',L06:'Physical historical payload/prose/enum/cache erasure after save requires parent-owned SQL/live-client validation.',U01:'Actual large text/long names/VoiceOver/no-color and independent first-card comprehension require native/user review.'};
for(const [id,given] of acceptanceCases)test(`${id}: ${given}`,{skip:gates[id]},async()=>{assert(cases[id],`No local implementation or honest gate for ${id}`);await cases[id]!();});
test('acceptance corpus contains all44 distinct exact Givens and each has a local assertion or explicit gate',()=>{assert.equal(acceptanceCases.length,44);assert.equal(new Set(acceptanceCases.map(c=>c[0])).size,44);for(const [id] of acceptanceCases)assert(Boolean(cases[id])!==Boolean(gates[id]),id);});
