import test from 'node:test';
import assert from 'node:assert/strict';
import {createSetupDraftStore,SETUP_DRAFT_KEY,SETUP_DRAFT_TTL} from '../src/presentation/p0b-personalization/setupDraftStorage.ts';
import {createContextDraft} from '../src/presentation/p0b-personalization/draft.ts';
import {createSetupBundle} from '../src/presentation/p0b-personalization/setup.ts';
const owner={ownerId:'owner',accountGeneration:123};
function fixture(){let account:typeof owner|null=owner,now=1000;const values=new Map<string,string>();const storage={getItem:async(k:string)=>values.get(k)??null,setItem:async(k:string,v:string)=>{values.set(k,v);},removeItem:async(k:string)=>{values.delete(k);}};return {values,storage,account:(a:typeof owner|null)=>{account=a;},time:(n:number)=>{now=n;},store:createSetupDraftStore(storage,()=>account,()=>now)};}
const draft=()=>({draft:{...createContextDraft(),primaryGoal:{state:'answered' as const,value:'dryness' as const}},bundle:createSetupBundle(owner.ownerId),step:2});
test('draft cold read is owner/session/revision bound and has seven day expiry',async()=>{const f=fixture();f.store.schedule(owner,0,draft());await f.store.flush();assert.equal((await f.store.read(owner,0))?.step,2);f.account({...owner,accountGeneration:124});assert.equal(await f.store.read({...owner,accountGeneration:124},0),null);f.account(owner);assert.equal(f.values.size,0);f.store.schedule(owner,0,draft());await f.store.flush();f.time(1000+SETUP_DRAFT_TTL);assert.equal(await f.store.read(owner,0),null);assert.equal(f.values.size,0);});
test('completion/retirement cancels debounce and in-flight writes; another owner cannot recover',async()=>{const f=fixture();f.store.schedule(owner,0,draft());await f.store.clear();await f.store.flush();assert.equal(f.values.size,0);let release!:()=>void;const blocked={...f.storage,setItem:async(k:string,v:string)=>{await new Promise<void>(r=>release=r);await f.storage.setItem(k,v);}};const store=createSetupDraftStore(blocked,()=>owner,()=>1000);store.schedule(owner,0,draft());const writing=store.flush();await Promise.resolve();await Promise.resolve();const clearing=store.clear();release();await writing;await clearing;assert.equal(f.values.size,0);});
test('corrupt, oversized, expired, foreign and stale-revision records are discarded without throwing',async()=>{const f=fixture();for(const value of ['bad',JSON.stringify({schemaVersion:1}),'x'.repeat(65537)]){f.values.set(SETUP_DRAFT_KEY,value);assert.equal(await f.store.read(owner,0),null);assert.equal(f.values.size,0);}f.store.schedule(owner,0,draft());await f.store.flush();assert.equal(await f.store.read(owner,1),null);f.account(null);assert.equal(await f.store.read(owner,0),null);});
test('projection excludes secrets/photos/notes/medical answers and query text',async()=>{const f=fixture();const d=draft();d.bundle.additionalNote='excluded';d.draft.sensitivities={state:'answered',value:['excluded']};f.store.schedule(owner,0,d);await f.store.flush();const bytes=f.values.get(SETUP_DRAFT_KEY)!;assert.ok(!bytes.includes('excluded'));const read=await f.store.read(owner,0);assert.deepEqual(read?.draft.sensitivities,{state:'unanswered'});assert.equal(read?.bundle.additionalNote,null);});
test('owner change during a storage read prevents delivery; retirement removes the old namespace',async()=>{const f=fixture();f.store.schedule(owner,0,draft());await f.store.flush();let release!:()=>void;let started!:()=>void;const begun=new Promise<void>(r=>started=r);let account:typeof owner|null=owner;const store=createSetupDraftStore({...f.storage,getItem:async k=>{started();await new Promise<void>(r=>release=r);return f.storage.getItem(k);}},()=>account,()=>1000);const reading=store.read(owner,0);await begun;account={ownerId:'other',accountGeneration:1};const cleared=store.clear();release();assert.equal(await reading,null);await cleared;assert.equal(f.values.size,0);});
test('storage failures are reported to the host and cannot return a draft',async()=>{const store=createSetupDraftStore({getItem:async()=>{throw Error('unavailable');},setItem:async()=>{throw Error('unavailable');},removeItem:async()=>{}},()=>owner);await assert.rejects(store.read(owner,0),/unavailable/);store.schedule(owner,0,draft());await assert.rejects(store.flush(),/unavailable/);await store.clear();});
