import assert from 'node:assert/strict';
import { createContextDraft } from '../src/presentation/p0b-personalization/draft.ts';
import { profileToStorage, profileFromStorage } from '../src/presentation/p0b-personalization/storageAdapter.ts';
import { componentHarness, control, press } from './ux-profile-render.ts';
const file = 'src/components/p0b-personalization/ContextFlow.tsx';
let applied: ReturnType<typeof createContextDraft> | null = null;
let exited = 0;
const harness = componentHarness(file, 'ContextFlow', { onApply: (draft: any) => { applied = draft; }, onSkip: () => { exited++; } });
let nodes = harness.render();
assert.ok(!nodes.some(node => node.props.label === 'Hide additional goals'), 'Additional goals should start collapsed');
assert.ok(nodes.some(node => node.props.label === 'Add other goals'), 'The secondary goal list must be disclosed on request');
press(control(nodes, 'Add other goals'));
nodes = harness.render();
assert.ok(nodes.some(node => node.props.label === 'Hide additional goals'));
press(control(nodes, 'Dryness'));
nodes = harness.render();
assert.equal(control(nodes, 'Dryness').props.selectionType, 'single');
press(control(nodes, 'Continue'));
nodes = harness.render();
assert.ok(nodes.some(node => node.props.label === 'How does your skin usually feel?'));
press(control(nodes, 'Dry or tight'));
nodes = harness.render();
press(control(nodes, 'Save skin profile'));
assert.ok(applied);
const saved = profileToStorage(applied!);
assert.equal(saved.primaryGoal, 'dryness');
assert.equal(saved.skinBehavior, 'dry_tight');
assert.equal(saved.reactivity, 'unanswered', 'Blank reactivity must not become tolerance or unsure');
assert.equal(saved.intent, 'unanswered', 'Goal selection must not invent intent');
assert.deepEqual(saved.secondaryGoals, [], 'Disclosing choices must not select goals');
press(control(harness.render(), 'Skip'));
assert.equal(exited, 0, 'Step Skip applies the retained draft instead of exiting');
const edit = createContextDraft(); edit.primaryGoal = { state: 'answered', value: 'maintain' }; edit.secondaryGoals = ['simplify'];
const editHarness = componentHarness(file, 'ContextFlow', { initialDraft: edit, onApply() {}, onSkip() {} });
assert.ok(editHarness.render().some(node => node.props.label === 'Hide additional goals'), 'Existing other goals remain discoverable during editing');
const states = ['unanswered', 'unsure', 'withheld'] as const;
for (const state of states) {
  const draft = createContextDraft(); draft.treatments = { state }; draft.sensitivities = { state };
  const roundTrip = profileFromStorage(profileToStorage(draft));
  assert.equal(roundTrip.treatments.state, state); assert.equal(roundTrip.sensitivities.state, state);
}
console.log('UX profile main priority, disclosure and unknown-state behavior passed');
const editSaved = { drafts: [] as ReturnType<typeof createContextDraft>[] };
const returning = componentHarness(file, 'ContextFlow', { initialDraft: edit, onApply: (value: any) => editSaved.drafts.push(value), onSkip() {} });
let editingNodes = returning.render();
assert.ok(editingNodes.some(node => node.props.label === 'Save skin profile'), 'Returning users can save a relevant correction without replaying setup');
press(control(editingNodes, 'Dryness'));
editingNodes = returning.render();
press(control(editingNodes, 'Save skin profile'));
assert.equal(editSaved.drafts[0].primaryGoal.state, 'answered');
assert.equal(editSaved.drafts[0].primaryGoal.state === 'answered' && editSaved.drafts[0].primaryGoal.value, 'dryness');
assert.deepEqual(editSaved.drafts[0].secondaryGoals, ['simplify']);
