import {ScientificClaimSchema,ClaimAdmissionSchema,type ScientificClaim} from '../../contracts/ScientificClaim.ts';
import {evidenceReview} from '../../contracts/EvidenceReview.ts';
import {scientificClaimHash,claimSourcePin} from './claimApplicability.ts';
import {buildScientificManifest,PENDING_SCIENTIFIC_MANIFEST} from './scientificDecision.ts';
import {REVIEWED_AHA_CLAIM,REVIEWED_AHA_ADMISSION} from './reviewedAha.ts';
export const BARRIER_REFERENCE_ID='G01-03-reviewed-barrier-reference-v1';
export const PHOTOAGING_REFERENCE_ID='G03-03-reviewed-photoaging-reference-v1';
const prior=(id:string)=>structuredClone(PENDING_SCIENTIFIC_MANIFEST.claims.find(c=>c.id===id)!);
const barrier=prior('G01-02');
export const REVIEWED_BARRIER_REFERENCE=ScientificClaimSchema.parse({...barrier,id:BARRIER_REFERENCE_ID,tier:'reference',scope:'ingredient_reference',copy:{reason:'In a small study of niacinamide-containing formulations, researchers reported changes in barrier-related measurements on healthy forearms after twice-daily use for 28 days. This is ingredient research, not a test of this product.',action:null,qualifications:['20 healthy volunteers; no numerical effect size is verified here.','Concentration and vehicle are unresolved; this does not predict finished-product benefit or relief of current irritation.']}});
const photo=prior('G03-01');
export const REVIEWED_PHOTOAGING_REFERENCE=ScientificClaimSchema.parse({...photo,id:PHOTOAGING_REFERENCE_ID,tier:'reference',scope:'ingredient_reference',applicability:[{field:'ingredientId',expected:['niacinamide'],reason:'Require current clear unconditional exact niacinamide identity; study metadata is not current dose.'},{field:'endpoint',expected:['fine-lines-wrinkles','hyperpigmented-spots'],reason:'Only the corresponding explicitly reported goal receives this research context; no texture or generic redness transfer.'}],copy:{reason:'One study of 5% niacinamide used twice daily for 12 weeks reported improvements in selected facial photoaging signs. The study did not test this product.',action:null,qualifications:['50 women with facial photoaging; fine lines and hyperpigmented spots are specific studied endpoints, not all texture or redness concerns.','Effect magnitudes, detailed vehicle and application mass are unverified here; study percentage/regimen is metadata, not your product dose or a direction to increase use.','Current dose, formula and population transfer are not established; there is no finished-product efficacy or superiority finding.']}});
function admission(claim:ScientificClaim){
 const claimHash=scientificClaimHash(claim),sourcePins=claim.sourceRefs.map(claimSourcePin);
 const review=evidenceReview({version:'evidence-review/v1',claimHash,sourcePins,mode:'automated_source_review',reviewer:{id:'codex-source-review:held-usefulness-20261004',kind:'agent',credentialEvidenceRef:null},checkedAt:'2026-10-04T12:00:05.000Z',decision:'approved',limits:['Held independent source checks from mvp-evidence-review/review-records.json dated2026-10-04T05:19:40Z directly recovered these abstracts. No new retrieval or raw body/hash is asserted.','New scoped original factual paraphrase; no raw abstract, manufacturer acquisition, professional credential or hosted activation.','Reference only; actual ingredient/goal/context/source applicability must be checked separately.']});
 return ClaimAdmissionSchema.parse({claimId:claim.id,claimHash,status:'approved',reviewerId:review.reviewer.id,qualificationRef:review.contentHash,reviewedAt:review.checkedAt,sourcePins,review,rights:{grantId:'task-authorized-local-original-research-facts',version:'held-barrier-photoaging-original-copy/v1',process:true,store:true,display:true,export:true,validUntil:'2026-12-31T00:00:00.000Z',revoked:false},validUntil:'2026-12-31T00:00:00.000Z'});
}
export const REVIEWED_USEFULNESS_MANIFEST=buildScientificManifest([...PENDING_SCIENTIFIC_MANIFEST.claims,REVIEWED_AHA_CLAIM,REVIEWED_BARRIER_REFERENCE,REVIEWED_PHOTOAGING_REFERENCE],[REVIEWED_AHA_ADMISSION,admission(REVIEWED_BARRIER_REFERENCE),admission(REVIEWED_PHOTOAGING_REFERENCE)]);
