import { z } from 'zod';
import { canonicalJson,sha256 } from '../part-two/hash.ts';
const id=z.string().min(1).max(200),option=z.strictObject({id,description:z.string().min(1).max(300)});
export const EligibleMenuSchema=z.strictObject({candidateSetId:id,candidateSetHash:id,jobs:z.array(z.strictObject({id:z.enum(['prioritize_tradeoff','select_question']),options:z.array(option).min(2).max(9)})).min(1).max(2),compatiblePairs:z.array(z.tuple([id.nullable(),id.nullable()])).max(45)}).superRefine((m,c)=>{if(new Set(m.jobs.map(j=>j.id)).size!==m.jobs.length)c.addIssue({code:'custom',message:'Duplicate jobs'});for(const j of m.jobs){if(new Set(j.options.map(o=>o.id)).size!==j.options.length||!j.options.some(o=>o.id==='none')||j.id==='select_question'&&j.options.length>5)c.addIssue({code:'custom',message:'Invalid closed menu'});}const {candidateSetHash,...rest}=m;if(candidateSetHash!==sha256(canonicalJson(rest)))c.addIssue({code:'custom',message:'Menu hash mismatch'});});
export type EligibleMenu=z.infer<typeof EligibleMenuSchema>;
export const AuthorizedProjectionSchema=z.strictObject({version:z.literal('part-three-provider-projection/v1'),purpose:z.literal('optional_content_selection'),approvalId:id,fields:z.array(z.strictObject({id,value:z.enum(['add','replace','check_current','unknown','main','additional','same_purpose','different_purpose','same_site','different_site','helpful','mixed','not_helping']),externalOperationGrant:id,sourceFieldId:id})).max(20)});
export type AuthorizedProjection=z.infer<typeof AuthorizedProjectionSchema>;
export interface NormalizedSelection {selectedTradeoffId:string|null;selectedQuestionId:string|null;provider:string;resolvedModel:string|null;usage:{inputTokens:number;outputTokens:number}|null;elapsedMs:number;contractVersion:'part-three-selection/v1';outcome:'accepted'|'abstained'|'invalid'|'timeout'|'unavailable'|'disallowed'}
export interface DecisionProvider {evaluate(projection:AuthorizedProjection,menu:EligibleMenu,signal:AbortSignal,deadline:number):Promise<NormalizedSelection>}
export interface JevTransport {send(request:{model:string;state:unknown;questions:Record<string,{type:'choice';instructions:string;criteria:Record<string,string>}>},signal:AbortSignal,deadline:number):Promise<string>}
export const JEV_PROTOCOL=Object.freeze({version:'jev-choice-v1',sumEpsilon:0.000001,tieEpsilon:0.000001,confidenceEpsilon:0.000001,inputTokenCap:2000,responseBytes:32768,totalDeadlineMs:1500,maxAttempts:1});
const probability=z.number().finite().min(0).max(1);
const NativeResponseSchema=z.strictObject({model:id,answers:z.record(id,z.strictObject({type:z.literal('choice'),choice:id,probabilities:z.record(id,probability),confidence:probability})),usage:z.strictObject({input_tokens:z.number().int().min(0).max(2000),output_tokens:z.number().int().min(0).max(32768)})});
/** JSON.parse erases duplicate object keys. This bounded parser rejects them
 * before interpreting the provider's option distribution or job map. */
export function parseUniqueJson(text:string):unknown {
 let p=0;const ws=()=>{while(/\s/.test(text[p]??'')&&p<text.length)p++;};
 const string=()=>{const start=p++;let escaped=false;for(;p<text.length;p++){const c=text[p];if(c==='"'&&!escaped){p++;return JSON.parse(text.slice(start,p)) as string;}if(c==='\\'&&!escaped)escaped=true;else escaped=false;}throw Error('Invalid JSON');};
 const value=(depth:number):unknown=>{if(depth>16)throw Error('JSON depth');ws();if(text[p]==='"')return string();if(text[p]==='{'){p++;ws();const obj:Record<string,unknown>=Object.create(null),keys=new Set<string>();if(text[p]==='}'){p++;return obj;}while(p<text.length){ws();if(text[p]!=='"')throw Error('JSON key');const key=string();if(keys.has(key))throw Error('Duplicate JSON key');keys.add(key);ws();if(text[p++]!==':')throw Error('JSON colon');obj[key]=value(depth+1);ws();const next=text[p++];if(next==='}')return obj;if(next!==',')throw Error('JSON separator');}throw Error('JSON object');}if(text[p]==='['){p++;ws();const values:unknown[]=[];if(text[p]===']'){p++;return values;}while(p<text.length){values.push(value(depth+1));ws();const next=text[p++];if(next===']')return values;if(next!==',')throw Error('JSON separator');}throw Error('JSON array');}const match=/^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/.exec(text.slice(p));if(!match)throw Error('JSON value');p+=match[0].length;return JSON.parse(match[0]);};
 const result=value(0);ws();if(p!==text.length)throw Error('Trailing JSON');return result;
}
export function createJevProvider(transport:JevTransport,configuredModel:string,now=Date.now):DecisionProvider {
 if(!/^jev-\d+\.\d+\.\d+$/.test(configuredModel))throw Error('Jev requires pinned model');
 return {async evaluate(rawProjection,rawMenu,signal,deadline){const start=now();const failure=(outcome:NormalizedSelection['outcome']):NormalizedSelection=>({selectedTradeoffId:null,selectedQuestionId:null,provider:'jev',resolvedModel:null,usage:null,elapsedMs:Math.max(0,now()-start),contractVersion:'part-three-selection/v1',outcome});
  const projected=AuthorizedProjectionSchema.safeParse(rawProjection),parsed=EligibleMenuSchema.safeParse(rawMenu);if(!projected.success||!parsed.success)return failure('disallowed');const projection=projected.data,menu=parsed.data;
  const maps=new Map<string,Map<string,string>>(),questions:Record<string,{type:'choice';instructions:string;criteria:Record<string,string>}>=Object.create(null);
  for(const job of menu.jobs){const options=new Map<string,string>();job.options.forEach((o,i)=>options.set(`o${String(i).padStart(3,'0')}`,o.id));maps.set(job.id,options);questions[job.id]={type:'choice',instructions:job.id==='select_question'?'Select one useful eligible optional question, or none. Do not infer new facts.':'Select one useful supported optional tradeoff, or none. Do not decide the judgment.',criteria:Object.fromEntries(job.options.map((o,i)=>[`o${String(i).padStart(3,'0')}`,o.description]))};}
  // Authority IDs, grants and baseline selection stay in the host. Derived enums
  // still require individual external-processing grants before composition.
  const request={model:configuredModel,state:{version:projection.version,fields:projection.fields.map(f=>({id:f.id,value:f.value}))},questions};
  if(new TextEncoder().encode(JSON.stringify(request)).byteLength>JEV_PROTOCOL.inputTokenCap)return failure('disallowed');
  const end=Math.min(deadline,start+JEV_PROTOCOL.totalDeadlineMs);if(signal.aborted||end<=now())return failure('timeout');
  const abort=new AbortController();let timer:ReturnType<typeof setTimeout>|null=null;const onAbort=()=>abort.abort();signal.addEventListener('abort',onAbort,{once:true});
  let rejectAbort:()=>void=()=>{};const cancelled=new Promise<never>((_,reject)=>{rejectAbort=()=>reject(Error('Deadline'));abort.signal.addEventListener('abort',rejectAbort,{once:true});});timer=setTimeout(()=>abort.abort(),Math.max(1,end-now()));
  try{const text=await Promise.race([transport.send(request,abort.signal,end),cancelled]);if(signal.aborted||abort.signal.aborted||now()>=end)return failure('timeout');if(new TextEncoder().encode(text).byteLength>JEV_PROTOCOL.responseBytes)return failure('invalid');
   let response:z.infer<typeof NativeResponseSchema>;try{response=NativeResponseSchema.parse(parseUniqueJson(text));}catch{return failure('invalid');}if(response.model!==configuredModel||Object.keys(response.answers).sort().join('|')!==menu.jobs.map(j=>j.id).sort().join('|'))return failure('invalid');
   const selected:Record<string,string|null>=Object.create(null);
   for(const job of menu.jobs){const answer=response.answers[job.id],map=maps.get(job.id)!;if(!map.has(answer.choice)||Object.keys(answer.probabilities).sort().join('|')!==[...map.keys()].sort().join('|'))return failure('invalid');
    const values=Object.values(answer.probabilities),sum=values.reduce((a,b)=>a+b,0),max=Math.max(...values),confidence=(max-1/values.length)/(1-1/values.length);
    if(Math.abs(sum-1)>JEV_PROTOCOL.sumEpsilon||max-answer.probabilities[answer.choice]>JEV_PROTOCOL.tieEpsilon||Math.abs(confidence-answer.confidence)>JEV_PROTOCOL.confidenceEpsilon)return failure('invalid');const chosen=map.get(answer.choice)!;selected[job.id]=chosen==='none'?null:chosen;
   }
   const trade=selected.prioritize_tradeoff??null,question=selected.select_question??null;if(menu.compatiblePairs.length&&!menu.compatiblePairs.some(([t,q])=>t===trade&&q===question))return failure('invalid');
   return {selectedTradeoffId:trade,selectedQuestionId:question,provider:'jev',resolvedModel:response.model,usage:{inputTokens:response.usage.input_tokens,outputTokens:response.usage.output_tokens},elapsedMs:Math.max(0,now()-start),contractVersion:'part-three-selection/v1',outcome:trade===null&&question===null?'abstained':'accepted'};
  }catch{return failure(abort.signal.aborted||signal.aborted||now()>=end?'timeout':'unavailable');}finally{if(timer)clearTimeout(timer);signal.removeEventListener('abort',onAbort);abort.signal.removeEventListener('abort',rejectAbort);}
 }};
}
/** One bounded HTTP attempt. Credentials live only in server composition.
 * No logger, SDK retry, body logging or Retry-After extension exists here. */
export function createJevHttpTransport(fetcher:typeof fetch,credential:()=>string|null,now=Date.now):JevTransport{return {async send(request,signal,deadline){const key=credential();if(!key||signal.aborted||now()>=deadline)throw Error('Unavailable');const response=await fetcher('https://api.typesafe.ai/v1/systemone',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify(request),signal,redirect:'error'});if(!response.ok||signal.aborted||now()>=deadline)throw Error('Unavailable');const length=response.headers.get('content-length');if(length&&Number(length)>JEV_PROTOCOL.responseBytes)throw Error('Response limit');if(!response.body)throw Error('Response unavailable');const reader=response.body.getReader();let bytes=0;const chunks:Uint8Array[]=[];try{for(;;){if(signal.aborted||now()>=deadline)throw Error('Deadline');const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>JEV_PROTOCOL.responseBytes)throw Error('Response limit');chunks.push(value);}const all=new Uint8Array(bytes);let offset=0;for(const chunk of chunks){all.set(chunk,offset);offset+=chunk.byteLength;}return new TextDecoder('utf-8',{fatal:true}).decode(all);}finally{await reader.cancel().catch(()=>{});}}};}
