import {z} from 'zod';
// This leaf contract is an isolated education proposal. It does not extend any
// deployed release, formula parser, source permission or personalized rule.
const id=z.string().min(1).max(200),text=z.string().min(1).max(4000),digest=z.string().regex(/^[a-f0-9]{64}$/),date=z.iso.datetime({offset:true});
export const Candidate423AliasProposalSchema=z.strictObject({name:text,qualifier:text,source_id:id});
export const Candidate423EditorialSchema=z.strictObject({caution:text.nullable(),amountAndUse:text.nullable(),aliasNotes:text.nullable(),distinctIngredients:text.nullable(),qualifications:z.array(text).max(10),copySha256:digest,documentId:id,libraryFileId:id,libraryVersion:z.number().int().nonnegative(),documentSha256:digest});
export const Candidate423CardSchema=z.strictObject({ingredientId:id,name:text,aliases:z.array(text).max(12),short:text,label:text,body:text,detail:text.nullable(),evidence:text.nullable(),sourceIds:z.array(id).min(1).max(100),version:id,editorial:Candidate423EditorialSchema,proposedAliases:z.array(Candidate423AliasProposalSchema).max(20).optional(),sourceClaimScopes:z.array(z.record(z.string(),z.unknown())).max(20).optional(),rawRecordId:id.optional(),contributionKind:z.literal('unknown').optional(),exactProductConcentration:z.null().optional()});
export const Candidate423SourceSchema=z.strictObject({id,title:text,url:z.url(),reviewedAt:date.nullable(),kind:z.literal('approved_editorial'),editorial:z.strictObject({metadataSha256:digest,copyApprovedAt:date.nullable(),copyApprovalMessageId:id.optional(),rights:z.literal('not_promoted'),remoteBodySnapshot:z.literal('unavailable'),readDateMeaning:z.literal('archived_read_metadata_not_new_review').optional()})});
const context=z.strictObject({documentId:id,sections:z.array(z.strictObject({heading:text,paragraphs:z.array(z.strictObject({text:z.string().max(4000),links:z.array(z.strictObject({label:text,url:z.url()})).max(20)})).max(100)})).max(20),researchTable:z.strictObject({rows:z.array(z.array(z.string().max(4000)).max(10)).max(50)}).nullable()});
export const Candidate423ReleaseSchema=z.strictObject({version:id,releaseGate:z.literal('isolated_local_candidate'),contentHash:digest,cards:z.array(Candidate423CardSchema).length(423),sources:z.array(Candidate423SourceSchema).max(1000),educationContext:z.array(context).length(3),contributionKinds:z.record(id,z.enum(['benefit','support','unknown'])),provenance:z.strictObject({inherited47:z.strictObject({version:id,contentHash:digest}),historical37:z.strictObject({version:id,contentHash:digest}),expansionSourcePackage:z.strictObject({libraryFileId:id,libraryVersion:z.literal(0),fileId:id,sha256:digest}),expansionDocument:z.strictObject({documentId:id,libraryFileId:id,libraryVersion:z.literal(0),libraryIdentityScope:z.literal('containing_source_pack'),documentSha256:digest,filename:text}),copyApproval:z.strictObject({messageId:id,approvedAtUtc:z.null(),scope:text,sourceArchivePendingFieldsUnchanged:z.literal(true)}),expiresAt:date.nullable(),revoked:z.boolean()})}).superRefine((release,ctx)=>{
 const issue=(message:string)=>ctx.addIssue({code:'custom',message});
 if(new Set(release.cards.map(card=>card.ingredientId)).size!==release.cards.length)issue('Duplicate ingredient identity');
 if(new Set(release.sources.map(source=>source.id)).size!==release.sources.length)issue('Duplicate source identity');
 const sourceIds=new Set(release.sources.map(source=>source.id)),cardIds=new Set(release.cards.map(card=>card.ingredientId));
 for(const card of release.cards){if(card.version!==release.version||card.sourceIds.some(id=>!sourceIds.has(id)))issue('Card version or source mismatch');if(card.rawRecordId&&(card.aliases.length||card.contributionKind!=='unknown'||release.contributionKinds[card.ingredientId]!=='unknown'))issue('New card promoted aliases or contribution claims');}
 if(Object.keys(release.contributionKinds).some(id=>!cardIds.has(id))||release.cards.some(card=>!(card.ingredientId in release.contributionKinds)))issue('Contribution identity mismatch');
});
export type Candidate423Release=z.infer<typeof Candidate423ReleaseSchema>;
export type Candidate423Card=z.infer<typeof Candidate423CardSchema>;
export const Candidate423LookupSchema=z.strictObject({literalName:text,mapping:z.strictObject({state:z.enum(['known','unknown','ambiguous']),ingredientId:id.nullable()})});
export const Candidate423SelectionSchema=z.strictObject({explicitLocal423:z.literal(true),expectedReleaseHash:digest,now:date,withdrawnDependencies:z.array(id).max(2000).optional()});
