import { z } from 'zod';
import { PartTwoOccurrenceSchema, PartTwoSourceRefSchema, PartTwoVersionsSchema, PartTwoBindingSchema, PartTwoFactSchema } from './PartTwo.ts';
const id = z.string().min(1).max(200);
const text = z.string().min(1).max(4000);
const refs = z.array(id).max(1000);
export const PartFourSourceSchema = z.strictObject({ id, title: text, url: z.url(), reviewedAt: z.iso.datetime(), kind: z.enum(['approved_editorial', 'formula', 'offer', 'review']) });
export const IngredientKnowledgeCardSchema = z.strictObject({ ingredientId: id, name: text, aliases: z.array(text).max(12), short: text, label: text, body: text, detail: text, evidence: text, sourceIds: refs, version: id });
export type IngredientKnowledgeCard = z.infer<typeof IngredientKnowledgeCardSchema>;
export const FormulaIngredientSchema = z.strictObject({ occurrenceId: id, occurrence: PartTwoOccurrenceSchema, observedName: text, ingredientId: id.nullable(), card: IngredientKnowledgeCardSchema.nullable(), modality: z.enum(['unconditional','may_contain','alternative','unresolved']), quantityText: text.nullable() });
export const FormulaAnalysisSchema = z.strictObject({ version: z.literal('formula-analysis/v1'), knowledgeVersion: id, knowledgeHash: z.string().regex(/^[a-f0-9]{64}$/), partTwoBindingKey: id, partTwoRevision: z.number().int().nonnegative(), dependencyDigest: id, binding: PartTwoBindingSchema, versions: PartTwoVersionsSchema, sourceRefs: z.array(PartTwoSourceRefSchema).max(1000), facts: z.array(PartTwoFactSchema).max(10000), expiresAt: z.iso.datetime(), scope: z.enum(['public','private_package']), evidenceState: z.enum(['partial','uncertain','accepted','conflict','blocked']), ingredients: z.array(FormulaIngredientSchema).max(1000), sources: z.array(PartFourSourceSchema).max(100), limitations: z.array(text).max(30) });
export type FormulaAnalysis = z.infer<typeof FormulaAnalysisSchema>;
export const PartFourInsightSchema = z.strictObject({ id, ruleId: z.enum(['F01','F02','F03','F04','F05','F06','F07','F08','F09','F10']), state: z.enum(['supported','limited','unknown','conflict','inapplicable']), title: text, explanation: text, action: text.nullable(), contextRevisionIds: refs, factIds: refs, occurrenceIds: refs, sourceIds: refs });
export type PartFourInsight = z.infer<typeof PartFourInsightSchema>;
export const PartFourComparisonSchema = z.strictObject({ state: z.enum(['selected','ambiguous','none','self','unavailable']), routineItemId: id.nullable(), explanation: text, candidateIds: refs });
export type PartFourComparison = z.infer<typeof PartFourComparisonSchema>;
export const ResearchBriefSourceSchema=z.strictObject({id,title:text,url:z.url(),kind:z.enum(['personal_anecdote','editorial','manufacturer']),retrievedAt:z.iso.datetime(),publishedAt:z.iso.datetime().nullable(),matching:z.enum(['exact_variant','exact_formula']),productId:id,variantId:id,formulaVersionId:id.nullable(),coverageLimit:text,permission:z.strictObject({grantId:id,version:id,process:z.literal(true),store:z.literal(true),display:z.literal(true),export:z.literal(true),validUntil:z.iso.datetime(),revoked:z.literal(false)})});
export const ProductResearchBriefSchema=z.strictObject({version:z.literal('product-research-brief/v1'),revision:id,contentHash:z.string().regex(/^[a-f0-9]{64}$/),productId:id,variantId:id,formulaVersionId:id.nullable(),observations:z.array(z.strictObject({id,text:text.max(600),kind:z.enum(['reported_experience','editorial_observation']),scope:z.enum(['feel_context','formula_context']),sourceIds:refs,opposingSourceIds:refs})).min(1).max(2),sources:z.array(ResearchBriefSourceSchema).min(1).max(8),coverageLimit:text,reviewDecision:z.enum(['approved_local_fixture','approved_source_brief']),reviewedAt:z.iso.datetime(),reviewerId:id,validUntil:z.iso.datetime()});
export type ProductResearchBrief=z.infer<typeof ProductResearchBriefSchema>;
export type ResearchBriefSource=z.infer<typeof ResearchBriefSourceSchema>;
const section = z.strictObject({ state: z.enum(['pending','unavailable','ready','conflict']), explanation: text, sourceIds: refs });
export const PartFourPacketSchema = z.strictObject({ version: z.literal('part-four-foundations/v1'), releaseId: id, formula: FormulaAnalysisSchema, insights: z.array(PartFourInsightSchema).max(100), comparison: PartFourComparisonSchema, reviews: section.extend({evidenceKind:z.literal('limited_research_brief').optional(),brief:ProductResearchBriefSchema.optional()}).superRefine((value,ctx)=>{if(value.state==='ready'&&(!value.brief||value.evidenceKind!=='limited_research_brief'))ctx.addIssue({code:'custom',path:['brief'],message:'A ready report section requires its reviewed brief'});if(value.brief&&value.state!=='ready')ctx.addIssue({code:'custom',path:['brief'],message:'Unavailable sections cannot carry protected brief bytes'});}), value: section, requiredEvidence: z.array(z.enum(['G01','G02','G03','G04','G05'])).max(5), decisionState: z.enum(['supported','pending','unavailable','conflict']), action: text, contextRevision: z.number().int().nonnegative() });
export type PartFourPacket = z.infer<typeof PartFourPacketSchema>;
/** Raw notes are intentionally absent. These structured fields are optional additions,
 * retaining old profile revisions without silently assigning a preference. */
export type TexturePreference = 'lightweight' | 'rich' | 'no_preference';
export interface SpendingPreference { currency: string; scope: 'per_product' | 'routine'; amountMinor: number; period: 'purchase' | 'month' }
