import { z } from 'zod';
import { quantityValidationIssue } from '../domain/part-two/quantities.ts';
import { canonicalJson, sha256 } from '../domain/part-two/hash.ts';
import { DeclarationSchema, FactBundleV1Schema, PackageConfirmationSchema } from './PartOne.ts';

const id = z.string().min(1).max(200);
const rev = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);
const date = z.iso.datetime({ offset: false });
const digest = z.string().regex(/^[a-f0-9]{64}$/);
const texts = z.array(z.string().max(500)).max(1000);
export const PartTwoSpanSchema = z.strictObject({ observationId: id, sourceRevision: rev, sectionId: id, entryId: id.nullable(), start: rev, end: rev, raw: z.string() }).refine(s => s.end >= s.start && s.end - s.start === s.raw.length, 'Span must preserve half-open UTF-16 offsets');
export const PartTwoSourceRefSchema = z.strictObject({ observationId: id, sourceRevision: rev, contentHash: digest, policyId: id, policyVersion: id, evidenceBasis: z.enum(['public_source', 'private_package']), observedAt: date, sourceUpdatedAt: date.nullable(), expiresAt: date, permitted: z.literal(true), sourceUrl: z.url().nullable(), attribution: z.string().nullable() });
export const PartTwoExplanationPolicySchema = z.strictObject({ policyId: id, policyHash: digest, sourceUrl: z.url(), roleDefinitionUrl: z.url(), licenceId: id, licenseUrl: z.url(), legalNoticeUrl: z.url(), sourceRevision: id, importVersion: id, sourceInventoryHash: digest, retrievedOn: z.iso.date(), reviewDate: date, reviewOwner: id, reviewScope: z.literal('local_editorial_only'), allowedFields: z.array(id), operations: z.strictObject({ process: z.boolean(), store: z.boolean(), display: z.boolean(), export: z.boolean() }), attribution: z.string(), retentionRule: z.string(), withdrawalDependencies: z.array(id), expiresAt: date, revoked: z.boolean() }).superRefine((policy, ctx) => { const { policyHash, ...content } = policy; if (sha256(canonicalJson(content)) !== policyHash) ctx.addIssue({ code: 'custom', message: 'Explanation policy hash differs from exact metadata' }); });
const observation = z.strictObject({ observationId: id, revision: rev });
const edit = z.strictObject({ observationId: id, supersedesId: id, revision: rev });
const commonBinding = { scanId: id, requestId: id, authenticatedOwnerId: id, bindingKey: id, generation: rev, evidenceRevision: rev, dependencyDigest: digest, deletionEpoch: rev, policyEpoch: rev, dictionaryEpoch: rev, expiresAt: date };
export const AuthorizedCaptureBindingSchema = z.strictObject({ ...commonBinding, kind: z.literal('capture'), ownerId: id, captureSessionId: id, packageObservationId: id, observations: z.array(observation).min(1).max(1000), attributedEdits: z.array(edit).max(1000) }).refine(b => b.ownerId === b.authenticatedOwnerId, 'Capture owner must be authenticated owner');
export const AuthorizedDeclarationBindingSchema = z.strictObject({ ...commonBinding, kind: z.literal('declaration'), captureSessionId: id.nullable(), itemId: id, snapshotId: id, snapshotRevision: rev, declarationId: id, declarationRevision: rev, scope: z.enum(['public', 'private_package']), ownerId: id.nullable(), packageObservationId: id.nullable(), packageConfirmation: PackageConfirmationSchema, requestedMarket: z.string().nullable(), sourceMarkets: z.array(z.string()), packageMarket: z.string().nullable(), observations: z.array(observation).min(1).max(1000), attributedEdits: z.array(edit).max(1000) }).refine(b => b.scope === 'public' ? b.ownerId === null && b.packageObservationId === null : b.ownerId === b.authenticatedOwnerId && b.packageObservationId !== null, 'Declaration scope/owner mismatch');
export const PartTwoBindingSchema = z.discriminatedUnion('kind', [AuthorizedCaptureBindingSchema, AuthorizedDeclarationBindingSchema]);
export const PartTwoClaimLimitsSchema = z.strictObject({ productPresenceAllowed: z.boolean(), declarationCompleteness: z.enum(['unestablished', 'partial', 'accepted']), negativeClaimsAllowed: z.literal(false) });
export const PartTwoReadingSectionSchema = z.strictObject({ sectionId: id, kind: z.enum(['ingredients', 'active', 'inactive', 'may_contain']), rawText: z.string(), sourceOffset: rev.default(0), observationId: id, sourceRevision: rev, transcription: z.enum(['clear', 'uncertain', 'conflict']), entryRefs: z.array(z.strictObject({ entryId: id, start: rev, end: rev, uncertaintyReasons: texts, conditional: z.string().nullable() })).max(1000) });
const sourceReading = z.strictObject({ kind: z.literal('source_reading'), scope: z.literal('private_package'), binding: AuthorizedCaptureBindingSchema, sections: z.array(PartTwoReadingSectionSchema), sourceRefs: z.array(PartTwoSourceRefSchema).min(1).max(1000), evidenceOutcome: z.enum(['partial', 'conflict', 'blocked']), claimLimits: PartTwoClaimLimitsSchema.extend({ productPresenceAllowed: z.literal(false), declarationCompleteness: z.literal('unestablished') }) });
const boundDeclaration = z.strictObject({ kind: z.literal('bound_declaration'), binding: AuthorizedDeclarationBindingSchema, bundle: FactBundleV1Schema, declaration: DeclarationSchema, sourceRefs: z.array(PartTwoSourceRefSchema).min(1).max(1000) });
export const NormalizationInputSchema = z.discriminatedUnion('kind', [sourceReading, boundDeclaration]).superRefine((input, ctx) => {
  const b = input.binding;
  const observations = new Map(b.observations.map(o => [o.observationId, o.revision]));
  if (observations.size !== b.observations.length || new Set(input.sourceRefs.map(s => s.observationId)).size !== input.sourceRefs.length) ctx.addIssue({ code: 'custom', message: 'Duplicate dependency references' });
  for (const s of input.sourceRefs) {
    if (observations.get(s.observationId) !== s.sourceRevision) ctx.addIssue({ code: 'custom', message: 'Source not in exact authorized observation set' });
    if (Date.parse(s.expiresAt) < Date.parse(b.expiresAt)) ctx.addIssue({ code: 'custom', message: 'Binding deadline exceeds source deadline' });
    if (input.kind === 'source_reading' && s.evidenceBasis !== 'private_package') ctx.addIssue({ code: 'custom', message: 'Capture source must be private' });
  }
  if (input.kind === 'source_reading') {
    for (const s of input.sections) {
      if (!input.sourceRefs.some(ref => ref.observationId === s.observationId && ref.sourceRevision === s.sourceRevision)) ctx.addIssue({ code: 'custom', message: 'Section missing exact source dependency' });
      for (const e of s.entryRefs) if (e.end <= e.start || e.end > s.rawText.length) ctx.addIssue({ code: 'custom', message: 'Invalid source entry span' });
    }
  } else {
    const { bundle: f, declaration: d, binding: db } = input;
    if (db.itemId !== f.itemId || db.snapshotId !== f.snapshotId || db.snapshotRevision !== f.snapshotRevision || db.declarationId !== f.declarationId || db.declarationRevision !== f.declarationRevision || db.declarationId !== d.declarationId || db.declarationRevision !== d.revision || db.itemId !== d.itemId || db.snapshotId !== d.snapshotId || db.scope !== f.scope || db.scope !== d.scope || db.ownerId !== f.ownerId || db.ownerId !== d.ownerId || db.packageObservationId !== d.packageObservationId || db.packageConfirmation !== f.packageConfirmation) ctx.addIssue({ code: 'custom', message: 'Authoritative declaration/bundle binding mismatch' });
    if (db.requestedMarket !== f.requestedMarket || JSON.stringify(db.sourceMarkets) !== JSON.stringify(f.sourceMarkets) || JSON.stringify(db.sourceMarkets) !== JSON.stringify(d.sourceMarkets) || db.packageMarket !== f.packageMarket || db.packageMarket !== d.packageMarket) ctx.addIssue({ code: 'custom', message: 'Market evidence differs from authoritative binding' });
    if (JSON.stringify(f.sections) !== JSON.stringify(d.sections)) ctx.addIssue({ code: 'custom', message: 'Bundle sections differ from immutable declaration' });
    if (Date.parse(db.expiresAt) > Math.min(Date.parse(f.expiresAt), Date.parse(d.expiresAt))) ctx.addIssue({ code: 'custom', message: 'Binding exceeds evidence deadline' });
    for (const s of input.sourceRefs) if (s.evidenceBasis !== (db.scope === 'public' ? 'public_source' : 'private_package')) ctx.addIssue({ code: 'custom', message: 'Source scope mismatch' });
    const entryIds = new Set<string>();
    for (const section of d.sections) {
      let cursor = 0;
      const bases = new Map<string, number>();
      for (const entry of section.entries) {
        const localStart = section.rawText.indexOf(entry.rawToken, cursor);
        if (!entry.rawToken || localStart < 0 || entry.sectionId !== section.sectionId || entryIds.has(entry.entryId)) ctx.addIssue({ code: 'custom', message: 'Entry raw text/order/section must match immutable section' });
        entryIds.add(entry.entryId);
        if (localStart >= 0) {
          cursor = localStart + entry.rawToken.length;
          if (entry.sourceSpans.length === 1 && entry.sourceSpans[0].start !== null && entry.sourceSpans[0].end !== null) {
            const source = entry.sourceSpans[0];
            const base = source.start! - localStart;
            if (source.end! - source.start! !== entry.rawToken.length || base < 0 || (bases.has(source.observationId) && bases.get(source.observationId) !== base)) ctx.addIssue({ code: 'custom', message: 'Entry source offsets disagree with section text' });
            bases.set(source.observationId, base);
          }
        }
      }
    }
    for (const section of d.sections) for (const entry of section.entries) for (const span of entry.sourceSpans) {
      if (!input.sourceRefs.some(s => s.observationId === span.observationId && s.sourceRevision === span.sourceRevision) || !d.observationIds.includes(span.observationId)) ctx.addIssue({ code: 'custom', message: 'Entry span missing exact source dependency' });
      if (span.start === null || span.end === null || span.end < span.start) ctx.addIssue({ code: 'custom', message: 'Entry requires literal source offsets' });
    }
  }
});
export const PartTwoMappingSchema = z.discriminatedUnion('state', [z.strictObject({ state: z.literal('resolved'), ingredientId: id, aliasRecordId: id, lookupKey: z.string(), rule: id, offsetMap: z.array(z.strictObject({ normalizedStart: rev, normalizedEnd: rev, sourceStart: rev, sourceEnd: rev })).max(4000) }), z.strictObject({ state: z.literal('ambiguous'), candidateIds: z.array(id).min(2).max(5) }), z.strictObject({ state: z.literal('unresolved'), reason: id })]);
export const PartTwoQuantitySchema = z.strictObject({ span: PartTwoSpanSchema, value: z.string().nullable(), min: z.string().nullable(), max: z.string().nullable(), operator: z.enum(['exact', 'less_than', 'less_than_or_equal', 'greater_than', 'greater_than_or_equal', 'range', 'approximate', 'unresolved']), unit: z.enum(['%', 'mg/g', 'mg/mL', 'unresolved']), basis: z.enum(['w/w', 'w/v', 'unknown']), subject: z.enum(['ingredient', 'blend', 'group', 'unresolved']), status: z.enum(['validated', 'parsed', 'invalid', 'conflict', 'unresolved']), reasons: texts, convertedPercentWw: z.string().nullable() }).superRefine((q, ctx) => { const issue = quantityValidationIssue(q); if (issue) ctx.addIssue({ code: 'custom', message: issue }); });
export const PartTwoOccurrenceSchema = z.strictObject({ occurrenceId: id, order: rev, sectionId: id, sectionKind: z.enum(['ingredients', 'active', 'inactive', 'may_contain']), rawToken: z.string(), observedName: z.string(), nameSpan: PartTwoSpanSchema, spans: z.array(PartTwoSpanSchema).min(1), entryRefs: z.array(id), transcription: z.enum(['clear', 'uncertain', 'conflict']), modality: z.enum(['unconditional', 'may_contain', 'alternative', 'unresolved']), qualifier: z.string().nullable(), mapping: PartTwoMappingSchema, quantities: z.array(PartTwoQuantitySchema).max(10), limitations: texts });
const factBase = { factId: id, occurrenceId: id, spans: z.array(PartTwoSpanSchema).min(1), rule: id, sourceDependencies: z.array(id).min(1), dictionaryDependencies: z.array(id), limitations: texts, validUntil: date };
const entrySubject = z.discriminatedUnion('kind', [z.strictObject({ kind: z.literal('reading_entry'), occurrenceId: id }), z.strictObject({ kind: z.literal('bound_declaration_entry'), declarationId: id, declarationRevision: rev, occurrenceId: id })]);
export const PartTwoFactSchema = z.discriminatedUnion('kind', [
  z.strictObject({ ...factBase, kind: z.literal('declared_ingredient'), subject: entrySubject, value: z.strictObject({ rawName: z.string(), order: rev, sectionKind: z.enum(['ingredients', 'active', 'inactive', 'may_contain']), modality: z.enum(['unconditional', 'may_contain', 'alternative', 'unresolved']) }) }),
  z.strictObject({ ...factBase, kind: z.literal('resolved_ingredient_identity'), subject: entrySubject, value: z.strictObject({ ingredientId: id, aliasRecordId: id }) }),
  z.strictObject({ ...factBase, kind: z.literal('declared_quantity'), subject: entrySubject, value: PartTwoQuantitySchema }),
  z.strictObject({ ...factBase, kind: z.literal('product_label_assertion'), subject: z.strictObject({ kind: z.literal('bound_label_assertion'), declarationId: id, declarationRevision: rev }), value: z.strictObject({ text: z.string(), attribution: z.literal('label_says'), assertionKind: z.enum(['category', 'usage', 'purpose', 'claim']) }) }),
  z.strictObject({ ...factBase, kind: z.literal('reference_function'), subject: z.strictObject({ kind: z.literal('ingredient_reference'), ingredientId: id }), value: z.strictObject({ roleId: id, explanationId: id, explanationRevision: rev, sentence: z.string().max(500), reviewDate: date, evidenceKind: z.enum(['source_inventory', 'reviewed_editorial']), sourceUrl: z.url(), sourceAttribution: z.string(), licenseUrl: z.url(), roleDefinitionUrl: z.url(), reviewOwner: id, policyId: id, policyHash: digest, sourceInventoryHash: digest }) }),
]);
export const PartTwoVersionsSchema = z.strictObject({ partOneParser: id, parser: id, dictionary: id, resolver: id, quantity: id, explanation: id, factPolicy: id });
export const PartTwoLiteralSectionSchema = z.strictObject({ sectionId: id, kind: z.enum(['ingredients', 'active', 'inactive', 'may_contain']), rawText: z.string(), sourceOffset: rev, observationId: id, sourceRevision: rev });
export const PartTwoSnapshotSchema = z.strictObject({ schemaVersion: z.literal(2), snapshotId: id, binding: PartTwoBindingSchema, scope: z.enum(['public', 'private_package']), evidenceState: z.enum(['partial', 'uncertain', 'accepted', 'conflict', 'blocked']), evidenceBasis: z.enum(['public_source', 'private_package']), packageConfirmation: PackageConfirmationSchema, claimLimits: PartTwoClaimLimitsSchema, literalSections: z.array(PartTwoLiteralSectionSchema).max(20), occurrences: z.array(PartTwoOccurrenceSchema).max(1000), facts: z.array(PartTwoFactSchema).max(10000), unresolvedSpans: z.array(PartTwoSpanSchema).max(2000), blockers: texts, versions: PartTwoVersionsSchema, dependencyManifest: z.strictObject({ sourceRefs: z.array(PartTwoSourceRefSchema).max(1000), dictionaryRecordIds: z.array(id).max(3000), dictionaryHash: digest, withdrawnExplanationDependencies: z.array(id).max(1000).default([]), explanationPolicies: z.array(PartTwoExplanationPolicySchema).max(1000), dependencyDigest: digest, deletionEpoch: rev, policyEpoch: rev, dictionaryEpoch: rev }), observedAt: date, sourceUpdatedAt: date.nullable(), createdAt: date, expiresAt: date }).superRefine((s, ctx) => {
  if (s.binding.kind === 'capture' && (s.scope !== 'private_package' || s.claimLimits.productPresenceAllowed || s.claimLimits.declarationCompleteness !== 'unestablished' || s.facts.some(f => f.subject.kind !== 'reading_entry' && f.subject.kind !== 'ingredient_reference'))) ctx.addIssue({ code: 'custom', message: 'Source reading cannot assert product/completeness' });
  if (s.facts.some(f => Date.parse(f.validUntil) > Date.parse(s.expiresAt))) ctx.addIssue({ code: 'custom', message: 'Fact exceeds snapshot deadline' });
  if (s.scope !== (s.binding.kind === 'capture' ? 'private_package' : s.binding.scope) || s.dependencyManifest.dependencyDigest !== s.binding.dependencyDigest || s.dependencyManifest.deletionEpoch !== s.binding.deletionEpoch || s.dependencyManifest.policyEpoch !== s.binding.policyEpoch || s.dependencyManifest.dictionaryEpoch !== s.binding.dictionaryEpoch || s.expiresAt !== s.binding.expiresAt) ctx.addIssue({ code: 'custom', message: 'Snapshot scope/lifecycle binding mismatch' });
  if (Date.parse(s.createdAt) >= Date.parse(s.expiresAt)) ctx.addIssue({ code: 'custom', message: 'Snapshot already expired at creation' });
  const occurrenceIds = new Set(s.occurrences.map(o => o.occurrenceId));
  if (occurrenceIds.size !== s.occurrences.length || new Set(s.facts.map(f => f.factId)).size !== s.facts.length) ctx.addIssue({ code: 'custom', message: 'Duplicate occurrence/fact identity' });
  const sourceMatches = (span: z.infer<typeof PartTwoSpanSchema>) => s.binding.observations.some(o => o.observationId === span.observationId && o.revision === span.sourceRevision) && s.dependencyManifest.sourceRefs.some(r => r.observationId === span.observationId && r.sourceRevision === span.sourceRevision && Date.parse(r.expiresAt) >= Date.parse(s.expiresAt));
  const literalContains = (span: z.infer<typeof PartTwoSpanSchema>) => s.literalSections.some(section => section.sectionId === span.sectionId && section.observationId === span.observationId && section.sourceRevision === span.sourceRevision && section.sourceOffset <= span.start && section.sourceOffset + section.rawText.length >= span.end && section.rawText.slice(span.start - section.sourceOffset, span.end - section.sourceOffset) === span.raw);
  if (s.literalSections.some(section => !sourceMatches({ ...section, entryId: null, start: section.sourceOffset, end: section.sourceOffset + section.rawText.length, raw: section.rawText }))) ctx.addIssue({ code: 'custom', message: 'Literal section missing exact source dependency' });
  const contains = (container: z.infer<typeof PartTwoSpanSchema>, span: z.infer<typeof PartTwoSpanSchema>) => container.observationId === span.observationId && container.sourceRevision === span.sourceRevision && container.sectionId === span.sectionId && container.entryId === span.entryId && container.start <= span.start && container.end >= span.end && container.raw.slice(span.start - container.start, span.end - container.start) === span.raw;
  if (s.evidenceBasis !== (s.scope === 'public' ? 'public_source' : 'private_package') || (s.binding.kind === 'declaration' && s.packageConfirmation !== s.binding.packageConfirmation) || s.dependencyManifest.sourceRefs.some(ref => ref.evidenceBasis !== s.evidenceBasis) || s.unresolvedSpans.some(span => !sourceMatches(span) || !literalContains(span))) ctx.addIssue({ code: 'custom', message: 'Snapshot attribution/unresolved span source mismatch' });
  for (const o of s.occurrences) {
    if (o.spans.length !== 1 || o.spans[0].raw !== o.rawToken || o.nameSpan.raw !== o.observedName || o.nameSpan.sectionId !== o.sectionId || o.spans.some(span => span.sectionId !== o.sectionId || !sourceMatches(span) || !literalContains(span) || (span.entryId !== null && !o.entryRefs.includes(span.entryId))) || !o.spans.some(span => contains(span, o.nameSpan)) || o.quantities.some(q => !o.spans.some(span => contains(span, q.span)))) ctx.addIssue({ code: 'custom', message: 'Occurrence literal span/source/entry mismatch' });
    const mapping = o.mapping;
    if (mapping.state === 'resolved' && (o.transcription !== 'clear' || o.modality === 'unresolved' || !s.dependencyManifest.dictionaryRecordIds.includes(mapping.ingredientId) || !s.dependencyManifest.dictionaryRecordIds.includes(mapping.aliasRecordId) || mapping.offsetMap.some(m => m.normalizedEnd < m.normalizedStart || m.normalizedEnd > mapping.lookupKey.length || m.sourceEnd < m.sourceStart || m.sourceStart < o.nameSpan.start || m.sourceEnd > o.nameSpan.end))) ctx.addIssue({ code: 'custom', message: 'Resolved mapping missing exact occurrence/dictionary dependency' });
  }
  for (const f of s.facts) {
    const o = s.occurrences.find(o => o.occurrenceId === f.occurrenceId);
    if (!o || o.transcription !== 'clear' || o.modality === 'unresolved' || f.spans.some(span => !o.spans.some(container => contains(container, span))) || f.sourceDependencies.some(dep => !f.spans.some(span => span.observationId === dep)) || f.spans.some(span => !f.sourceDependencies.includes(span.observationId)) || f.dictionaryDependencies.some(dep => !s.dependencyManifest.dictionaryRecordIds.includes(dep))) { ctx.addIssue({ code: 'custom', message: 'Fact missing exact occurrence/span/dependencies' }); continue; }
    if (['declared_ingredient', 'resolved_ingredient_identity', 'reference_function'].includes(f.kind) && !f.spans.some(span => contains(span, o.nameSpan))) ctx.addIssue({ code: 'custom', message: 'Fact source span does not support the complete observed name' });
    if ('occurrenceId' in f.subject && f.subject.occurrenceId !== f.occurrenceId) ctx.addIssue({ code: 'custom', message: 'Fact subject occurrence mismatch' });
    if ('declarationId' in f.subject && (s.binding.kind !== 'declaration' || f.subject.declarationId !== s.binding.declarationId || f.subject.declarationRevision !== s.binding.declarationRevision)) ctx.addIssue({ code: 'custom', message: 'Fact subject declaration mismatch' });
    if (f.kind === 'declared_ingredient' && (f.value.rawName !== o.observedName || f.value.order !== o.order || f.value.sectionKind !== o.sectionKind || f.value.modality !== o.modality)) ctx.addIssue({ code: 'custom', message: 'Declared fact strengthens or changes occurrence' });
    if (f.kind === 'resolved_ingredient_identity' && (o.mapping.state !== 'resolved' || f.value.ingredientId !== o.mapping.ingredientId || f.value.aliasRecordId !== o.mapping.aliasRecordId || !f.dictionaryDependencies.includes(f.value.ingredientId) || !f.dictionaryDependencies.includes(f.value.aliasRecordId))) ctx.addIssue({ code: 'custom', message: 'Identity fact differs from occurrence mapping' });
    if (f.kind === 'declared_quantity' && (!['parsed', 'validated'].includes(f.value.status) || f.value.operator === 'unresolved' || f.value.subject === 'unresolved' || !o.quantities.some(q => JSON.stringify(q) === JSON.stringify(f.value)) || !f.spans.some(span => JSON.stringify(span) === JSON.stringify(f.value.span)))) ctx.addIssue({ code: 'custom', message: 'Quantity fact differs from supported occurrence amount' });
    if (f.kind === 'reference_function' && (s.dependencyManifest.withdrawnExplanationDependencies.some(dep => f.dictionaryDependencies.includes(dep) || dep === f.value.explanationId || dep === f.value.policyId) || s.dependencyManifest.explanationPolicies.some(policy => policy.policyId === f.value.policyId && policy.withdrawalDependencies.some(dep => s.dependencyManifest.withdrawnExplanationDependencies.includes(dep))))) ctx.addIssue({ code: 'custom', message: 'Reference function depends on a durable withdrawal' });
    if (f.kind === 'reference_function' && !s.dependencyManifest.explanationPolicies.some(policy => policy.policyId === f.value.policyId && policy.policyHash === f.value.policyHash && policy.sourceInventoryHash === f.value.sourceInventoryHash && !policy.revoked && Object.values(policy.operations).every(Boolean) && Date.parse(policy.expiresAt) >= Date.parse(f.validUntil) && policy.sourceUrl === f.value.sourceUrl && policy.reviewDate === f.value.reviewDate && policy.attribution === f.value.sourceAttribution && policy.licenseUrl === f.value.licenseUrl && policy.roleDefinitionUrl === f.value.roleDefinitionUrl && policy.reviewOwner === f.value.reviewOwner && f.dictionaryDependencies.includes(policy.policyId))) ctx.addIssue({ code: 'custom', message: 'Function fact lacks current independent source rights policy' });
    if (f.kind === 'reference_function' && (o.mapping.state !== 'resolved' || f.subject.ingredientId !== o.mapping.ingredientId || !f.dictionaryDependencies.includes(f.value.explanationId) || !f.dictionaryDependencies.includes(f.subject.ingredientId))) ctx.addIssue({ code: 'custom', message: 'Function fact lacks exact identity/explanation dependencies' });
    if (f.kind === 'product_label_assertion' && !f.spans.some(span => span.raw === f.value.text)) ctx.addIssue({ code: 'custom', message: 'Label assertion must retain exact literal attribution' });
    if (o.modality !== 'unconditional' && !f.limitations.includes('conditional_not_definite_presence')) ctx.addIssue({ code: 'custom', message: 'Conditional fact lacks required limitation' });
  }
  if (s.claimLimits.productPresenceAllowed && !s.facts.some(f => f.kind === 'declared_ingredient' && f.subject.kind === 'bound_declaration_entry' && f.value.modality === 'unconditional')) ctx.addIssue({ code: 'custom', message: 'Product presence has no unconditional bound supporting fact' });
});
export const NormalizationOutputSchema = z.discriminatedUnion('kind', [z.strictObject({ kind: z.literal('reading_only'), reading: PartTwoSnapshotSchema }), z.strictObject({ kind: z.literal('bound'), reading: PartTwoSnapshotSchema, productFacts: PartTwoSnapshotSchema })]).superRefine((o, ctx) => {
  if (o.kind === 'reading_only' && o.reading.binding.kind !== 'capture') ctx.addIssue({ code: 'custom', message: 'Source reading requires capture binding' });
  if (o.kind === 'bound' && (JSON.stringify(o.reading.literalSections) !== JSON.stringify(o.productFacts.literalSections) || JSON.stringify(o.reading.occurrences) !== JSON.stringify(o.productFacts.occurrences) || JSON.stringify(o.reading.dependencyManifest) !== JSON.stringify(o.productFacts.dependencyManifest) || JSON.stringify(o.reading.versions) !== JSON.stringify(o.productFacts.versions) || o.reading.evidenceState !== o.productFacts.evidenceState || o.reading.evidenceBasis !== o.productFacts.evidenceBasis || o.reading.packageConfirmation !== o.productFacts.packageConfirmation || o.reading.claimLimits.declarationCompleteness !== o.productFacts.claimLimits.declarationCompleteness || o.reading.expiresAt !== o.productFacts.expiresAt || o.reading.observedAt !== o.productFacts.observedAt || o.reading.createdAt !== o.productFacts.createdAt)) ctx.addIssue({ code: 'custom', message: 'Product projection differs from immutable reading interpretation' });
  if (o.kind === 'bound' && (o.reading.facts.some(f => f.subject.kind !== 'reading_entry' && f.subject.kind !== 'ingredient_reference') || o.reading.binding.kind !== 'declaration' || JSON.stringify(o.reading.binding) !== JSON.stringify(o.productFacts.binding) || o.productFacts.facts.some(f => f.subject.kind === 'reading_entry'))) ctx.addIssue({ code: 'custom', message: 'Product facts require exact declaration binding' });
});
export const PermittedLiteralViewSchema = z.strictObject({ sections: z.array(z.strictObject({ sectionId: id, kind: z.enum(['ingredients', 'active', 'inactive', 'may_contain']), text: z.string() })).max(20), expiresAt: date });
const resultBinding = { scanId: id, captureSessionId: id.nullable(), schemaVersion: z.literal(2), requestId: id, authenticatedOwnerId: id, bindingKey: id, generation: rev, evidenceRevision: rev, resultRevision: rev, expiresAt: date };
export const NormalizationResultSchema = z.discriminatedUnion('state', [z.strictObject({ ...resultBinding, state: z.literal('ready'), output: NormalizationOutputSchema }), z.strictObject({ ...resultBinding, state: z.literal('pending'), permittedText: PermittedLiteralViewSchema.nullable() }), ...(['no_declaration', 'blocked', 'expired', 'parse_limit', 'failed'] as const).map(state => z.strictObject({ ...resultBinding, state: z.literal(state), reasonCodes: texts, permittedText: PermittedLiteralViewSchema.nullable() }))]).superRefine((r, ctx) => {
  if (r.state === 'ready') { const b = r.output.reading.binding; if (r.scanId !== b.scanId || r.captureSessionId !== b.captureSessionId || r.requestId !== b.requestId || r.authenticatedOwnerId !== b.authenticatedOwnerId || r.bindingKey !== b.bindingKey || r.generation !== b.generation || r.evidenceRevision !== b.evidenceRevision || r.expiresAt !== r.output.reading.expiresAt) ctx.addIssue({ code: 'custom', message: 'Ready result binding mismatch' }); }
  else if (r.permittedText && Date.parse(r.permittedText.expiresAt) > Date.parse(r.expiresAt)) ctx.addIssue({ code: 'custom', message: 'Literal deadline exceeds result' });
});
export const NormalizationRequestSchema = z.strictObject({ schemaVersion: z.literal(1), requestId: id, scanId: id, captureSessionId: id.nullable(), expectedGeneration: rev, expectedEvidenceRevision: rev });
export type NormalizationInput = z.infer<typeof NormalizationInputSchema>;
export type NormalizationResult = z.infer<typeof NormalizationResultSchema>;
export type NormalizationOutput = z.infer<typeof NormalizationOutputSchema>;
export type PartTwoBinding = z.infer<typeof PartTwoBindingSchema>;
export type PartTwoSnapshot = z.infer<typeof PartTwoSnapshotSchema>;
export type PartTwoOccurrence = z.infer<typeof PartTwoOccurrenceSchema>;
export type PartTwoQuantity = z.infer<typeof PartTwoQuantitySchema>;
export type PartTwoSpan = z.infer<typeof PartTwoSpanSchema>;
export type PartTwoFact = z.infer<typeof PartTwoFactSchema>;
export type PartTwoSourceRef = z.infer<typeof PartTwoSourceRefSchema>;
export type NormalizationRequest = z.infer<typeof NormalizationRequestSchema>;
