import { z } from 'zod';
import { profileSchema, referenceSchema, frequencySchema, experienceSchema } from '../../supabase/functions/personal-context/validate.ts';
const uuid=z.uuid().transform(v=>v.toLowerCase());
const revision=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER);
const timestamp=z.iso.datetime({offset:true}).refine(v=>/(Z|\+00:00)$/.test(v));
const text=(max:number)=>z.string().min(1).refine(v=>Array.from(v).length<=max).refine(v=>!/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(v));
const unique=<T extends {id:string}>(items:T[])=>new Set(items.map(i=>i.id)).size===items.length;
export const contextGoalSchema=z.enum(['breakouts','dark_spots','dryness','oiliness','texture','redness','fine_lines','simplify','maintain']);
export const purposeSchema=z.enum(['moisturizing','cleansing','sun_protection','other']);
export function answerSchema<T extends z.ZodType>(value:T) { return z.discriminatedUnion('state',[z.strictObject({state:z.literal('known'),value}),z.strictObject({state:z.literal('unanswered')}),z.strictObject({state:z.literal('unsure')}),z.strictObject({state:z.literal('withheld')})]); }
export const profileV2Schema=z.strictObject({...profileSchema.shape,primaryGoal:answerSchema(contextGoalSchema)}).refine(v=>v.primaryGoal.state!=='known'||!v.secondaryGoals.includes(v.primaryGoal.value));
const preciseDate=z.strictObject({value:z.string(),precision:z.enum(['day','month','year'])}).refine(v=>{
  if(v.precision==='year') return /^\d{4}$/.test(v.value)&&Number(v.value)>0;
  if(v.precision==='month') return /^\d{4}-(0[1-9]|1[0-2])$/.test(v.value);
  const d=new Date(v.value);return /^\d{4}-\d{2}-\d{2}$/.test(v.value)&&Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v.value;
});
export const reportedDateSchema=answerSchema(preciseDate);
const reported=<T extends z.ZodType>(value:T)=>z.strictObject({answer:answerSchema(value),provenance:z.literal('self_report')});
const useFields={timing:z.enum(['am','pm','both','unknown']),frequency:z.discriminatedUnion('kind',[
  frequencySchema.options[0],frequencySchema.options[1],z.strictObject({kind:z.literal('exact'),count:z.number().finite().positive().max(100),unit:z.enum(['day','week','month'])})]),startedOn:reportedDateSchema,stoppedOn:reportedDateSchema,
  duration:z.strictObject({count:z.number().finite().positive().max(1000),unit:z.enum(['days','weeks','months','years'])}).nullable(),
  reportedPurpose:reported(purposeSchema).optional(),applicationSite:reported(z.enum(['face','body','hands','scalp','lips','eye_area','other'])).optional(),useForm:reported(z.enum(['leave_on','rinse_off','other'])).optional()};
function dateBounds(d:z.infer<typeof reportedDateSchema>):[string,string]|null { if(d.state!=='known') return null; const v=d.value.value;return d.value.precision==='day'?[v,v]:d.value.precision==='month'?[v+'-01',v+'-31']:[v+'-01-01',v+'-12-31']; }
const coherent=(v:{startedOn:z.infer<typeof reportedDateSchema>;stoppedOn:z.infer<typeof reportedDateSchema>})=>{const a=dateBounds(v.startedOn),b=dateBounds(v.stoppedOn);return !a||!b||a[0]<=b[1];};
export const useContextV2Schema=z.strictObject(useFields).refine(coherent);
export const routineV2Schema=z.strictObject({completeness:z.enum(['partial','complete','unknown']),items:z.array(z.strictObject({id:uuid,reference:referenceSchema,state:z.enum(['current','paused','stopped','occasional']),...useFields}).refine(coherent)).max(50).refine(unique)});
export const experienceV2Schema=z.strictObject({...experienceSchema.shape,occurred:z.strictObject({start:reportedDateSchema,end:reportedDateSchema}).refine(v=>coherent({startedOn:v.start,stoppedOn:v.end})),useContext:useContextV2Schema.nullable()});
const target=z.discriminatedUnion('kind',[z.strictObject({kind:z.literal('ingredient'),identity:z.discriminatedUnion('kind',[z.strictObject({kind:z.literal('resolved'),ingredientId:text(100)}),z.strictObject({kind:z.literal('unresolved'),originalTerm:text(100)})])}),z.strictObject({kind:z.literal('product'),reference:referenceSchema}),z.strictObject({kind:z.literal('routine')})]);
export const preferenceSchema=z.strictObject({id:uuid,revision:revision.min(1),kind:z.enum(['avoid_ingredient','avoid_product','no_extra_step']),target,strength:z.enum(['decisive','prefer']),status:z.literal('confirmed'),confirmedAt:timestamp,source:z.discriminatedUnion('kind',[z.strictObject({kind:z.literal('structured')}),z.strictObject({kind:z.literal('note'),noteId:uuid,noteRevisionId:uuid,supportingSpan:text(2000),adoptedIndependently:z.boolean()})])}).refine(v=>v.kind==='avoid_ingredient'?v.target.kind==='ingredient':v.kind==='avoid_product'?v.target.kind==='product':v.target.kind==='routine');
export const productAssessmentSchema=z.strictObject({id:uuid,reference:referenceSchema,useContext:useContextV2Schema,reportingPeriod:z.strictObject({start:reportedDateSchema,end:reportedDateSchema}).refine(v=>coherent({startedOn:v.start,stoppedOn:v.end})),goalOrPurpose:answerSchema(z.union([contextGoalSchema,purposeSchema])),perceivedHelp:z.enum(['helps','mixed','not_helping','unsure','unanswered','withheld']),satisfaction:z.enum(['satisfied','mixed','dissatisfied','unsure','unanswered','withheld']),textureExperience:answerSchema(z.enum(['too_heavy','too_light','comfortable'])).optional(),assessedAt:timestamp,supersedesRevisionId:uuid.nullable().optional()});
export const contextNoteSchema=z.strictObject({id:uuid,scope:z.enum(['profile','routine_item','experience']),targetRef:uuid.nullable(),text:text(2000)}).refine(v=>(v.scope==='profile')===(v.targetRef===null));
export const setupV2Schema=z.strictObject({profile:profileV2Schema,routine:routineV2Schema,experiences:z.array(experienceV2Schema).max(20).refine(unique),preferences:z.array(preferenceSchema).max(20).refine(unique),assessments:z.array(productAssessmentSchema).max(20).refine(unique),notes:z.array(contextNoteSchema).max(20).refine(unique),setupAnswers:z.strictObject({currentProducts:z.enum(['unanswered','none','unsure','reported']),pastProducts:z.enum(['unanswered','none','unsure','reported'])})}).superRefine((v,ctx)=>{
  if(v.routine.items.length>20)ctx.addIssue({code:'custom',message:'At most 20 setup current products'});
  const ids=[...v.routine.items,...v.experiences,...v.preferences,...v.assessments,...v.notes].map(i=>i.id);if(new Set(ids).size!==ids.length)ctx.addIssue({code:'custom',message:'Duplicate record IDs'});
  for(const note of v.notes)if(note.targetRef&&!((note.scope==='routine_item'?v.routine.items:v.experiences).some(i=>i.id===note.targetRef)))ctx.addIssue({code:'custom',message:'Unknown note target'});
  for(const pref of v.preferences){const source=pref.source;if(source.kind==='note'&&!v.notes.some(n=>n.id===source.noteId&&n.text.includes(source.supportingSpan)))ctx.addIssue({code:'custom',message:'Unknown preference note source'});}
  if(v.setupAnswers.currentProducts==='none'&&v.routine.items.length)ctx.addIssue({code:'custom',message:'No products conflicts with reported items'});

});
export const personalContextV2RequestSchema=z.discriminatedUnion('operation',[z.strictObject({operation:z.literal('read_context_v2')}),z.strictObject({operation:z.literal('save_setup'),requestId:uuid,baseContextRevision:revision,setup:setupV2Schema}),z.strictObject({operation:z.literal('delete_context_record'),requestId:uuid,baseContextRevision:revision,record:z.strictObject({kind:z.enum(['profile','routine_item','experience','assessment','note','preference']),id:uuid.nullable()}).refine(v=>(v.kind==='profile')===(v.id===null))})]);
const revisionFields={id:uuid,ownerId:uuid,revision:revision.min(1),recordedAt:timestamp,provenance:z.literal('self_report'),supersedesRevisionId:uuid.nullable()};
const record=<T extends z.ZodType>(data:T)=>z.strictObject({...revisionFields,data});
export const personalContextV2Schema=z.strictObject({version:z.literal('personal-context-v2'),ownerId:uuid,revision,profile:record(profileV2Schema).nullable(),routine:record(routineV2Schema).nullable(),experiences:z.array(record(experienceV2Schema)),preferences:z.array(record(preferenceSchema)),assessments:z.array(record(productAssessmentSchema)),notes:z.array(record(contextNoteSchema)),historyTruncated:z.boolean(),historyRevision:uuid.nullable(),setupRevision:uuid.nullable(),setupAnswers:setupV2Schema.shape.setupAnswers.nullable(),legacy:z.strictObject({source:z.literal('legacy_free_context'),profile:z.record(z.string(),z.unknown()).nullable(),products:z.array(z.record(z.string(),z.unknown())),experiences:z.array(z.record(z.string(),z.unknown())),truncated:z.boolean()})}).superRefine((v,ctx)=>{for(const r of [v.profile,v.routine,...v.experiences,...v.preferences,...v.assessments,...v.notes])if(r&&(r.ownerId!==v.ownerId||r.revision>v.revision))ctx.addIssue({code:'custom',message:'Foreign or future context revision'});});
export const setupWriteResultSchema=z.strictObject({contextRevision:revision.min(1),revisionReferences:z.strictObject({setup:uuid,profile:uuid,routine:uuid,experiences:z.record(uuid,uuid),preferences:z.record(uuid,uuid),assessments:z.record(uuid,uuid),notes:z.record(uuid,uuid)}),replayed:z.boolean()});
export const contextDeleteResultSchema=z.strictObject({contextRevision:revision.min(1),deletedRevisionIds:z.array(uuid),replayed:z.boolean()});
